### ISSUE TITLE
UniTask for UnityEngine on NuGet

### ISSUE THREAD

**Issue by Trojaner** [Cysharp/UniTask#100]
Hello, I am developing a [plugin framework](https://github.com/openmod/OpenMod) for UnityEngine. It would be nice if the UnityEngine variants could be uploaded to NuGet too so I don't have to reference the dlls directly.

**Comment by neuecc** [comment]
Which version of UnityEngine.dll should reference?
I'm not sure I understand your plugin framework, but the
Referencing many UnityEngine.dll verions in NuGet feels difficult.

**Comment by Trojaner** [comment]
It could be the minimum required one only, or there could be one for each supported LTS release

**Comment by neuecc** [comment]
Thank you.
For example, already exists `#if UNITY_2020_2_OR_NEWER` and others.
Upload to `UniTask.Unity2019.4`, `UniTask.Unity2020.1`, etc... it's not very attractive.
It doesn't seem to be able to officially upload as UniTask.

**Comment by Trojaner** [comment]
Sad to hear, but thank you.
