### ISSUE TITLE
Exceptions take me to a weird place in the debugger.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Cysharp/UniTask#103]
```csharp
case TaskStatus.Faulted:
                        p.TrySetException(x.Exception);
                        break;
```

Can it instead take me to where the exception actually occurs?
If it is not a cancellation could it take me to the right function/line of code?

**Comment by neuecc** [comment]
I don't know what you mean.
Please provides more detail and code.

**Comment by neuecc** [comment]
related at #105 ?

**Comment by LiamKarlMitchell** [comment]
Yes looks like the related, missing the exception information where the error actually happened, takes you to UniTask code not your own code where the exception was thrown.
