### ISSUE TITLE
Firebase + UniTask issue

### ISSUE THREAD

**Issue by Nyankoo** [Cysharp/UniTask#106]
I'm currently using Firebase together with UniTask, and everything is working so far. When I tested exception behavior when the app is offline and Firebase Auth is trying to register a new user, I noticed that exceptions are thrown inside of the Firebase library instead of being bubbled up.
This is what I currently use:
```
try
            {
                NewFirebaseUser = await firebaseAuth.SignInAnonymouslyAsync();
                return AuthError.None;
            }
            catch(FirebaseException fe)
            {
                return (AuthError)fe.ErrorCode;
            }
```

When using the following code, the exception is not "thrown upwards" but kept in the task itself:
```
try
            {
                await firebaseAuth.SignInAnonymouslyAsync().ContinueWith((task) => 
                {
                    if(task.IsCanceled)
                    {
                        UnityEngine.Debug.LogError("CreateUserWithEmailAndPasswordAsync was canceled.");
                        return;
                    }
                    if(task.IsFaulted)
                    {
                        UnityEngine.Debug.LogError("CreateUserWithEmailAndPasswordAsync encountered an error: " + task.Exception);
                        return;
                    }
                });

                return AuthError.None;
            }
            catch(FirebaseException fe)
            {
                return (AuthError)fe.ErrorCode;
            }
```

This is actually using Task instead of UniTask, so I'm wondering how I should handle exceptions here to avoid them being only thrown inside Firebase code, which makes me unable to react to them.

**Comment by neuecc** [comment]
What is exception type?
Please check it, maybe `AggregateException`.
This is due to the very low quality of the Firebase Unity SDK,
Please send complaints to Google.

**Comment by Nyankoo** [comment]
@neuecc The main exception is a `FirebaseException`, but it is re-thrown as `AggregateException`.

What would be the correct way of handling this issue with UniTask?

**Comment by neuecc** [comment]
`catch(AggreageteException)` and retrieve from `.InnerExceptions`.
