### ISSUE TITLE
2.0.23 Unitask.WhenAny always fails

### ISSUE THREAD

**Issue by eplesse** [Cysharp/UniTask#107]
Hello, first of all congrats for this great component which made my life so much easier for async programming in unity.
This is quite an achievment !! 
I recently switched to 2.0.X release since UniTask could run wihtin editor. Unfortunaltely I massively use Unitask.WhenAny and it seems to fail the way I used to use it. 

Here is a test code which fails automatically as soon as first task is done. 

"Error: Operation is not valid due to the current state of the object."

Maybe I am using it badly. Thanks for your help

```
using Cysharp.Threading.Tasks;
using System;
using System.Collections.Generic;
using UnityEngine;

[ExecuteInEditMode]
public class UNniTastWhenAnyTester : MonoBehaviour
{
    public bool apply = false;

    private  async void Update()
    {
        if (apply)
        {
           apply = false;
           await LaunchTasksAndDetectWhenAnyDone(5);
        }
    }

    private async UniTask LaunchTasksAndDetectWhenAnyDone(int nbTasks)
    {
        List<UniTask<int>> sleeptasks = new List<UniTask<int>>();
        for (int i = 0; i < nbTasks; i ++)
        {
            sleeptasks.Add(SleepAndReturnTrue(i));
        }
        while(sleeptasks.Count > 0)
        {
            Debug.Log(DateTime.Now.ToString() + " waiting for " + sleeptasks.Count + " tasks...");
            try
            {
                (int index, int taskID) = await UniTask.WhenAny(sleeptasks);
                Debug.Log(DateTime.Now.ToString() + " Sleep task " + taskID + " done");
                sleeptasks.RemoveAt(index);
            }catch(Exception e)
            {
                Debug.Log("Error: " + e.Message);
                return;
            }
        }
    }

    private async UniTask<int> SleepAndReturnTrue(int taskIndex)
    {
        await UniTask.Delay(100);
        return taskIndex;
    }
}
```

**Comment by neuecc** [comment]
You're await twice(in second while loop).
Modify your code to avoid await twice, or quick workaround, change to following.
`sleeptasks.Add(SleepAndReturnTrue(i).ToAsyncLazy().Task);`

**Comment by eplesse** [comment]
ok. Indeed task conversion to lazy task solves the problem. Still have 2 remarks:.
- You say I am awaiting twice. Of course, I am, that is - according to me-  the whole point of using WhenAny (as with Tasks: https://docs.microsoft.com/fr-fr/dotnet/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete).: being able to loop on a bunch of tasks while being notified when one is done.
- That was how  it was working before 2.0.X. This to lazy conversion makes the function less "natural" to use to me.  

But anyway, thanks for your quick answer ! And UniTask is such a relief !!
Emmanuel

**Comment by neuecc** [comment]
NET's Task is evolving.
Task -> async/await -> ValueTask -> IValueTaskSource -> ManualResetValueTaskSourceCore

But in the process, quite a few of the rules became outdated.
UniTask is compliant with the latest ValueTask/IValueTaskSource.
https://docs.microsoft.com/en-us/dotnet/api /system.threading.tasks.tasks.valuetask-1?view= netcore-3.1
Therefore, some of the documentation written about Task does not apply.

If we had only used IValueTaskSource from the beginning, we wouldn't have had this problem.
In any case, .NET has a Task and a ValueTask(IValueTaskSource), there is confusion.
In Unity(UniTask), being UniTask only makes it better with only one rule.
I consider this to be a step forward, better than .

**Comment by eplesse** [comment]
thanks for your explanation. I am not quite sure I understand it fully since I never really dove very deep into Task/asyn/await inner mechanisms (too happy we could get rid of the "yield" hell). This is the occasion. I am definitively going to  take a serious look at it.
