### ISSUE TITLE
Return Addressables asset using synchronous loading

### ISSUE THREAD

**Issue by Noxalus** [Cysharp/UniTask#111]
Hello everyone!

Like most of developers using Unity's Addressables, I would like to load them synchronously since the assets will be available locally.

After a lot of researches, I found this project as the best way to use await/async C# keyword with Unity and a potential way to do what I would like with Addressable.

First thing I tried is to create a fresh new `MonoBehaviour` script and update the `Start` method like that:

```csharp
async void Start()
{
    string materialKey = "MY_MATERIAL_KEY";
    var material = await Addressables.LoadAssetAsync<Material>(materialKey).Task;
    Debug.Log(material);
}
```

And it's working as expected!

But now, I would like to create a method `GetMaterial` that will synchronously load the Addressables asset and return it. So I've started to create this method:

```csharp
private async Material GetMaterial(string materialKey)
{
    var material = await Addressables.LoadAssetAsync<Material>(materialKey).Task;
    return material;
}
```

It needs to be `async` to use `await` keyword, but because of that, I can't return the `Material` directly... (so this code doesn't compile).

So I've updated the code like that:

```csharp
void Start()
{
    string materialKey = "MY_MATERIAL_KEY";
    var material = GetMaterial(materialKey);
    Debug.Log(material);
}

private async UniTask<Material> GetMaterial(string materialKey)
{
    var material = await Addressables.LoadAssetAsync<Material>(materialKey).Task;
    return material;
}
```

But if I don't put an `await` for the call to `GetMaterial`, it won't work, the one in the `GetMaterial` doesn't seem to wait as I could expect it.

So to make it work, I need to update the `Start` method like that:

```csharp
async void Start()
{
    string materialKey = "MY_MATERIAL_KEY";
    var material = await GetMaterial(materialKey);
    Debug.Log(material);
}
```

Which is not really convenient because if the `Start` method needs to return something, it couldn't, except if it's a `Task` or `void`.

Do I really have all the methods as `async` when there is in `await` in one of them? 🤔

**Comment by neuecc** [comment]
Asynchronous methods cannot be essentially synchronous methods.
You can either make everything async/await or FireAndForget.

**Comment by Noxalus** [comment]
Thank you for your answer.

I've finally found a better solution, that doesn't imply to use UniTask anymore and is an official example to load Addressables assets synchronously [here](https://github.com/Unity-Technologies/Addressables-Sample#advancedsync-addressables) and it works like a charm for me 👍

**Comment by neuecc** [comment]
It doesn't look like a good sample at all, but if it can fulfill, that's fine.
