### ISSUE TITLE
[Addressables]same frame multiple do InstantiateAsync & ReleaseInstance(go),only first go will release

### ISSUE THREAD

**Issue by IllusionCui** [Cysharp/UniTask#112]
Debug:
Addressable source code,the handle has Done,the completed callback will call next frame.
AddressablesAsyncExtensions WithCancellation and ToUniTask await the handle has Done,will callback same frame.
So,ReleaseInstance(go) the Addressable can't find the go to handle map.

Suggest:
1、ReleaseInstance handle
2、Change AddressablesAsyncExtensions:
```
        public static UniTask WithCancellation(this AsyncOperationHandle handle, CancellationToken cancellationToken)
        {
            // if (handle.IsDone) return UniTask.CompletedTask;
            return new UniTask(AsyncOperationHandleWithCancellationSource.Create(handle, cancellationToken, out var token), token);
        }
```

```
        public static UniTask ToUniTask(this AsyncOperationHandle handle, IProgress<float> progress = null, PlayerLoopTiming timing = PlayerLoopTiming.Update, CancellationToken cancellationToken = default(CancellationToken))
        {
            // if (handle.IsDone) return UniTask.CompletedTask;
            return new UniTask(AsyncOperationHandleConfiguredSource.Create(handle, timing, progress, cancellationToken, out var token), token);
        }
```

By the way,Why "(handle.IsDone) return UniTask.CompletedTask"?

**Comment by neuecc** [comment]
The content and title seem vaguely obscure.
Can you providespecific code that says this is causing a bug?

**Comment by IllusionCui** [comment]
public class TestMono : MonoBehaviour
{
    void Start()
    {
        Test().Forget();
    }

    async UniTask Test()
    {
        for(int i = 0;i < 3;i++)
        {
            Debug.Log("Test S:" + Time.frameCount);
            var go = await Addressables.InstantiateAsync("Item101", Vector3.one * i, new Quaternion(0, 0, 0, 1)).WithCancellation<GameObject>(this.GetCancellationTokenOnDestroy());
            Debug.Log("Test E:" + Time.frameCount);
            go.name = "Test" + i;
            Addressables.ReleaseInstance(go);
        }
    }
}

The Test1&Test2 will not destory.

**Comment by neuecc** [comment]
I don't know details of Addressables but maybe ReleaseInstance(handle) works fine.

```csharp
var handle = Addressables.InstantiateAsync("Item101", Vector3.one * i, new Quaternion(0, 0, 0, 1));
var go = await handle.WithCancellation<GameObject>(this.GetCancellationTokenOnDestroy());
Debug.Log("Test E:" + Time.frameCount);
go.name = "Test" + i;
Addressables.ReleaseInstance(go);
```

Isn't this an issue with ReleaseInstance(GameObject)?
If so, please contact Addressables.

---

`(handle.IsDone) return UniTask.CompletedTask` means continue next line of await.
If `IsDone`, we can get instantiated gameobject correctly, and currently it works fine.

**Comment by IllusionCui** [comment]
Yes,ReleaseInstance(handle) works fine.
ReleaseInstance(go) not work,because:
Addressables add object to handle dictionary at next frame for handle.IsDone when the handle complete callback triggered.
UniTask continue next line of await at same frame.

Because handle's callback&Task(C#) work fine,I think the better way to handle the situation by AddressablesAsyncExtensions.
So, suggest the second way:
// if (handle.IsDone) return UniTask.CompletedTask;
continue next line of await at next frame.

**Comment by neuecc** [comment]
Once again, I think there is a problem with the Addressables implementation, so please report it to Unity.
It's crazy to say it's IsDone but not Done.

**Comment by neuecc** [comment]
This is an extension method to AsyncOperationHandle.
The problem stems from a poor implementation of InstantiateAsync, which is a result of
We can't change the whole implementation for InstantiateAsync.

The problem with InstantiateAsync is that the m_ If an OnHandleCompleteAction is set to
CompletedTypeless += m_ OnHandleCompleteAction;` because it's registered to
A naive implementation that needs to wait for the OnHandleCompleteAction to complete This is due to
This creates a timing problem, which is not considered by the Addressables implementers It is clear that

**Comment by neuecc** [comment]
reported at: https://forum.unity.com/threads/bug-release-not-work-when-check-asyncoperationhanlde-isdone-to-get-result-to-release-immediately.933306/
(and issue tracker number?)
