### ISSUE TITLE
Best practice for Return UniTask(warp UniTask and other logic process) with cancel process

### ISSUE THREAD

**Issue by IllusionCui** [Cysharp/UniTask#116]
For Example:
        private static async UniTask<T> AsyncOperationToTask<T>(AsyncOperationHandle<T> handle, CancellationToken token)
        {
            await handle.WithCancellation<T>(default(CancellationToken));
            if (token.IsCancellationRequested)
            {
                Addressables.Release(handle);
                return default(T);
            }
            return handle.Result;
        }

        private async UniTask Test()
        {
            var res = await AsyncOperationToTask<T>(handle, token);
            Debug.Log("continue");
        }
I want:
If token is not cancelled,there will have log "continue";
If token is cancelled,three will not have log "continue";
But:
there always have log "continue".

So,with different process for cancelled condition after other UniTasks.
I need to write self process UniTaskSouce?
Is there any easy way to do?

**Comment by neuecc** [comment]
use `throw new OperationCanceledException(token)` or `token.ThrowIfCancellationRequested`.

**Comment by IllusionCui** [comment]
Thank you very much
