### ISSUE TITLE
Sending a web request to a 404 path throws an error

### ISSUE THREAD

**Issue by Ristellise** [Cysharp/UniTask#117]
Under the `UnityWebRequestAsyncOperationAwaiter` struct:

```cs
public UnityWebRequest GetResult()
{
    if (continuationAction != null)
    {
        asyncOperation.completed -= continuationAction;
        continuationAction = null;
        var result = asyncOperation.webRequest;
        asyncOperation = null;
        if (result.IsError())
        {
            throw new UnityWebRequestException(result);
        }
        return result;
    }
    else
    {
        var result = asyncOperation.webRequest;
        asyncOperation = null;
        if (result.IsError())
        {
            throw new UnityWebRequestException(result);
        }
        return result;
    }
}
```
Throws *all* errors, including 404 & errors that are designed to be checked on the user end. Currently we would have to use a `try` & `catch` to catch these errors.  
Would it be possible to only include internal errors and exclude http errors? Thanks.

**Comment by neuecc** [comment]
Try-catch is required.
You can check if it is a 404 by using the `UnityWebRequestException.ResponseCode` or `.IsNetworkError`, `.IsHttpError`.

**Comment by Ristellise** [comment]
Not possible since `throw new UnityWebRequestException(result);`
Immediately breaks out of the function that my await is contained. So im unable to check it.

**Comment by Ristellise** [comment]
Ignore my previous deleted message, would try and catch be slower than check for an if statement or is it about the same?

**Comment by neuecc** [comment]
It's slow, but it should be infrequent, such as a 404.
If you're assuming frequent 404s, you're doing something wrong.
