### ISSUE TITLE
UniTaskCompletionSource.Reset removed, what should we replace it with?

### ISSUE THREAD

**Issue by albermotion** [Cysharp/UniTask#118]
I've been using Reset for every `UniTaskCompletionSource`, so after the breaking change in `2.0.19` I had to remove it.
What is the best way to use `UniTaskCompletionSource` now? Should we create a `new` instance everytime we want to use it again?
I've seen that you have also added `AutoResetUniTaskCompletionSource`, should we use this instead?

Thank you!

**Comment by chris-o3h** [comment]
Is there an upgrade guide? We ran into a few issues of compatibility moving from 1.x to 2.x and I'm not sure we made the right calls. 

For example:
```
             return new SampleData
             {
                // Module = getModuleTask.Result // 1.x Version; does not compile in 2.x
                Module = getModuleTask.AsTask().Result // 2.x; we think this is the appropriate solution
             };
```

Any hints on breaking changes and how to best navigate them would be of great help to everyone who upgrades.


Great library by the way!

**Comment by neuecc** [comment]
If you're using `Reset` for performance optimization, use the `UniTaskCompletionSourceCore`.
This has a `Reset`.

**Comment by albermotion** [comment]
> 
> 
> If you're using `Reset` for performance optimization, use the `UniTaskCompletionSourceCore`.
> This has a `Reset`.

I'm using `UniTaskCompletionSource` as a substitute of `TaskCompletionSource` if I was using pure C# Tasks.

Normally with `TaskCompletionSource` I would do a `new TaskCompletionSource` every time I want to reuse it. With `UniTaskCompletionSource` I was calling `.Reset()` until it's gone. 
I've seen you have implemented a new class called `AutoResetUniTaskCompletionSource` with a private constructor and a `Create()` method, but I didn't see it in the docs. Is this new class the substitute of `UniTaskCompletionSource` or should we use `UniTaskCompletionSourceCore`'s `Reset`?

**Comment by neuecc** [comment]
`UniTaskCompletionSource` is compatible with `TaskCompletionSource`.

AutoReset... follows UniTask's rules, such as only one await, can not await twice, etc.

UniTaskCompletionSourceCore is similar, but it is more of a manual control.
It is compatible with the `ManualResetValueTaskSourceCore` in .NET Core.

Both Auto and Core are advanced features.
I would recommend using UniTaskCompletionSource if you are not familiar with its behavior.
