### ISSUE TITLE
Using ToUniTask() with progress callback with autoReleaseHandle causes exception

### ISSUE THREAD

**Issue by randomPoison** [Cysharp/UniTask#119]
When using `ToUniTask()` on the `AsyncOperationHandle` returned by `DownloadDependenciesAsync()`, it looks like if I specify `autoReleaseHandle: true` to `DownloadDependenciesAsync()` and pass an `IProgress` object to `ToUniTask()`, this causes an exception to be thrown.

Code example:

```cs
await Addressables
	.DownloadDependenciesAsync(keys, Addressables.MergeMode.Union, autoReleaseHandle: true)
	.ToUniTask(Progress.Create<float>(percent => { ... }));
```

Exception thrown:

```text
Exception: Attempting to use an invalid operation handle
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle.get_InternalOp () (at Library/PackageCache/com.unity.addressables@1.12.0/Runtime/ResourceManager/AsyncOperations/AsyncOperationHandle.cs:306)
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle.get_PercentComplete () (at Library/PackageCache/com.unity.addressables@1.12.0/Runtime/ResourceManager/AsyncOperations/AsyncOperationHandle.cs:341)
Cysharp.Threading.Tasks.AddressablesAsyncExtensions+AsyncOperationHandleConfiguredSource.MoveNext () (at Library/PackageCache/com.cysharp.unitask@2.0.26/Runtime/External/Addressables/AddressablesAsyncExtensions.cs:303)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () (at Library/PackageCache/com.cysharp.unitask@2.0.26/Runtime/Internal/PlayerLoopRunner.cs:182)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.Internal.<>c:<.ctor>b__9_0(Exception) (at Library/PackageCache/com.cysharp.unitask@2.0.26/Runtime/Internal/PlayerLoopRunner.cs:25)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore() (at Library/PackageCache/com.cysharp.unitask@2.0.26/Runtime/Internal/PlayerLoopRunner.cs:203)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update() (at Library/PackageCache/com.cysharp.unitask@2.0.26/Runtime/Internal/PlayerLoopRunner.cs:127)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run() (at Library/PackageCache/com.cysharp.unitask@2.0.26/Runtime/Internal/PlayerLoopRunner.cs:94)
```

This seems to be happening because `AsyncOperationHandleConfiguredSource.MoveNext()` is not checking if the handle is still valid before attempting to get the current progress. You can use [`AsyncOperationHandle.IsValid()`](https://docs.unity3d.com/Packages/com.unity.addressables@1.12/api/UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle.html#UnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_IsValid) to check that first, which should work around the issue (though there might also be a better way to handle this case).

**Comment by randomPoison** [comment]
Also, I should be able to get a pull request together to fix this at some point, though I can't promise it'll be any time soon :sweat_smile:

**Comment by neuecc** [comment]
Thanks, I'm waiting for the PR.

**Comment by neuecc** [comment]
It is not only for progress, also can not take `handle.Result`.
I'll change `ToUniTask`'s internal source to same as `WithCancellation`, it is using `Completed` event so maybe can take result.

**Comment by neuecc** [comment]
In `2.0.27`, maybe fixed it.

**Comment by randomPoison** [comment]
Ah excellent! Thanks a ton for fixing this so quickly :heart:
