### ISSUE TITLE
Intended Monobehaviour entrypoint

### ISSUE THREAD

**Issue by SecretPocketCat** [Cysharp/UniTask#124]
The docs doen't really show an example how to work with monobehaviours and what are considered good practices when doing so.

Currently I'm doing a fire and forget from the regular synchronous Start to invoke an async function.

```
public abstract class AsyncBehaviour : MonoBehaviour
{
    private readonly CancellationTokenSource cts = new CancellationTokenSource();

    private bool asyncUpdateRunning;

    private void Start()
    {
        this.StartAsyncLoop().Forget();
    }

    private async UniTaskVoid StartAsyncLoop()
    {
        await this.StartAsync(this.cts.Token);

        // run the update loop
        await UniTaskAsyncEnumerable.EveryUpdate().ForEachAwaitAsync(async _ =>
        {
            if (!this.asyncUpdateRunning)
            {
                this.asyncUpdateRunning = false;
                await this.UpdateAsync(this.cts.Token);
                this.asyncUpdateRunning = true;
            }
        });
    }

    //...
}
```

Is this alright or am I being a naughty boy and there's a better way to achieve this?   

_BTW. I've looked through your repos and you are doing a lot of awesome work. I finally started doing some async in Unity, but as expected webgl just hangs - UniTask to the rescue :)_

**Comment by neuecc** [comment]
I don't recommend BaseClass as standard.
You can get `CellationToken` with `this.GetCancellationTokenOnDestroy`.
Also, replacing all of Update is an optional usage.

**Comment by SecretPocketCat** [comment]
@neuecc You wouldn't reccomend a base class why exactly? Composition vs inheritance or smt. else?  
To be honest, I'm not wild about it either, but this allows me to use a component with an async start and update when I happen to need it.  (I'm not gonna use it always, only when I want to do async).

But I'm still not sure about the entry point. Is starting it from the default Unity synchronous Start fine or is there a better way?  

THX about the CancellationToken tip

**Comment by neuecc** [comment]
Whether or not to use BaseClass is not a concern of UniTask.
Each application can do what it wants.
(I often create a common Base in my actual applications, too.)

entry point?
`async UniTaskVoid Start`.

**Comment by SecretPocketCat** [comment]
Nice, I didn't realise Unity would pick up on that.  

What I was looking for was an example of MonoBehaviour with UniTask, 'cause most of the samples are just snippets or good old classes (which is fine, just one example of a full MonoBehaviour using async would be nice or just specifying that it's not recommended because of X & Y). I was asking about MonoBehaviour specifically 'cause MonoBehaviour components are an integral part of Unity (unless one goes fully ECS I guess).
