### ISSUE TITLE
[Question]  await UniTask.WaitForEndOfFrame() Execution timing is different on computers and phones.

### ISSUE THREAD

**Issue by stnaw** [Cysharp/UniTask#125]
hi there，
I have a commandbuffer that I want to clear when EndOfFrame() is drawn (at this point, the commandbuffer is drawn.) When I use await UniTask.WaitForEndOfFrame() instead of unity's new WaitForEndOfFrame(), the commandbuffer is always emptied before it's drawn on a computer, but on a phone it's fine.

**Comment by neuecc** [comment]
`UniTask.WaitForEndOfFrame` is wait for last of PostLateUpdate.
https://gist.github.com/neuecc/bc3a1cfd4d74501ad057e49efcd7bdae
Coroutine's WaitForEndOfFrame seems to be running after PostLateUpdate.
Also, I don't know when your CommandBuffer is being filled, but if it's being handled outside of PlayerLoop, I can't guarantee the stability of the results.

**Comment by stnaw** [comment]
Thanks for the reply, my CommandBuffer is committing the draw command at the time of Update.  On the computer, I use await UniTask.Yield(PlayerLoopTiming.EarlyUpdate) and the result is right.
The order is like this: update->fill command->gpu draw->end of frame->clear command->next update...

**Comment by neuecc** [comment]
Very interesting!
As a UniTask, it can't seem to be able to handle it....
But I will try to come up with a solution.
