### ISSUE TITLE
Questions about implementation in UnityAsyncExtensions.Jobs

### ISSUE THREAD

**Issue by RamType-0** [Cysharp/UniTask#127]
I have many question about implementation in UnityAsyncExtensions.Jobs.

1.
https://github.com/Cysharp/UniTask/blob/c99d3eb3c3ebee0a9de569ac4dad6f11f70f100d/src/UniTask/Assets/Plugins/UniTask/Runtime/UnityAsyncExtensions.Jobs.cs#L12-L17
It seems like CancellationToken never works.
Currently,we could not cancel JobHandle.Complete,but we could still cancel UniTask.Yield. 
And why it says "cancelled" after job completes? 
If it takes CancellationToken only for future support,it is inconsistent between this signature.
https://github.com/Cysharp/UniTask/blob/c99d3eb3c3ebee0a9de569ac4dad6f11f70f100d/src/UniTask/Assets/Plugins/UniTask/Runtime/UnityAsyncExtensions.Jobs.cs#L33-L35
2.
https://github.com/Cysharp/UniTask/blob/c99d3eb3c3ebee0a9de569ac4dad6f11f70f100d/src/UniTask/Assets/Plugins/UniTask/Runtime/UnityAsyncExtensions.Jobs.cs#L19-L31
Why we don't await in other timings?(e.g. LastEarlyUpdate)

3.
https://github.com/Cysharp/UniTask/blob/c99d3eb3c3ebee0a9de569ac4dad6f11f70f100d/src/UniTask/Assets/Plugins/UniTask/Runtime/UnityAsyncExtensions.Jobs.cs#L52-L63
Why we don't use pool?

**Comment by neuecc** [comment]
I consider jobHandle.Complete to be essential to prevent leaks.
Check CancellationToken after complete is just to save the user calling Cancel manually after await.

> Why we don't await in other timings?(e.g. LastEarlyUpdate)

Last*** is almostly same as PreUpdate.
In other words, because it doesn't make sense.
If it does make sense, LastPostLateUpdate might be a good addition.

> Why we don't use pool?

handler is shared in many loops.

```
                PlayerLoopHelper.AddAction(PlayerLoopTiming.EarlyUpdate, handler);
                PlayerLoopHelper.AddAction(PlayerLoopTiming.PreUpdate, handler);
                PlayerLoopHelper.AddAction(PlayerLoopTiming.Update, handler);
```

when returns one(await completed) but others is running,  must not return to pool.
Using a pool requires a bit more fiddly implementation (like going back after all loops are completed)

**Comment by RamType-0** [comment]
Now I understood about 2 and 3.
But I'm still not sure about 1.
It says "Async",but possibly waits jobs synchronously.
and how does it's behaviour around CancellationToken helps us?
I think WaitAsync should be removed.

**Comment by neuecc** [comment]
synchronous wait for job is standard usage of jobsystem.
Otherwise, Allocator.TempJob will fail.

**Comment by RamType-0** [comment]
Waiting job synchronously is not bad,but what I want to say is that we could hardly imagine WaitAsync behaves like this(passed CancellationToken never canceles job,possibly wait synchronously) without any document.

BTW,TempJob allcation is valid for 4frames.(not a 1 frame)
