### ISSUE TITLE
Is it possible to get rid of `#if UNITY_EDITOR` inside runtime code?

### ISSUE THREAD

**Issue by Elringus** [Cysharp/UniTask#128]
I wonder if it's possible to remove editor-only code from the runtime code?

Specifically, the following two files:
https://github.com/Cysharp/UniTask/blob/b8260d4e91f3eac252e897ff5a6f0d1847e28f0a/src/UniTask/Assets/Plugins/UniTask/Runtime/Internal/TaskTracker.cs#L16
https://github.com/Cysharp/UniTask/blob/6ec0ed8d6132a36eb99a7097d85702cc3c052ff4/src/UniTask/Assets/Plugins/UniTask/Runtime/PlayerLoopHelper.cs#L15

This will allow compiling UniTask to a dll, distribute it with other packages more easily and prevent polluting user solution with additional projects.

**Comment by neuecc** [comment]
If you generate a DLL, don't you need a DLL that references UnityEditor (for Editor) and a DLL that doesn't reference UnityEditor (for Any Platform)?
In any case, there is no separation.

**Comment by Elringus** [comment]
> If you generate a DLL, don't you need a DLL that references UnityEditor (for Editor) and a DLL that doesn't reference UnityEditor (for Any Platform)?
When editor code is mixed with runtime code (which is a bad practice for a lot of reasons), two DLLs are required, right.

It's a pity you don't even want to consider improving the code.

**Comment by neuecc** [comment]
I don't think it's very beneficial, even from the UPM ecosystem.
I understand what you're saying about how ideally that would be better.
