### ISSUE TITLE
AssetbundleRequestのawaitについて

### ISSUE THREAD

**Issue by emptybraces** [Cysharp/UniTask#129]
UniTask使用させていただいております。ありがとうございます。

掲題の件について質問なのですが、AssetBundleからオブジェクト配列をAsyncロードするときに、
UniTaskではどのように記述すればいいのでしょうか。
`var request = await assetBunle.LoadAllAssetsAsync<AudioClip>();`
このとき、requestがUnityEngine.Objectなのですが、AudioClip[]かAssetBundleRequest.allAssetsにアクセスする
方法はありますでしょうか。

https://github.com/Cysharp/UniTask#basics-of-unitask-and-asyncoperation

UniTask Ver.2.0.27
Unity 2019.3.5f1

**Comment by emptybraces** [comment]
同種のissue#67見落としていました。失礼いたしました。

**Comment by neuecc** [comment]
@emptybraces 
最新のバージョンでは `AwaitForAllAssets` というのが用意されているので、
それをawaitすることで request は `AudioClip[]` になります(ReadMeにまだ書いてないので書いておかないと……)
