### ISSUE TITLE
why async alloc gc if not await?

### ISSUE THREAD

**Issue by bbsuuo** [Cysharp/UniTask#130]
i realize it's will  gc alloc  when i call function ,and it not waring
async UniTask Test(){
  if(false){
  await something....  
  }
}
Is there any way block gc alloc?

**Comment by neuecc** [comment]
If you see in Unity Profiler,

> In UnityEditor profiler shows allocation of compiler generated AsyncStateMachine but it only occurs in debug(development) build. C# Compiler generate AsyncStateMachine as class on Debug build and as struct on Release build.

**Comment by bbsuuo** [comment]
> 如果您在Unity Profiler中看到，
> 
> > 在UnityEditor中，探查器显示了编译器生成的AsyncStateMachine的分配，但仅在debug（development）构建中发生。C＃编译器在Debug版本上将AsyncStateMachine生成为类，在Release版本上将AsyncStateMachine生成为struct。

thanks ! Because I'm new to task, i just wrong this incurs additional gc, i will build it and test

**Comment by neuecc** [comment]
In Unity 2020.1, you can change debug/release C# compiler optimization mode on Unity Editor.

![image](https://user-images.githubusercontent.com/46207/89967342-2f944600-dc8c-11ea-99fc-0b74527a16f6.png)
