### ISSUE TITLE
Compatibility with unity package manager (UPM) ?

### ISSUE THREAD

**Issue by jcrombez** [Cysharp/UniTask#136]
Hi,

First thank you for this library, it's very helpfull !

Any chance to get compatibility with the "new" package manager Unity added recently ?

https://docs.unity3d.com/Manual/CustomPackages.html

**Comment by neuecc** [comment]
already supports git url or open upm, What are you seeking?
https://github.com/Cysharp/UniTask#upm-package

**Comment by jcrombez** [comment]
Oh right, it's at the end of the documentation, i missed it.
Thank you for poiting that out.
