### ISSUE TITLE
DOTween.SetAutoKill(false) is awaited forever

### ISSUE THREAD

**Issue by NoxCaos** [Cysharp/UniTask#137]
Tweens that have set autokill to `false` are still awaited until they are destroyed. The built-in OnComplete still fires without any problems. In my case I wanted to make a DOTween.Sequence that I can reuse, but turns out I cannot really await for it to complete without destroying and re-creating the sequence.
Is this an intentional behavior?

**Comment by neuecc** [comment]
Currently, I'm trying to stop it in conjunction with OnKill.
This is to stop all patterns of Complete(false/true) and Kill(false/true) without any problem.
It certainly seems to be a problem in the reuse case.
I'll try to solve this by adding an `AwaitForComplete` method, but what do you think?

**Comment by NoxCaos** [comment]
That could be a solution. The only problem that it is not intuitive behavior, like I would expect it to await the competition naturally.
Is it possible to maybe make `AwaitForComplete` and `AwaitForKill` and then regular `await` would work in both of those cases? I think that would make more sense and give more control to the end user. But I did not really check out the implementation yet to see if that is possible.

Just my thoughts, I am fine with any solution.

**Comment by neuecc** [comment]
It is possible to have two, but a default is required anyway.
The current state is AwaitForKill, and that will remain the default.

**Comment by neuecc** [comment]
`2.0.31`, adds `AwaitForComplete`, `AwaitForPause`, `AwaitForPlay`, `AwaitForRewind`, `AwaitForStepComplete`
