### ISSUE TITLE
Optimization proposal:Use ref T for ITaskPoolNode<T>.NextNode

### ISSUE THREAD

**Issue by RamType-0** [Cysharp/UniTask#143]
It seems that `ITaskPoolNode<T>.NextNode` is only used by `TaskPool<T>` to create linked list.
We could reduce virtual call by using ref T for `ITaskPoolNode<T>.NextNode`.
But this becomes breaking changes.
What do you think about it?
Should we create `ITaskPoolNode2<T>`?

**Comment by neuecc** [comment]
You can add benchmark to `UniTask.NetCoreSandbox/QueueCheck.cs`.
Discussion will start after seeing the results.

**Comment by RamType-0** [comment]
This is benchmark result in my environment.

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.450 (2004/?/20H1)
Intel Core i9-9900K CPU 3.60GHz (Coffee Lake), 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.100-preview.8.20417.9
  [Host]   : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT
  ShortRun : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT

Job=ShortRun  IterationCount=1  LaunchCount=1  
WarmupCount=1  

```
|              Method |     Mean | Error |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------- |---------:|------:|-------:|------:|------:|----------:|
|               Queue | 13.56 ns |    NA |      - |     - |     - |         - |
|           QueueLock | 63.81 ns |    NA |      - |     - |     - |         - |
|               Stack | 12.62 ns |    NA |      - |     - |     - |         - |
|           StackLock | 61.43 ns |    NA |      - |     - |     - |         - |
|     ConcurrentQueue | 35.29 ns |    NA |      - |     - |     - |         - |
|     ConcurrentStack | 39.62 ns |    NA | 0.0076 |     - |     - |      64 B |
|            TaskPool | 33.16 ns |    NA |      - |     - |     - |         - |
|     TaskPoolRefNode | 30.72 ns |    NA |      - |     - |     - |         - |
|   TaskPoolEqualNull | 33.52 ns |    NA |      - |     - |     - |         - |
|       TaskPoolClass | 32.83 ns |    NA |      - |     - |     - |         - |
| TaskPoolWithoutSize | 32.83 ns |    NA |      - |     - |     - |         - |
| TaskPoolWithoutLock | 20.41 ns |    NA |      - |     - |     - |         - |

**Comment by neuecc** [comment]
Thanks, seems good.
TaskPool is almostly internal so ok to breaking changes.
Let's change current `ITaskPoolNode.NextNode` to ref NextNode.
