### ISSUE TITLE
Question:Is there way to switch to main thread as soon as possible?

### ISSUE THREAD

**Issue by RamType-0** [Cysharp/UniTask#144]
UniTask.SwitchToMainThread only switch to main thread at one PlayerLoopTiming.
Is there way to switch to main thread as soon as possible?

**Comment by neuecc** [comment]
like JobHandle's await?
I'm not really interested in this because I have to change from a struct awaiter to a class and put a pool to share the state of await completion.

**Comment by RamType-0** [comment]
How about inserting same UniTask runner instance for multiple PlayerLoopTiming?

**Comment by neuecc** [comment]
SwitchToMainThread does not use the UniTask runner.

**Comment by RamType-0** [comment]
Sorry,that was not a exact.
I mean insert same ContinuationQueue instance for a multiple PlayerLoopTiming by PlayerLoopHelper.InsertRunner.

**Comment by neuecc** [comment]
If you do, the continuation will fire multiple times, right?
That's why I'm saying we need something to share the state.

**Comment by RamType-0** [comment]
Sorry,I have looked into ContinuationQueue.RunCore and ContinuationQueue.Enqueue implementation,
but I could not figure out the reason why continuation will fire multiple times.
Why calling ContinuationQueue.RunCore multiple times in another frame is safe, but in same frame is unsafe?

**Comment by neuecc** [comment]
I don't understand what you're talking about, can you give me a code example of how you'd like to do it?

**Comment by RamType-0** [comment]
```C#
var ASAPContinuationQueue = new ContinuationQueue(default);
var ASAPLoopRunner = new PlayerLoopRunner(default);

copyList[4].subSystemList = InsertRunner(copyList[4], typeof(SwitchToMainThreadASAPYieldUpdate), ASAPContinuationQueue,
                                                                  typeof(SwitchToMainThreadASAPLastYieldUpdate), ASAPContinuationQueue,
                                                                  typeof(SwitchToMainThreadASAPUpdate), ASAPLoopRunner,
                                                                  typeof(SwitchToMainThreadASAPLastUpdate), ASAPLoopRunner);


ASAPContinuationQueue.Enqueue(() => Debug.Log("Call ASAP on main thread!"));
```

This is what I meant.

**Comment by neuecc** [comment]
I don't understand it at all.
