### ISSUE TITLE
UniTask.SwitchToMainThread(PlayerLoopTiming) doesn't always ensure current PlayerLoopTiming

### ISSUE THREAD

**Issue by RamType-0** [Cysharp/UniTask#146]
UniTask.SwitchToMainThread(PlayerLoopTiming) doesn't ensure current PlayerLoopTiming if we are in MainThread.
Isn't it weird?

**Comment by neuecc** [comment]
Please use Yield.
It has a different function than Yield.

**Comment by RamType-0** [comment]
Yield uses continuation even if we are already in specified PlayerLoopTiming.

**Comment by neuecc** [comment]
If you have any expected behaviour, write it in a way that people can understand.

**Comment by RamType-0** [comment]
Here is my expected behaviour.

- UniTask.SwitchToMainThread()
  - Expected
  This works to be in main thread as soon as possible.
    - Already in main thread 
    Do nothing.
    - Otherwise 
    Switch to main thread as soon as possible.
  - Actual
    - Already in main thread 
    Do nothing.
    - Otherwise 
    Switch to main thread in next PlayerLoopTiming.Update. 
- UniTask.SwitchToMainThread(PlayerLoopTiming)
  - Expected
  This works to be in main thread and also in specified PlayerLoopTiming as soon as possible.
    - Already in main thread 
      - Already in specified PlayerLoopTiming
      Do nothing.
      - Otherwise
      Awaits next specified PlayerLoopTiming.
    - Otherwise 
    Switch to main thread in next specified PlayerLoopTiming.
- Actual
    - Already in main thread 
      - Already in specified PlayerLoopTiming
      Do nothing.
      - Otherwise
      Do nothing.
    - Otherwise 
    Switch to main thread in next specified PlayerLoopTiming.

- UniTask.Yield(PlayerLoopTiming)
This works exactly same as I expected,but doesn't work as replacement of my expected UniTask.SwitchToMainThread(PlayerLoopTiming).
  - Expected&Actual
    - Already in main thread 
      - Already in specified PlayerLoopTiming
      Skip specified PlayerLoopTiming of current,and awaits until next specified PlayerLoopTiming.
      - Otherwise
      Awaits next specified PlayerLoopTiming.
    - Otherwise 
    Switch to main thread in next specified PlayerLoopTiming.
