### ISSUE TITLE
Proposal: Custom PlayerLoopTiming combination

### ISSUE THREAD

**Issue by RamType-0** [Cysharp/UniTask#153]
Currently, registering continuation or IPlayerLoopTiming for multiple timing is not supported.
But we could do it by registering PlayerLoopRunner itself to PlayerLoopRunner,or registering ContinuationQueue to PlayerLoopRunner.
```C#
internal sealed class ContinuationQueue : IPlayerLoopItem//Mark itself as IPlayerLoopItem
{
    //...
        public bool MoveNext()
        {
            RunCore();
            return true;//Always returns true for persistent registration
        }
        static ContinuationQueue CreateMultipleTimings(params PlayerLoopTiming[] timings)
        {
            var runner = new ContinuationQueue(default/*This PlayerLoopTiming is just a dummy*/);
            foreach (var timing in timings)
            {
                PlayerLoopHelper.AddAction(timing,runner);
            }
            return runner;
        }
}
internal sealed class PlayerLoopRunner : IPlayerLoopItem//Mark itself as IPlayerLoopItem
{
    //...
        public bool MoveNext()
        {
            RunCore();
            return true;//Always returns true for persistent registration
        }
        static PlayerLoopRunner CreateMultipleTimings(params PlayerLoopTiming[] timings)
        {
            var runner = new PlayerLoopRunner(default/*This PlayerLoopTiming is just a dummy*/);
            foreach (var timing in timings)
            {
                PlayerLoopHelper.AddAction(timing,runner);
            }
            return runner;
        }
}


```

**Comment by neuecc** [comment]
Is this required for the implementation of #151?
Then try to implement it, including #151.
However, they may not adopt it.
At least, this code example doesn't appeal to me.

**Comment by RamType-0** [comment]
> Is this required for the implementation of #151?
> Then try to implement it, including #151.
> However, they may not adopt it.
> At least, this code example doesn't appeal to me.

This could be one of a good solution for #151 .
But even if this solution failed,another solution could be appliable to #151.
I'll try to resolve it by this solution.

But I want to question you at first of all,
do you think #151 is a "issue"?

**Comment by neuecc** [comment]
Impl like JobHandle's awaiter.
However, I don't intend to change it to struct -> class, so if you really want to do it, use an another name.

**Comment by RamType-0** [comment]
Maybe I could implement SwitchToMainThread like JobHandle's awaiter(register for multiple enough separated timings)with struct.
Should I still use another name?

**Comment by neuecc** [comment]
First, you need to provide the code.
