### ISSUE TITLE
IEnumerator.ToUniTask doesn't work correctly for IEnumerator which returns Coroutine

### ISSUE THREAD

**Issue by RamType-0** [Cysharp/UniTask#158]
Here's a code to reproduce this issue.

```C#
using Cysharp.Threading.Tasks;
using System.Collections;
using UnityEngine;

public class CoroutineSample : MonoBehaviour
{
    IEnumerator Coroutine()
    {
        Debug.Log("Wait for InnerCoroutine");
        yield return StartCoroutine(InnerCoroutine());
        Debug.Log("Exit Coroutine");
        
    }

    IEnumerator InnerCoroutine()
    {
        Debug.Log("Wait for 2 seconds in InnerCoroutine");
        yield return new WaitForSeconds(2);
        Debug.Log("Exit InnerCoroutine");
    }

    // Start is called before the first frame update
    IEnumerator Start()
    {
        Debug.Log("StartCoroutine");
        var startCoroutineStartTime = Time.time;
        yield return StartCoroutine(Coroutine());
        Debug.Log($"End of StartCoroutine\nElapsed time:{Time.time - startCoroutineStartTime}");
        Debug.Log("CoroutineToUniTask");
        var coroutineToUniTaskStartTime = Time.time;
        yield return Coroutine().ToUniTask().ToCoroutine();
        Debug.Log($"End of CoroutineToUniTask\nElapsed time:{Time.time - coroutineToUniTaskStartTime}");
    }
}

```

You can see unexpectedly shorter elapsed time for IEnumerator.ToUniTask with this code.

**Comment by neuecc** [comment]
also `WatiForFixedUpdate`.
Do you have any idea?

**Comment by RamType-0** [comment]
Does this work?
```C#
internal sealed class Coroutiner : MonoBehaviour
    {
        internal static Coroutiner instance;

        IEnumerator UniTaskCompletionCoroutine(object coroutine,AutoResetUniTaskCompletionSource uniTaskCompletionSource)
        {
            yield return coroutine;
            uniTaskCompletionSource.TrySetResult();
        }

        public UniTask ToUniTask(IEnumerator coroutine) => ToUniTask((object)coroutine);
        public UniTask ToUniTask(Coroutine coroutine) => ToUniTask((object)coroutine);
        
        UniTask ToUniTask(object coroutine)
        {
            var uniTaskCompletionSource = AutoResetUniTaskCompletionSource.Create();
            StartCoroutine(UniTaskCompletionCoroutine(coroutine, uniTaskCompletionSource));
            return uniTaskCompletionSource.Task;
        }
    }
```

**Comment by neuecc** [comment]
who instantiate MonoBehaviour?
So that means it's impossible.
It's by spec, will note to ReadMe.

**Comment by RamType-0** [comment]
Is it not allowed to just create new GameObject in DontDestroyOnLoad scene,and add this MonoBehaviour to it?

**Comment by neuecc** [comment]
not allowed.

**Comment by RamType-0** [comment]
So we could not support Coroutine,but maybe we could support WaitForFixedUpdate or WaitForEndOfFrame by just stop using IPlayerLoopItem, and use PlayerLoopHelper.AddContinuation instead.

**Comment by RamType-0** [comment]
But maybe it could have additional one frame latency for its complete if we don't have PlayerLoopHelper.TryGetCurrentPlayerLoopTiming().

**Comment by neuecc** [comment]
If you're saying you'll do AddContinuation every frame, that's a ridiculous design.

**Comment by RamType-0** [comment]
I'm really not sure about why AddContinuation every frame is a ridiculous design,(Of course, continuation action is pooled).
UniTask.Yield is doing so, isn't it?

If you think AddContinuation every frame is a ridiculous design,
I can also avoid it.
AddContinuation will called only when enumerator yields WaitForEndOfFrame or WaitForFixedUpdate.

**Comment by neuecc** [comment]
Then that's OK.

**Comment by RamType-0** [comment]
Current implemention calls MoveNext in specified PlayerLoopTiming,not always same as StartCoroutine with yield return null.

Is it an explicit design?
Or unintended behaviour to set end of awaiting timing to specified PlayerLoopTiming?

I can solve it,and also leave it.
Which would you like?

**Comment by neuecc** [comment]
PR please.
However, I don't know that will adopt.
