### ISSUE TITLE
UniTask.WaitForFixedUpdate is not a replacement of WaitForFixedUpdate,but FixedUpdate

### ISSUE THREAD

**Issue by RamType-0** [Cysharp/UniTask#160]
Although UniTask.WaitForEndOfFrame bahaves like yield return new WaitForEndOfFrame,
UniTask.WaitForFixedUpdate doesn't behave like yield return new WaitForFixedUpdate.
[FixedUpdate is called before physics update,WaitForFixedUpdate is called after physics update.](https://docs.unity3d.com/ja/2018.4/Manual/ExecutionOrder.html)

**Comment by neuecc** [comment]
What are you trying to say?
A list of timings is available at
https://gist.github.com/neuecc/bc3a1cfd4d74501ad057e49efcd7bdae

**Comment by RamType-0** [comment]
https://gist.github.com/neuecc/bc3a1cfd4d74501ad057e49efcd7bdae#gistcomment-3291978

If UniTask.WaitForFixedUpdate is designed to behaves like yield WaitForFixedUpdate, 
we should use UniTask.Yield(PlayerLoopTiming.LastFixedUpdate) in it implementation.
(Currently,it uses UniTask.Yield(PlayerLoopTiming.FixedUpdate).)
If it is designed to behaves like FixedUpdate,it's naming is really misleading.

**Comment by RamType-0** [comment]
WaitForUpdateがあるならもしかしたらWaitForFixedUpdateもそうなのかなあって想像がつくと思うんですけど、WaitForEndOfFrameとWaitForFixedUpdateしかなくてWaitForEndOfFrameがyield WaitForEndOfFrameと（ほぼ）同じなので、完全に罠だと思います

**Comment by neuecc** [comment]
FixedUpdate内での順序依存を大事に思ってたらそっちのほうがヤバいのでは。
（さすがにフレームの最後はめっちゃ重要なので、重要度が違う）
重要度を勘案せずにアレと一緒じゃないコレと一緒じゃないって騒ぐのはビミョーな論法ですね。
ただまぁ、極力合わせたほうがいいでしょ、という意見はそうだと思うので、変更はいれましょうか。

**Comment by RamType-0** [comment]
WaitForFixedUpdateとWaitForEndOfFrameがどっちも意味レベルじゃなく文字列として完全一致しちゃってるので、騒いだ次第です。
UniTask.WaitUntilFixedUpdateとかだったら何も言わなかったと思うので。

変更、って単純に中身をUniTask.Yield(PlayerLoopTiming.LastFixedUpdate)に差し替えるってことですか？
個人的には消したほうが良いと思います。理解して使うならUniTask.Yield使えばいい話ですし。
