### ISSUE TITLE
What would I need to do if I wanted to integrate UniTask with some other asynchronous API?

### ISSUE THREAD

**Issue by JesseTG** [Cysharp/UniTask#161]
I'm using UniTask in my game. Suppose that I need to integrate another asynchronous API whose nature I can't publicly discuss. It would make sense to implement UniTask support via custom `await`-able objects [much like you did for some Unity packages](https://github.com/Cysharp/UniTask#external-assets). However, I don't know how I would actually do this.

**What would I need to do to ensure that this mystery API can be used with UniTask as if it were natively supported?**

**Comment by neuecc** [comment]
The easiest way for convert is to use `UniTaskCompletionSource`.

```csharp
public UniTask<int> WrapByUniTaskCompletionSource()
{
    var utcs = new UniTaskCompletionSource<int>();

    // when complete, call utcs.TrySetResult();
    // when failed, call utcs.TrySetException();
    // when cancel, call utcs.TrySetCanceled();

    return utcs.Task; //return UniTask<int>
}
```

If you know UniTask's pooling mechanism, also you can use `AutoResetUniTaskCompletionSource` to avoid completion source's allocation.
You can also use `TaskPool` and `PlayerLoopHelper` as the most advanced and low-level patterns.

If you know a little bit about the .NET await pattern,
you can support await directly by implementing `GetAwaiter/IsCompleted/GetResult/I(Critical)NotifyCompletion`.

In any case, if you're not sure, start with `UniTaskCompletionSource`.
