### ISSUE TITLE
EnumeratorAsyncExtensions.cs throw a NullReferenceException at line 131 after upgrading to the latest version

### ISSUE THREAD

**Issue by LeeSinLcj** [Cysharp/UniTask#165]
Hello, When I upgraded UniTask to the latest version(2.0.32), sometimes it would throw a NullReferenceException while awaiting a Coroutine. And then I try to downgrade to version 2.0.27, everything works well. So I think this problem may have caused by the update of version 2.0.28. Could you have a look at this release? Thank you very much!

**Comment by neuecc** [comment]
Thanks, there seems to be a problem with the pool and the timing of the first manual run.
I'll fix it.

**Comment by LeeSinLcj** [comment]
Thank you ^_^

**Comment by neuecc** [comment]
fixed at `2.0.33`.
