### ISSUE TITLE
Problem while using native collection with UniTask

### ISSUE THREAD

**Issue by RamType-0** [Cysharp/UniTask#166]
If we awaiting in this kind of way, "finally" block will never executed if we quit application while awaiting task.
```C#
var na = new NativeArray<byte>(1,Allocator.Persistent);
try
{
    await someUniTask;
}
finally
{
    na.Dispose();
}

```

This resulted in native collection leak on editor.
Is there any solution?

**Comment by neuecc** [comment]
passing `CancellationToken` to someUniTask.

**Comment by RamType-0** [comment]
In most of this case,someUniTask itself or some of its descendants is JobHandle.
`CancellationToken` doesn't trigger continuation immediately.
Also, disposing native collection while executing job is not allowed.

**Comment by neuecc** [comment]
At least it's not NEVER.

**Comment by RamType-0** [comment]
Did you mean that it is possible if someUniTask itself or any of its descendants is not a job handle?
