### ISSUE TITLE
"Exception: Attempting to use an invalid operation handle" on Addressables.ClearDependencyCacheAsync().

### ISSUE THREAD

**Issue by tealm** [Cysharp/UniTask#167]
I get an invalid operation handle exception when trying to use UniTask with Addressables.ClearDependencyCacheAsync.
This only occurs when autoReleaseHandle is set as true.

`
var handle = Addressables.ClearDependencyCacheAsync("key", true);
await handle;
`

Unity 2019.4.10f1
Addressables 1.15.1

**Comment by neuecc** [comment]
Currently `AsyncOperationHandle.ToUniTask` checks `handle.IsValid()` and if not valid, throws exception.
But ClearDependencyCacheAsync(, true) release internal handle immediately so IsValid is false.

I'll change IsValid check from `throw exception` to `return completed task`.
This will probably be the behavior you expect.

**Comment by neuecc** [comment]
`2.0.34` changes behaviour.
