### ISSUE TITLE
Does this library work on consoles?

### ISSUE THREAD

**Issue by JesseTG** [Cysharp/UniTask#168]
Do you know (and are you allowed to say) whether or not UniTask works on all three major game consoles?

**Comment by neuecc** [comment]
It doesn't use any special APIs or native binaries, so I think it will work.
I have seen it working on one console.

**Comment by JesseTG** [comment]
Thank you. If it was for a commercially-released game, which game was it used in? I assume if it worked on the one console you describe, it works on the others.
