### ISSUE TITLE
ScreenCapture.CaptureScreenshotAsTexture() not working after await UniTask.WaitForEndOfFrame()

### ISSUE THREAD

**Issue by WraithKim** [Cysharp/UniTask#169]
I don't know where is the forum of UniTask, so write here.
This is code.
```CSharp
await UniTask.WaitForEndOfFrame();
ScreenCapture.CaptureScreenshotAsTexture();
```
If you run it, it throws this exception.
```
CaptureScreenshotAsTexture() failed to generate texture! Was method called before the 'end of frame' state was reached?
```
Why this happened and how can I solve it?

Tested at Unity 2019.4.4.f1 and UniTask 2.0.34

**Comment by neuecc** [comment]
Thanks.
UniTask.WaitForEndOfFrame is executed at the end of the PlayerLoopSystem.
This is not equivalent to yeield return new WaitForEndOfFrame.
The actual WaitForEndOfFrame seems to run after the PlayerLoopSystem is done.
And some of the methods seem to require it to be exactly last.

The current situation should be written in a coroutine.

**Comment by WraithKim** [comment]
Thanks for your answer.

I have no choice but use coroutine.
But, for someone might have same problem, I leave this issue as opened.

Whether close issue or not is yours. @neuecc

**Comment by neuecc** [comment]
I've added notice to ReadMe.
