### ISSUE TITLE
Warning Game scripts or other custom code contains OnMouse_ event handlers. 

### ISSUE THREAD

**Issue by HaSeungHo86** [Cysharp/UniTask#170]
Warning Game scripts or other custom code contains OnMouse_ event handlers. Presence of such handlers might impact performance on handheld devices.

Occurs when building Android, can I ignore it?

**Comment by neuecc** [comment]
Thank you.
This is a mistake, UNITY_ANDROID and UNITY_IOS should exclude it.

**Comment by HaSeungHo86** [comment]
Thank you. It’s very helpful
