### ISSUE TITLE
UniTaskScheduler.UnobservedTaskException don't called finally on Exception 

### ISSUE THREAD

**Issue by michael-spb-gor** [Cysharp/UniTask#174]
If we call **async UniTask Func()** with exception inside,
**UniTaskScheduler.UnobservedTaskException** will not be called if we don't ~~await~~ Func(). 
E.g. we have function **ExceptionTest()**, and in some cases we want to wait completion : **await ExceptionTest()**,
but in some cases we dont want to wait :  **ExceptionTest()**.
In second case on exception **UniTaskScheduler.UnobservedTaskException will not be called**.

`
   
    private void OnEnable()
    {
        UniTaskScheduler.UnobservedTaskException += HandleException;
    }

    private void HandleException(Exception obj)
    {
        Debug.LogError(obj.Message + "\n" + obj.StackTrace);
    }

    public async UniTask ExceptionTest()
    {
        await AsyncNonVoid(); // OK. call UniTaskScheduler.UnobservedTaskException
        AsyncNonVoid(); // NOT OK .. don't call UniTaskScheduler.UnobservedTaskException
    }
    
    private async UniTask AsyncNonVoid()
    {
        throw new Exception("AsyncNonVoid");
    } 

  
`
Best regards
And Thank You for great library :)

**Comment by neuecc** [comment]
Thank you.
The exceptions held in the UniTaskMethodBuilder for synchronous completion don't seem to be in the target of being Unobserved.
This behavior needs to be improved, but a little more technical validation is needed.

By the way, is this have a warning by the compiler?
I think it can be resolved as a workaround by calling `Forget()` properly or using `UniTaskVoid`.

**Comment by michael-spb-gor** [comment]
Yes, `UnitTaskVoid` or `Forget()` **can be workaround**. 
And no, using `UniTask Func()` without `await`, **have no compiler warnings**. 

Workarounds will work, but have some disadvantages
- If we want to use same `async UnitTask AsyncFunc()` function with `await` and witout `await`, we can't. It will be greate if it become awalable. Just like IEnumerator
`IEnumerator AsyncFunc()` 
`yield return AsyncFunc() // wait completion`
`StartCoroutine( AsyncFunc() ) // don't wait completion`

- Without compiler warnings/errors warkarounds are error prone (due to human inattention).  
It is easy to miss plases where `AsyncFunc()` called without await. For example after migrate from IEnumerator's.
