### ISSUE TITLE
Andriod/IL2CPP build increased 5M after using unitask

### ISSUE THREAD

**Issue by circleapps** [Cysharp/UniTask#175]
Comparing to the build using the stand Task from .NET, the build increased 5 megabytes after using unitask.
Is there anyway to avoid this problem? 
I'm using Unity 2019.4.9f1 with the latest version of unitask.

Thanks.

**Comment by neuecc** [comment]
Is there a reference to UniTask.Linq? If you reference it, please remove.

Also, UniTask uses many struct generics for inner Task runner to avoid allocations.
(See [my blog post](https://medium.com/@neuecc/unitask-v2-zero-allocation-async-await-for-unity-with-asynchronous-linq-1aa9c96aa7dd) for more details.)
This is very memory efficient but causes increase code size per type.
It's a trade-off.

**Comment by circleapps** [comment]
There is no reference to UniTask.Linq.
I understand that the struct generics will increase the size, but does not expect that much change.

Anyway, I will continue to evaluate this package, I learned a lot from your code, thanks.
