### ISSUE TITLE
How to reset a CancellationTokenSource? 

### ISSUE THREAD

**Issue by Wizzel1** [Cysharp/UniTask#176]
I need to have multiple CancellationTokenSource.cancel() calls in an Objects lifespan. 

Is there a way to "reset" the CancellationTokenSource or do I have to dispose the cancelled token and assign a new one? 

Thanks

**Comment by neuecc** [comment]
CancellationTokenSource can not reset.
By the way, combine multiple sources is to use a `CancellationTokenSource.CreateLinkedTokenSource`.

**Comment by kenofori** [comment]
@neuecc is there an alternative as of today in UniTask that doesnt generate garbage? if yes, please provide a sample code to use it as well as im a beginner. Thanks

**Comment by timcassell** [comment]
@kenofori See #601

**Comment by kenofori** [comment]
@timcassell Thank you for your reply, and I apologize for not fully understanding without a code example. I'd really appreciate it if you could demonstrate how to modify the following code to avoid recreating the CancellationTokenSource each time.


`   private async UniTaskVoid OnButtonClickedDebounced()
    {
        if (cts != null)
        {
            cts.Cancel();
            cts.Dispose();
        }

        cts = new CancellationTokenSource();

        try
        {
            await UniTask.Delay(500, cancellationToken: cts.Token);

            PerformAction();
        }
        catch (OperationCanceledException)
        {
        }
    }`

**Comment by timcassell** [comment]
UniTask does not provide an alloc-free cancelation source. If you need to avoid allocations, try using my ProtoPromise library instead (I saw you opened a discussion over there already). It contains an alloc-free cancelation source.

**Comment by neuecc** [comment]
I believe creating a custom CancellationToken in C#'s async/await is bad design.
A narrow-minded introduction is likely to degrade the overall user experience.

**Comment by kenofori** [comment]
> UniTask does not provide an alloc-free cancelation source. If you need to avoid allocations, try using my ProtoPromise library instead (I saw you opened a discussion over there already). It contains an alloc-free cancelation source.

I used it but somehow i got issues with Unity 6 compilation, and had to use UnityMainThreadDispatcher which didnt feel intuitive. Have you used ProtoPromise library with Unity? If yes, how would you approach it? Thanks

**Comment by kenofori** [comment]
> I believe creating a custom CancellationToken in C#'s async/await is bad design. A narrow-minded introduction is likely to degrade the overall user experience.

How would you recommend creating a debounce method in Unity C# with zero allocations?
https://angular.io/guide/http-optimize-server-interaction

**Comment by neuecc** [comment]
To add one more point, this is not the place to discuss other libraries, so please have that conversation in an appropriate place.
Also, please recognize that excessively promoting your own library is not a very refined behavior.
