### ISSUE TITLE
Major performance regression in v2

### ISSUE THREAD

**Issue by Elringus** [Cysharp/UniTask#177]
I've tried upgrading from v1 to the current release and noticed significantly increased GC allocations and CPU usage.

Here is the profiler result from v1:

![](https://i.gyazo.com/5d288993340e5568971f526cc14f6b70.png)

And here is the same code, but with UniTask v2.0.36:

![](https://i.gyazo.com/96b030c09d9ce4585329ff0d196045e4.png)

I've just removed v1, installed v2 and changed the namespaces. Running under Unity 2019.4.11.

It seems related with the delegate pooling. Is this a known issue or I'm missing something?

**Comment by neuecc** [comment]
Thank you for investigation.

It seems occur from `<ResetStateAsync>d__77.MoveNext()`, it is continuation of `async ResetStateAsync`'s await line.
Can you give me the details of this method?
I don't think the 964ms occurrence is caused by the library code.

**Comment by Elringus** [comment]
Sure, here is the method implementation:

```csharp
        public virtual async UniTask ResetStateAsync (Type[] exclude, params Func<UniTask>[] tasks)
        {
            OnResetStarted?.Invoke();

            if (Configuration.LoadStartDelay > 0)
                await UniTask.Delay(TimeSpan.FromSeconds(Configuration.LoadStartDelay));

            scriptPlayer?.Playlist?.ReleaseResources();

            Engine.Reset(exclude);

            await Resources.UnloadUnusedAssets();

            if (tasks != null)
            {
                foreach (var task in tasks)
                    await task?.Invoke();
            }

            OnResetFinished?.Invoke();
        }
```

**Comment by Elringus** [comment]
Somehow it stopped reproducing today. Not sure what was the cause in the first place, maybe something related with disabled domain reload and multiple profiling sessions. Sorry for the distraction!
