### ISSUE TITLE
[Feature Request] GetCancellationTokenOnDisable and Multiple await on same UniTask

### ISSUE THREAD

**Issue by SamiSdd** [Cysharp/UniTask#178]
Hey, Just added this issue because I want to confirm few things

GetCancellationTokenOnDisable
- Is there any reason or issue It's not available,
- For now, we can use UniRx OnDisableAsObservable to run this?

Multiple await on the Same UniTask

This code doesn't work and throws an exception

```cs
public class Test
{
    UniTask? process;
    public async UniTask Execute()
    {
        if (!process.HasValue)
        {
            process = CreateProcess();
        }

        await process.Value;
    }
}

public class TestRunner
{
    public void OnEnable()
    {
        var test = new Test();
        test.Execute().Forget();
        test.Execute().Forget(); // This will throw a exception
    }
}
```

This code works fine

```cs
public class Test
{
    Task process;
    public async Task Execute()
    {
        if (process == null)
        {
            process = CreateProcess();
        }

        await process;
    }
}

public class TestRunner
{
    public void OnEnable()
    {
        var test = new Test();
        test.Execute().Forget();
        test.Execute().Forget(); // This will throw a exception
    }
}
```

Is there a reason behind this other then UniTask is struct and Task is class?

BTW, Thanks for such a beautiful implementation, really helpful on mobile development, Only hope Unity learn something from this

**Comment by neuecc** [comment]
Because the CancellationTokenSource can only be used once, it was difficult to pass it to something that would repeatedly Enable/Disable.
However, we may add it in the next release since it seems to be solved by new CancellationTokenSource at the time of Enable.

---

Task can await multiple times but UniTask can not because UniTask('s internal awaiter) is pooled.
If you want to await multiple times, use `UniTask.Lazy` or `UniTaskCompletionSource`.

**Comment by Inspyro** [comment]
I have a question regarding 2 forgets. My code looks like this:

`_task = DoSomething(token).Forget()`

but now if I want to cancel that task I will call `_cts.Cancel() `
but then of course I need to wait for the task to be cancelled. How do I do that?
If I call await _task it will throw
`Already continuation registered, can not await twice or get Status after await.`

However if I remove the Forget() above and don't stop / cancel the task the exception will be swallowed

**Comment by Inspyro** [comment]
I think essentially instead of throwing this exception you should ignore the 2nd continuation (at least if it is a Forget() continuation) right? Or can I somehow unregister the Forget?

**Comment by neuecc** [comment]
I don't understand what you're talking about.
Basically, don't use Forget.
Handle OperationCanceledExceptions properly.
However, you should usually be able to ignore it.

**Comment by Inspyro** [comment]
Well I am trying to fire & forget a task but still store a reference to it so I can stop it if that makes sense.
Now I stop it by cancelling the cancellation token source, but I also want to wait until the task is cancelled

In normal .Net I just registered an exception handler for the fire&forget task, but i was still able to stop it and await the tasks completion. 

With UniTask this seems not possible? But maybe you have a suggestion for me? ;D

**Comment by Inspyro** [comment]
Essentially what I am trying to recreate is this:
`var coroutine = StartCoroutine(MyCoroutine)`
`StopCoroutine(coroutine)`
-> but the stop only happens in certain scenarios (and it needs to wait for the "coroutine" in this case task to be finished)

**Comment by Inspyro** [comment]
`Handle OperationCanceledExceptions properly.`
How can I handle those exceptions?

**Comment by neuecc** [comment]
```csharp
try
{
    await DoSomething(token);
}
catch (OperationCanceledException)
{
    // do nothing when canceled.
}

DoWhenTaskIsCompletedOrCanceled();
```

**Comment by Inspyro** [comment]
I think this code-example can provide some insight. I'm already using the try/catch logic you mentioned above.
```csharp
public class UniTaskForgetProblem : MonoBehaviour
{
  void Awake()
  {
    var cts = new CancellationTokenSource();

    var task = DownloadSomething(cts.Token);
    task.Forget();

    // we perform some kind of long runnig download
    async UniTask DownloadSomething(CancellationToken t)
    {
      await UniTask.Delay(500, cancellationToken: t);
      Debug.Log("we waited 0.5s");
    }

    // however the user might cancel the download at some point
    MaybeCancel().Forget();

    async UniTask MaybeCancel()
    {
      await UniTask.Delay(Random.Range(400, 600));
      cts.Cancel();

      try
      {
        // we need to wait for the task to be finished (how to do that with unitask?)
        await task;
      }
      catch (OperationCanceledException)
      {
      }
    }
  }
}
```

Now the problem is in the "edge-case" that the user wants to abort the download i have to cancel the task. Also I would be good to wait for the cancellation to finish.

**Comment by neuecc** [comment]
Ah, you want to wait cancellation completed from canceled method.

You can have a separate UniTaskCompletionSource to output the signal to Cancelation.
Or you can wrap it in UniTask.Lazy and handle it the same way as Task (delegating internally to UniTaskCompletionSource, so you can await more than once).

**Comment by Inspyro** [comment]
> You can have a separate UniTaskCompletionSource

How can I create such a completion source?

**Comment by neuecc** [comment]
```csharp
UniTaskCompletionSource completeSignal = new UniTaskCompletionSource();

DownloadSomething()
{
    try
    {
        await ....
    }
    finally
    {
        completeSignal.TrySetResult();
    }
}
```

**Comment by Inspyro** [comment]
Thanks for the help. It works now as expected :)
