### ISSUE TITLE
WebGL Compat Broken

### ISSUE THREAD

**Issue by stonstad** [Cysharp/UniTask#179]
The Unity WebGL player does not support ConcurrentDictionary and ConcurrentQueue, apparently.  See https://forum.unity.com/threads/webgl-runtimeerror-memory-access-out-of-bounds.949842/#post-6385872.  I'm a huge fan of UniTask, but I am wondering if WebGL support should be removed from the readme.

**Comment by neuecc** [comment]
Our unittest on WebGL works fine.

![image](https://user-images.githubusercontent.com/46207/95277534-fc83c280-0888-11eb-84cf-f0c530df9c1a.png)

Do you have any sample code that doesn't work?

**Comment by stonstad** [comment]
See http://fogbugz.unity3d.com/default.asp?1243361_i2ujptm2ut9qhjai.  After reviewing let me know so that I may remove this link.  In short, ConcurrentDictionary is not supported because it causes random crashes in the WebGL player.  Your unit tests work because, as you likely know, threading behavior is highly random.  Specific to Unitask, I have run into issues with its use of ConcurrentDictionary.  It throws a general WASM memory bounds error and if Count is called, it halts the WebGL player.

**Comment by neuecc** [comment]
First of all, UniTask does not use ConcurrentDictionary.Count.
Is this problem with ConcurrentDictionary in general?

I can stop using ConcurrentDictionary because I'm using it almost exclusively for diagnostics.
But first, I need some more evidence.
For example, your crash is not caused by ConcurrentDictionary, but by something else?

**Comment by stonstad** [comment]
Understood. Unity's position that ConcurrentDictionary is unsupported in WebGL builds is certainly incredulous.  The challenge you'll find in obtaining a consistent and repeatable stack trace is that the player freezes the browser tab or it throws a seemingly random memory bounds error when threading issues are encountered. 

The current state of things is that calls to ConcurrentDictionary.Count do freeze the runtime reliably, and everything else in the concurrent collections namespace is hit-or-miss -- failures occur based on frequency of use.

Cysharp.Threading.Tasks.TaskPool uses a concurrent dictionary when UniTask.Coroutine() is invoked.  My local change is as follows:

`public static class TaskPool
{
        internal static int MaxPoolSize;
#if (UNITY_WEBGL)
        static Dictionary<Type, Func<int>> sizes = new Dictionary<Type, Func<int>>();
#else
        static ConcurrentDictionary<Type, Func<int>> sizes = new ConcurrentDictionary<Type, Func<int>>(); 
#endif
}
`

If I have any new insight re: UniTask and WebGL compat, I'll share it here.  Thanks.

**Comment by neuecc** [comment]
> The current state of things is that calls to ConcurrentDictionary.Count do freeze the runtime reliably, and everything else in the concurrent collections namespace is hit-or-miss -- failures occur based on frequency of use.

Ok.
Dictionary may behave differently than usual when it exceeds Capacity.

TaskPool.sizes are for diagnostic purposes and are not important for performance.
Change it to Dictioanry and lock.

**Comment by neuecc** [comment]
I've released `2.0.37`, it removes ConcurrentDictionary code.
