### ISSUE TITLE
Can you recommend any Roslyn analyzers for asynchronous code?

### ISSUE THREAD

**Issue by JesseTG** [Cysharp/UniTask#180]
It's a little off-topic, but I figured that since you're well-versed in C# asynchronous programming and in Roslyn analyzers you'd have some useful insight.

Can you recommend any Roslyn analyzers focused on asynchronous programming that pair well with UniTask? They don't have to be written specifically for it.

**Comment by neuecc** [comment]
The most major one is the vsthreading analyzer, but some of them may not be suitable for UniTask.
https://github.com/microsoft/vs-threading/blob/master/doc/analyzers/index.md

**Comment by JesseTG** [comment]
Awesome, thank you. Which ones do you think would not be applicable to UniTask? I'm fairly new to `async` programming in C#, so I'm not familiar enough with standard `Task`s to be sure.
