### ISSUE TITLE
Discarded Async UniTasks not repooled

### ISSUE THREAD

**Issue by timcassell** [Cysharp/UniTask#181]
Hey, I've been running some benchmarks of your library against my own, and the benchmark tool shows your library allocating a lot with discarded async UniTasks. I pulled your code into a VS console application to use BenchmarkDotNet, of course I had to remove all of the Unity-specific code for it to compile.

I looked into your code a bit, and it appears that's because you only repool your objects when the GetResult is called (i.e. if it's awaited). I think if you always do what's in your `#if IL2CPP_ENABLED` code path (adding the object to the event queue to clean up later), but do it in SetResult/SetException should solve that issue (that's what I do in my library).

Btw, how can I execute your event queue without the Unity objects? [EDIT] Oh, looks like the `PlayerLoopHelper` is coupled to Unity objects, so guess I can't. I was hoping to get a more accurate benchmark with that. Is there any way for me to improve this benchmark?

```
[Benchmark]
public void UniTask()
{
    Promise.Config.ObjectPooling = Promise.PoolType.All;
    // Create a promise to await so that the async functions won't complete synchronously.
    Promise.Deferred deferred = Promise.NewDeferred();
    Promise promise = deferred.Promise;
    long counter = 0L;

    for (int i = 0; i < N; ++i)
    {
        _ = TaskVoid();
        _ = TaskVector();
        _ = TaskObject();
    }

    async UniTask TaskVoid()
    {
        Interlocked.Increment(ref counter);
        await promise;
        Interlocked.Decrement(ref counter);
    }

    async UniTask<Vector4> TaskVector()
    {
        Interlocked.Increment(ref counter);
        await promise;
        Interlocked.Decrement(ref counter);
        return vector;
    }

    async UniTask<object> TaskObject()
    {
        Interlocked.Increment(ref counter);
        await promise;
        Interlocked.Decrement(ref counter);
        return obj;
    }

    deferred.Resolve();
    Promise.Manager.HandleCompletesAndProgress();
    while (Interlocked.Read(ref counter) > 0) { }
}
```

```
| Allocated |
|----------:|
| 5857355 B |
```

**Comment by neuecc** [comment]
For .NET Core, use `UniTask.NetCore.sln` (that includes `UniTask.NetCore.csproj`).

It is recommended to use `UniTaskVoid` or `.Forget()`.
The destructor can be used to automatically collect them during GC, but the
I quit due to its frequency and the difficulty of handling destructor looping correctly with IL2CPP.

**Comment by timcassell** [comment]
In terms of using the destructor/finalizer to repool objects, I had thought about that before also, but it really doesn't alleviate the issue of GC pressure (hitting the finalizer at all is GC pressure), so I solved that by doing a delayed repool instead of forcing the developer to call another method to clean it up (like your `Forget` or RSG Promise's `Done`).

Okay cool, so I was able to build the dlls from that solution and used the netstandard 2.0 dll in my benchmark project.

I'm still getting some odd results in the .Net Framework 4.7.2 runtime, though, it's still showing a lot of allocations. Any idea why that might be (.Net Core and Mono both seem okay)?

```
|     Method |        Job |    Runtime |     N |     Mean |    Error |   StdDev |   Median | Ratio | RatioSD |     Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|----------- |----------- |----------- |------ |---------:|---------:|---------:|---------:|------:|--------:|----------:|---------:|---------:|----------:|
| SystemTask | Job-KZKWXR |   .NET 4.8 | 10000 | 31.86 ms | 0.454 ms | 0.402 ms | 31.89 ms |  1.00 |    0.00 | 1312.5000 | 562.5000 |  62.5000 | 7301782 B |
|    UniTask | Job-KZKWXR |   .NET 4.8 | 10000 | 20.62 ms | 0.233 ms | 0.218 ms | 20.62 ms |  0.65 |    0.01 |   62.5000 |  31.2500 |        - |  376368 B |
|    Proto_N | Job-KZKWXR |   .NET 4.8 | 10000 | 50.60 ms | 0.995 ms | 1.259 ms | 50.54 ms |  1.59 |    0.04 | 1100.0000 | 500.0000 | 200.0000 | 6419514 B |
|    Proto_A | Job-KZKWXR |   .NET 4.8 | 10000 | 12.29 ms | 0.243 ms | 0.497 ms | 12.57 ms |  0.37 |    0.01 |         - |        - |        - |         - |
|            |            |            |       |          |          |          |          |       |         |           |          |          |           |
| SystemTask | Job-OUGRBP | CoreRt 3.1 | 10000 | 15.28 ms | 0.293 ms | 0.274 ms | 15.21 ms |  1.00 |    0.00 |  843.7500 | 406.2500 |        - | 5120032 B |
|    UniTask | Job-OUGRBP | CoreRt 3.1 | 10000 | 17.02 ms | 0.190 ms | 0.158 ms | 17.01 ms |  1.12 |    0.02 |         - |        - |        - |         - |
|    Proto_N | Job-OUGRBP | CoreRt 3.1 | 10000 | 35.76 ms | 0.462 ms | 0.432 ms | 35.83 ms |  2.34 |    0.05 | 1062.5000 | 375.0000 | 125.0000 | 5920262 B |
|    Proto_A | Job-OUGRBP | CoreRt 3.1 | 10000 | 10.71 ms | 0.149 ms | 0.139 ms | 10.67 ms |  0.70 |    0.01 |         - |        - |        - |         - |
|            |            |            |       |          |          |          |          |       |         |           |          |          |           |
| SystemTask | Job-IAWAXN |       Mono | 10000 | 40.34 ms | 0.262 ms | 0.233 ms | 40.37 ms |  1.00 |    0.00 | 2000.0000 | 307.6923 | 307.6923 |         - |
|    UniTask | Job-IAWAXN |       Mono | 10000 | 21.49 ms | 0.103 ms | 0.091 ms | 21.49 ms |  0.53 |    0.00 |         - |        - |        - |         - |
|    Proto_N | Job-IAWAXN |       Mono | 10000 | 89.36 ms | 0.720 ms | 0.639 ms | 89.19 ms |  2.22 |    0.02 | 1714.2857 | 285.7143 | 285.7143 |         - |
|    Proto_A | Job-IAWAXN |       Mono | 10000 | 13.22 ms | 0.162 ms | 0.152 ms | 13.19 ms |  0.33 |    0.00 |         - |        - |        - |         - |
```

**Comment by neuecc** [comment]
I don't know the difference in .NET 4.8, but it's an interesting result.

**Comment by timcassell** [comment]
In case you're interested...

I ran your benchmark on my machine (old AMD Phenom II x6) and saw your results very close to Task's, if not slightly slower (ignoring the allocations).

```
|   Method |   Categories |     Mean | Error |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |------------- |---------:|------:|-------:|------:|------:|----------:|
|     .NET |      Task<T> | 3.599 μs |    NA | 0.0352 |     - |     - |     120 B |
|   Pooled |      Task<T> | 3.779 μs |    NA | 0.0195 |     - |     - |      72 B |
|          |              |          |       |        |       |       |           |
|     .NET |         Task | 3.580 μs |    NA | 0.0352 |     - |     - |     112 B |
|   Pooled |         Task | 3.650 μs |    NA | 0.0195 |     - |     - |      72 B |
|          |              |          |       |        |       |       |           |
|     .NET | ValueTask<T> | 3.762 μs |    NA | 0.0391 |     - |     - |     128 B |
|   Pooled | ValueTask<T> | 4.045 μs |    NA |      - |     - |     - |         - |
|          |              |          |       |        |       |       |           |
|     .NET |    ValueTask | 3.733 μs |    NA | 0.0352 |     - |     - |     120 B |
|   Pooled |    ValueTask | 3.644 μs |    NA |      - |     - |     - |         - |
|          |              |          |       |        |       |       |           |
|  UniTask |      UniTask | 3.684 μs |    NA |      - |     - |     - |         - |
| UniTaskT |      UniTask | 3.747 μs |    NA |      - |     - |     - |         - |
```

My benchmarks show UniTask winning on .Net Framework and Mono, but losing in .Net Core 3.1 (I'm actually impressed by how much they have optimized Tasks in .Net Core). I'm testing async and await separately in my benchmarks while yours are tested together, but it seems we're getting similar results either way (in Core).

https://github.com/timcassell/CSharpAsynchronousBenchmarks

P.S. No idea why, but several of the UniTask tests (await and ContinueWith) failed with the Mono runtime (and not due to StackOverflow like I expect with the N = 10k ContinueWith). I got this error if it means anything to you (I'm guessing not since this was ran with the dll, not source)...
```
* Assertion at ..\mono\mini\intrinsics.c:1039, condition `mini_type_is_reference (fsig->params [0])' not met
```

**Comment by neuecc** [comment]
I don't understand what you are trying to measure.
You seem to have implemented it a bit, so I'm sure you understand.

* async code, synchronous complete
* aysnc code, asynchronous complete
* TaskCompletionSource, already completed
* TaskCompletionSource, not completed(register continuation)

All of these code paths are different.
I looked at the benchmark codes, but the measurements are messed up and the results are useless.

**Comment by timcassell** [comment]
Yes I understand the different code paths (my benchmark doesn't have async complete sync). Could you please explain how the measurements are messed up? I'd like to fix that if there's an issue.
