### ISSUE TITLE
What exactly run on a single thread ?

### ISSUE THREAD

**Issue by oktomus** [Cysharp/UniTask#184]
UniTask's README states: 

> Most UniTask methods run in a single thread (PlayerLoop), but only UniTask.Run and UniTask.SwitchToThreadPool run on a thread pool. If you use a thread pool, it won't work with WebGL and so on.

I'm concerned about "*Most UniTask methods run in a single thread*". 

More precisely, I'm wondering when do we have to call `UniTask.SwitchToMainThread` ? 

From my understanding, we need to call `SwitchToMainThread` when we interact with Unity from another thread (with `Unitask.Run` or `UniTask.SwitchToThreadPool`).

**Comment by neuecc** [comment]
As you understand it.

**Comment by oktomus** [comment]
So even `DoSomethingAsync` in this case will run on the main thread ?

```csharp
Button.OnClick += () => DoSomethingAsync().Forget();
```

**Comment by neuecc** [comment]
It depends on the body of `DoSomethingAsync`.

**Comment by oktomus** [comment]
> 
> 
> It depends on the body of `DoSomethingAsync`.

Sorry, I wasn't very precise. The most basic use case is the following : 

```csharp
public async UniTask DoSomethingAsync()
{
    await UniTask.WaitForEndOfFrame();
    // .. Something not async
   View.PopulateOrWhatever();
}
