### ISSUE TITLE
How to handle transition from Play mode to Edit mode, cleaning up objects in 'try finally' block

### ISSUE THREAD

**Issue by prodigga** [Cysharp/UniTask#186]
Hi there.

I am seeking advice from the author. I have looked at the games that your company has worked on (Cygames) and see you've worked on many large games! I assume you use UniTask in some of those games?

I've recently started using Async code, but am having trouble with 'exit playmode' in the editor. I use Disposable objects and 'try/finally' blocks to clean up some objects during regular execution. However, when my task is cancelled when exiting play mode, my code wants to clean up objects that does not exist any more. This is a _very_ simple example:

```csharp
var ct = this.GetCancellationTokenOnDestroy();
var popup = Instantiate(popupPrefab);
try
{
    await popup.WaitTillClosed(ct);
}
finally
{
    Destroy(popup);
}
```

If play mode is stopped in the editor while popup is waiting to close, the 'wait till close' will throw `OperationCanceledException`, and my `finally` block will attempt to destroy the popup to clean up... but the popup is already destroyed! Because we are exiting play mode!

Any advice here? What is the best way to handle these situations..? Should I just avoid using `try/finally` or `IDisposable`s with `using(...)`?

**Comment by neuecc** [comment]
This search result's screen shots(japanese mobile games) is credited my library(Cysharp, Yoshifumi Kawai, neuecc).
https://twitter.com/search?q=%E6%8E%A1%E7%94%A8%E3%81%82%E3%82%8A%E3%81%8C%E3%81%A8%E3%81%86%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99%20(from%3Aneuecc)&src=typed_query&f=live

---


Is this not good enough?

```csharp
if(popup ! = null) Destroy(popup)
````

It's just a matter of timing.
`this.GetCancellationTokenOnDestroy` will raise when `this` have been destroyed.
For example, if you do `popup.GetCancellationTokenOnDestroy`, that would be a different firing timing.
However, it's better to just check for `! = null`.
