### ISSUE TITLE
Refactor PlayerLoop injection to allow merging with user made injections

### ISSUE THREAD

**Issue by baboongd** [Cysharp/UniTask#187]
Problem is most notable on pre `GetCurrentPlayerLoop` , where we only have `GetDefault` so changes made by unitask can't be easily pulled without passing the newly created playerloop back to user code.
Currently i had to refactor injection on my side so that i could chain it with my systems.
Would be nice to have the api take it into account.

**Comment by neuecc** [comment]
If the story is mostly solved by `GetCurrentPlayerLoop`, I'm not interested.
