### ISSUE TITLE
Any samples?

### ISSUE THREAD

**Issue by JuGGerNaunT** [Cysharp/UniTask#19]
Are there any useful samples for this project? I don't get how to properly use it. I want to use it to load resources
`await Resources.LoadAsync`
but it just blocks main thread.

**Comment by neuecc** [comment]
> it just blocks main thread

UniTask is completely work on single-thread but not block.
Could you show full code(around-method, method signature, and caller signature)?

**Comment by JuGGerNaunT** [comment]
https://gist.github.com/JuGGerNaunT/7e381720ef1bd6694da54c506b86fa89
It turned out that it happens only in the presence of [this](https://gist.github.com/JuGGerNaunT/7e381720ef1bd6694da54c506b86fa89#file-testunirxpart-L17) line.

**Comment by neuecc** [comment]
Thanks,
Your code needs to go here to be asynchronous.
https://gist.github.com/JuGGerNaunT/7e381720ef1bd6694da54c506b86fa89#file-testunirxresource-L68
Please log framecount and time before await and after.

Internaly, await AsyncOperation is called this codes.
https://github.com/Cysharp/UniTask/blob/master/Assets/UniRx.Async/UnityAsyncExtensions.cs#L138-L194

* If `asyncOperation.isDone`, return immediately
* If not, register to `asyncOpeation.completed` https://github.com/Cysharp/UniTask/blob/master/Assets/UniRx.Async/UnityAsyncExtensions.cs#L192

**Comment by JuGGerNaunT** [comment]
I updated gist and made it as simple as possible.
Output:

> Start world update at 2019-06-09 18:29:16.633
> Frame number 1
> Asset 0 pre frame number 1
> Asset 0 post frame number 2
> Asset 1 pre frame number 2
> Asset 1 post frame number 2
> ...
> Asset 49 pre frame number 2
> Asset 49 post frame number 2
> Finish world update at 2019-06-09 18:29:19.765
> Frame number 2
> Frame count 1
> Object count 50

> If asyncOperation.isDone, return immediately
It means that isDone always return true? But why?

**Comment by neuecc** [comment]
I've made simple code(maybe same as your codes).
https://gist.github.com/neuecc/440f79de22d29dd3ea51714c60333acf
and this is the result.

![image](https://user-images.githubusercontent.com/46207/59170397-60a15400-8b79-11e9-9efb-683b3d1f4ba9.png)

This is works we expected.
This Unity version is `2019.3.0a2`.

FYI, `Resource.LoadAsync` sometimes run strange behaviour.
https://answers.unity.com/questions/1555290/resourcesloadasync-seems-to-load-more-than-the-req.html

**Comment by JuGGerNaunT** [comment]
As I mentioned earlier key thing to reproduce this issue are these lines
https://gist.github.com/JuGGerNaunT/7e381720ef1bd6694da54c506b86fa89#file-testunirxmanager-L16
https://gist.github.com/JuGGerNaunT/7e381720ef1bd6694da54c506b86fa89#file-testunirxpart-L14
If I comment out these lines, then async works as expected.

**Comment by neuecc** [comment]
I don't know what file exists in `ResourceDatabase`.
Maybe UnityEditor caches some files when call `LoadWorld`, `LoadGeometry`.
so `LoadAsync` return immediately(beacuse return from cached file so it is `sync`).

**Comment by JuGGerNaunT** [comment]
No. In real project it loads unique assets and the issue is still present.

**Comment by neuecc** [comment]
so I've pointed link that said load multiple files  -> https://answers.unity.com/questions/1555290/resourcesloadasync-seems-to-load-more-than-the-req.html

I don't know Unity engines details(it is not open source code).
For example, if in engine, resource is packed as some chunk,
and loads as chunk, use pointed single(unique) file but loaded multiple.
This is just a hypothetical situation.

Anyway, this is about UnityEngine, not UniTask.
I don't investigate anymore.
