### ISSUE TITLE
Is it sensible to poll UniTasks every frame if I can't use async/await?

### ISSUE THREAD

**Issue by JesseTG** [Cysharp/UniTask#190]
My core game loop within Unity is synchronous. Here's a simplified version:

```csharp
using UnityEngine;

internal sealed class EntryPoint : MonoBehaviour
{
    private Systems systems; // All game logic is represented here

    private void Start()
    {
        systems.Initialize()
    }

    private void Update()
    {
        systems.Execute();
        systems.Cleanup();
    }

    private void OnDestroy()
    {
        systems.TearDown();
    }
}
```

Since the game loop is synchronous I can't use `async` or `await` within it, and it's built atop [a third-party ECS framework](https://github.com/sschmid/Entitas-CSharp) (not [Unity's](https://docs.unity3d.com/Packages/com.unity.entities@0.16)) that can't easily be adapted to be asynchronous. _Note that this framework doesn't modify the [`PlayerLoop`](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/LowLevel.PlayerLoop.html), so [UniTask's](https://github.com/Cysharp/UniTask#playerloop) is still in effect._

But I still need to rely on a wide variety of asynchronous operations, and UniTask is a good way to abstract away their differences. There are some operations I can abstract away into platform-agnostic asynchronous services, too.

The best thing I could think of would be to do the following, in order:

1. Assign each active `UniTask` to an entity
2. Each frame, poll each `UniTask` through its owning entity
3. Set a component on the entity representing the `UniTask`'s status
4. Execute any game logic based on the status of certain `UniTasks` (e.g. loading screens, level transitions, applying loaded data, etc.)
5. At the end of each frame, destroy every entity that owns a completed `UniTask`.

Here's a simplified version of what that looks like:

```csharp
using System.Collections.Generic;
using Entitas;
using UnityEngine;


internal sealed class MonitorTaskSystem : IInitializeSystem, IExecuteSystem
{
    private IGroup<EngineInputEntity> _tasks;

    public void Initialize()
    {
        _tasks = Contexts.engineInput.GetGroup(
            EngineInputMatcher.AllOf(
                EngineInputMatcher.Task,
                EngineInputMatcher.TaskStatus
            )
        );
    }

    public void Execute()
    {
        foreach (var e in _tasks.GetEntities())
        {
            e.ReplaceTaskStatus(e.task.task.Status);
            // All entities representing non-Pending UniTasks are destroyed at the end of the frame
        }
    }
}
```

**Is this a sensible approach for using UniTask?** Are there any downsides, opportunities, techniques, or features that I'm not aware of that would improve (or eliminate the need for) this approach?

**Comment by neuecc** [comment]
I'm not interested in Entitas-CSharp, and as long as I don't see UniTask in your code examples, I can't comment on anything.
However, you shouldn't deal with Status directly.

**Comment by JesseTG** [comment]
Okay, forget Entitas. That detail isn't actually as important as I thought it might be. Let me show you a more general version of what I'm doing.

```csharp
using UnityEngine;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;

internal sealed class EntryPoint : MonoBehaviour
{
    // There are actually a variety of return types in my real code, but this is for illustrative purposes.
    private List<UniTask<object>> runningTasks;
    private List<UniTask<object>> finishedTasks;


    // This method *can* be async, but the other constraints I face means there's no reason for it to be.
    private void Start()
    {
        runningTasks= new List<UniTask<object>>();
        finishedTasks = new List<UniTask<object>>();
    }

    // This method *can* be async, but the other constraints I face means there's no reason for it to be.
    private void Update()
    {
        finishedTasks.Clear();
        runningTasks.AddRange(GetNewTasks());
        foreach (var t in runningTasks)
        {
            if (t.Status == UniTaskStatus.Succeeded)
            {
                finishedTasks.Add(t);
            }
        }
        runningTasks.RemoveAll(finishedTasks);

        ProcessFinishedTasks(finishedTasks);
    }

    // Returns whatever new asynchronous tasks we started this frame, or an empty sequence if none.
    // This isn't allowed to be async because it uses a lot of third-party code that isn't async.
    private IEnumerable<UniTask<object>> GetNewTasks() => /* something */;

    // Looks at each finished task and processes their results. If the enumerable is empty, do nothing.
    // This isn't allowed to be async because it uses a lot of third-party code that isn't async.
    private void ProcessFinishedTasks(IEnumerable<UniTask<object>> tasks) => /* something */;
}
```

This is a good enough analogy to what I'm doing in my real code. **Is there anything wrong with this?**

**Comment by neuecc** [comment]
Most UniTasks are managed by Pools.
Manually controlling it will take out the incorrect state.

It's not impossible if you know perfectly well when UniTask will be returned to Pool, and the user has complete control over it, but you shouldn't.

**Comment by JesseTG** [comment]
Okay, so it sounds like polling is a bad idea unless I know exactly what I'm doing. I have another idea, but I'll try it out first and then I'll ask for your opinion in another thread. Thank you!
