### ISSUE TITLE
UniTask.Yield returns object to unity main thread.

### ISSUE THREAD

**Issue by mdsitton** [Cysharp/UniTask#191]
I've found one issue so far, after scheduling a UniTask to run on the ThreadPool doing UniTask.Yield the task returns to the unity main thread. Any chance there would be a more convenient way of handing this so that we don't need to do:

```
            await UniTask.Yield();
            await UniTask.SwitchToThreadPool();
```

Each time?

Thanks

**Comment by neuecc** [comment]
That operation is independent, and I don't think it's an operation most people use.
If you have to do so, write it each time.
