### ISSUE TITLE
About "Await UnityWebRequest.SendWebRequest" 

### ISSUE THREAD

**Issue by Personuo** [Cysharp/UniTask#192]
When using wait UnityWebRequest.SendWebRequest to wait for a network request,
Then UnityWebRequest reports an error (e.g. 404, or can't find the host)
But,the program is stuck here.

Is this behavior expected?

``` 
        UnityWebRequest request = new UnityWebRequest("some error web url");
        await request.SendWebRequest();//the program is stuck here when request get a error
        
```

And here's how I solved it. 

```
        UnityWebRequest request = new UnityWebRequest("some error web url");
        request.SendWebRequest()
        await UniTask.WaitUntil(()=> request .isDone);
```
But I still want to make sure.

**Comment by neuecc** [comment]
I've tested your first sample, it throws UnityWebRequestException.
`UnityWebRequestException: HTTP/1.1 404 Not Found`
