### ISSUE TITLE
Awaiting multiple DOTween Tasks in a single statement

### ISSUE THREAD

**Issue by SharkWithLasers** [Cysharp/UniTask#193]
Hi there!

I have experienced an error when trying to await multiple DOTween tasks in the same statement.
`await (task1, task2)` doesn't compile and neither does `await UniTask.WhenAll(task1, task2)`.

```
public async UniTask DoTweenTest()
{
    var task1 = transform.DOScale(2, 1f);
    var task2 = transform.DORotate(Vector3.one, 1f);

    // Doesn't compile
    await (task1, task2);

    // Doesn't compile
    await UniTask.WhenAll(task1, task2);

    // Compiles
    await task1;
    await task2;
}
```

I'm on Unity 2019.4.11f1 and UniTask 2.0.36.

Thank you for your time! And thank you for the great library!

**Comment by SharkWithLasers** [comment]
Experimented a bit more.

If I add `.WithCancellationToken(...)` to the end of the `DOScale` and `DORotate` calls, then `await (task1, task2)` and `await UniTask.WhenAll(task1, task2)` work fine.

**Comment by neuecc** [comment]
task1 itself is not UniTask(DoTween's TweenCore).
so you should convert TweenCore to UniTask by `WithCancellation` or `ToUniTask`.
