### ISSUE TITLE
UniTask performance issues

### ISSUE THREAD

**Issue by mahgo** [Cysharp/UniTask#195]
UniTask appears to be having some performance issues to me. Here is a screenshot of the Unity Profiler, of my game running on Android, even when nothing is currently being awaited. Should it be using this much CPU? I'm using Unity 2019.4.0f1

![image](https://user-images.githubusercontent.com/4499646/98313079-29adc700-2027-11eb-9f1f-6c76e8a1782a.png)

**Comment by neuecc** [comment]
Is it in PlayerLoop?
all await codes run on PlayerLoop so it is your application code.
check deep profile.

**Comment by mahgo** [comment]
Yes this is deep profiled. Here's a closer view on some of it.
![image](https://user-images.githubusercontent.com/4499646/98315682-dc345880-202c-11eb-82ff-598425c31386.png)

According to the profiler, it is in PlayerLoop, yes.

**Comment by neuecc** [comment]
PlayerLoop 33ms

LastYield 0.21ms
Last 0.08ms
YieldFixed 0.2ms

There are not costful (also, it comes out thicker in the deep profile due to the spinlock hierarchy, but it won't really cost that much)
Therefore, I don't think the depth of the hierarchy is an issue.
Show me the details of the 33ms (the loop that takes the most time).

**Comment by mahgo** [comment]
I went through and added up the rest and it added up to 3.12ms, which when the total frame (excluding WaitForTargetFPS) comes to 15ms, is quite a lot. 33ms is the whole frame including WaitForTargetFPS. What did you want me to show you in that?

**Comment by neuecc** [comment]
There's nothing in particular I'd like to see, but it's hard to see anything in the image you're specifying.

**Comment by mahgo** [comment]
https://drive.google.com/file/d/1DZS48-k0W1xEWol3nsf706rT8t5qse19/view?usp=sharing

I exported the profile data, you are able to load this into your profiler.

**Comment by neuecc** [comment]
Thank you.
Each one is small, but UniTask has 28 Injects to PlayerLoop, so if it took, say, 0.5ms, it would take 28 * 0.5ms = 14ms.
To begin with, these processes should be mostly 0.0ms to be lightweight, but the
Apparently, SpinLock is behaving in an unintended way and eating up a lot of performance.

I'm going to try to get rid of SpinLock now.

**Comment by mahgo** [comment]
Thanks for looking into this for me!

**Comment by neuecc** [comment]
I've released `2.0.37`, it still exists SpinLock but fix incorrect usage of SpinLock.
I think it's an improvement, but please let me know if you still have problems.

**Comment by mahgo** [comment]
I just updated to 2.0.37 and checked it out again, I'm getting approximately 4.13ms taken by UniTask in a frame now, which is more than before.

https://drive.google.com/file/d/1YmyZNaf03818eBUWbU6KFb13YfNOm-Fy/view?usp=sharing

**Comment by neuecc** [comment]
Thanks, improvment of SpinLock works fine.

![image](https://user-images.githubusercontent.com/46207/98618171-f3808800-2343-11eb-9550-bd0434f49d6c.png)

UniTask's empty PlayerLoop's totaly cost is 0.4ms.

most costed tree is only do `lock(obj) { }`.

![image](https://user-images.githubusercontent.com/46207/98618431-8f11f880-2344-11eb-9ee4-7676bfd6c9a0.png)

It is affected by Deep Profiling.

In other words, I don't think it's a UniTask issue.

**Comment by mahgo** [comment]
Ok thanks, I didn't think that deep profiling could affect this. I'll keep an eye on it.

**Comment by neuecc** [comment]
Your Profiling Data was very helpful.
Also, thanks to you, I was able to find a problem with SpinLock.
Thank you very much.

**Comment by mahgo** [comment]
No worries

**Comment by neuecc** [comment]
v2.2.0 implements remove unuse PlayerLoop injection.

```
var loop = PlayerLoop.GetCurrentPlayerLoop();
PlayerLoopHelper.Initialize(ref loop, InjectPlayerLoopTimings.Minimum); // minimum is Update | FixedUpdate | LastPostLateUpdate
```
