### ISSUE TITLE
i meet a error in editor mode.

### ISSUE THREAD

**Issue by woshihuo12** [Cysharp/UniTask#197]
[11:23:24-204][1][Exception] : Detected invalid initialization(use 'default'), only to create from StartNew(). 
   at Cysharp.Threading.Tasks.Internal.ValueStopwatch.get_ElapsedTicks () [0x00010] in D:\work\android\ohayoo_whitebird_project4\project4\client\Assets\Plugins\UniTask\Runtime\Internal\ValueStopwatch.cs:27 
  at Cysharp.Threading.Tasks.UniTask+DelayRealtimePromise.MoveNext () [0x00027] in D:\work\android\ohayoo_whitebird_project4\project4\client\Assets\Plugins\UniTask\Runtime\UniTask.Delay.cs:729 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00067] in D:\work\android\ohayoo_whitebird_project4\project4\client\Assets\Plugins\UniTask\Runtime\Internal\PlayerLoopRunner.cs:163 
UnityEngine.Debug:LogError(Object)
Debug:DoLog(LogLevel, String)
Debug:LogInternalFormat(LogLevel, String, Object[])
Debug:LogException(String, Exception)
Debug:LogException(Exception)
Cysharp.Threading.Tasks.Internal.<>c:<.ctor>b__9_0(Exception) (at Assets/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:25)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore() (at Assets/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:177)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update() (at Assets/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:137)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run() (at Assets/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:104)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)

so why has this error?
very thanks...

**Comment by woshihuo12** [comment]
i use like this:  await UniTask.Delay(1500, DelayType.Realtime).SuppressCancellationThrow();

**Comment by woshihuo12** [comment]
in UniTask.Delay.cs

UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)

i change code like this( realtime promise):

           bool TryReturn()
            {
                TaskTracker.RemoveTracking(this);
                core.Reset();
                stopwatch = ValueStopwatch.StartNew();  ------------ this...
                cancellationToken = default;
                return pool.TryPush(this);
            }

**Comment by neuecc** [comment]
please provide reproduce code.

**Comment by woshihuo12** [comment]
using System;
using Cysharp.Threading.Tasks;
using UnityEditor;
using UnityEngine;

public class Test1
{
    [MenuItem("Test/Test1")]
    public static async UniTaskVoid TestFunc()
    {
        await DoSomeThing();
        string[] scenes = new string[]
        {
            "Assets/Scenes/SampleScene.unity",
        };

        try
        {
            BuildPipeline.BuildPlayer(scenes, Application.dataPath + "../target", BuildTarget.iOS, BuildOptions.CompressWithLz4);
        }
        catch (Exception e)
        {
            Debug.LogError(e.Message);
        }
    }

    public static async UniTask DoSomeThing()
    {
        Debug.Log("Dosomething");
        await UniTask.Delay(1500, DelayType.Realtime).SuppressCancellationThrow();
        Debug.Log("Dosomething 2");
        await UniTask.Delay(1000, DelayType.Realtime).SuppressCancellationThrow();
        Debug.Log("Dosomething 3");
    }
}


new a project and put above script in editor folder, then run test/test1 menu, in unity2018.4.28, you will meet an error.

**Comment by woshihuo12** [comment]
can i have some help?

**Comment by neuecc** [comment]
I can't understand why this happens but actually reproduced.
I've added a fix to stop Delay when ValueStopwatch is in an invalid state.
This will probably work correctly.
This fix will be included in the next release.
