### ISSUE TITLE
How to stop all UniTask, UniTask<T> immediately when Unity Editor exit playmode ?

### ISSUE THREAD

**Issue by HyVong007** [Cysharp/UniTask#199]
I always met problem when Editor exit playmode but some tasks are running after that time and cause the scene objects to change unexpected. I want to stop all tasks IMMEDIATELY when exiting playmode !

**Comment by nikolayinnerspace** [comment]
I'm also interesting in this question. and from the same side another one
How to stop all tasks on scene reload (the same way as courutines are running only while object is active is it possible to run task  which are active only within parent scene)

**Comment by neuecc** [comment]
use CancellationToken.
