### ISSUE TITLE
ConfigureAwait does not accept progress callback

### ISSUE THREAD

**Issue by renatoi** [Cysharp/UniTask#20]
README.md says:

```
// .ConfigureAwait accepts progress callback
await SceneManager.LoadSceneAsync("scene2").ConfigureAwait(Progress.Create<float>(x => Debug.Log(x)));
```

I tried the following:

```
await UniTask.Delay(TimeSpan.FromSeconds(10)).ConfigureAwait(Progress.Create<float>(x => Debug.Log(x)));
```

It doesn't work. It says that `.ConfigureAwait` expects a `PlayerLoopTiming`.

**Comment by neuecc** [comment]
Eash `ConfigureAwait` is anothrer things.
`AsyncOperation.ConfigureAwait` reports `asyncOperation.progress` per frame.
But Delay(`UniTask<float>`)  has no progress port.
