### ISSUE TITLE
Preserve() does not guarantee await twice on non completed state

### ISSUE THREAD

**Issue by piti6** [Cysharp/UniTask#206]
Subject:
``` csharp
private void Start()
{
    var task = UniTask.Create(Hoge).Preserve();

    task.Forget();
    task.Forget();
    // or something like await UniTask.WhenAll(task, task), await once again before 1000ms exceeds 
}
        
private async UniTask Hoge()
{
    await UniTask.Delay(1000);
    UnityEngine.Debug.Log("Hoge");
}
```

Expected result(on my sight): "Hoge" should be printed in Unity console
Actual result: throws InvalidOperationException("Already continuation registered, can not await twice or get Status after await");

Is this for design? afaik, UniTask v1 constructor with function<UniTask> was fine with above usage.
Actual situation: await formerly sent UniWebRequest when there is one, etc..

**Comment by neuecc** [comment]
This is a hard to understand behavior and may change, but it is currently a specification.
Use `UniTask.Lazy` instead.
Details are in the last section below.
https://github.com/Cysharp/UniTask#basics-of-unitask-and-asyncoperation
