### ISSUE TITLE
Combining IProgress

### ISSUE THREAD

**Issue by slimshader** [Cysharp/UniTask#207]
Hi,

problem: I want to implement async function that calls 2 other async functions that take IProgress as paramaters, how to combine resulting progress?

```csharp
private async UniTask BingFunction(IProgress<float> progress)
{
   var combinedProgress = ??
   await SmallFunction1(combinedProgress);
   await SmallFunction2(combinedProgress);
}
```

First thing that comes to mind is to create new Progress that reports half of the value reported by SmallFunctionX (or third of value in case of 3 SmallFunctions etc.) but maybe there is easier way?

**Comment by neuecc** [comment]
IProgress is a simple implementation.
As per your idea, if you need individual control, please create a wrapper for IProgress to do that operation.
