### ISSUE TITLE
How to continue execution of an `async` method synchronously if a UniTask has already been completed?

### ISSUE THREAD

**Issue by JesseTG** [Cysharp/UniTask#209]
I'm using `UniTask` with Addressables to load assets. I can load an addressable asset with `async`/`await` like this:

```csharp
private async UniTaskVoid LoadAssetAsync(AssetReference reference)
{
    ValidateReference(reference); // synchronous
    var asset = await reference.LoadAssetAsync<Object>();
    ProcessAsset(asset); // asynchronous, but I'd like it to be synchronous if the asset was already loaded
}
```

Unless I'm mistaken, `ProcessAsset` will be called at least one frame after `ValidateReference` due to the `await`. This is expected if I'm loading `reference` for the first time. However, sometimes (but not always!) the asset referred to by `reference` has already been loaded and is ready to use. In that case, I would like to continue execution within the same frame. **How can I do that?**

**Comment by neuecc** [comment]
If LoadAssetAsync(`AsyncOperationHandle<T>`) already completed, returns synchronously.
https://github.com/Cysharp/UniTask/blob/908e3619/src/UniTask/Assets/Plugins/UniTask/Runtime/External/Addressables/AddressablesAsyncExtensions.cs#L255
