### ISSUE TITLE
Pending tasks count increases

### ISSUE THREAD

**Issue by slimshader** [Cysharp/UniTask#21]
I have a method that awaits for other GOs trigger enter like so
```
var collisionTrigger = bullet.gameObject.GetAsyncCollision2DTrigger();
var hit1 = await collisionTrigger.OnCollisionEnter2DAsync();
```
this method is awaited and eventually flow is returned to the caller, but in theUniTask Tracker that every time this code is called, a new Pending task is created at the "await" line.

**Comment by neuecc** [comment]
Could you provide tracker's screenshot?
I don't understand what you mean.

AsyncTriggerPromise is cache and reuse in AsyncCollision2DTrigger components.
