### ISSUE TITLE
UniTask cancellation doesn't work

### ISSUE THREAD

**Issue by janissimsons** [Cysharp/UniTask#211]
I am trying to cancel a running task on keyboard input, so if the task is running and the same key is pressed again, the task should cancel and start from the beginning.

I created a private property to store the async task:
```csharp
    private CancellationTokenSource cancellationTokenSource;
    private UniTask activeTask;
    private int cancelCount = 0;
```

Then I am checking if the task is not already running, if it is then, it should be cancelled:
```csharp
        if (activeTask.Status == UniTaskStatus.Pending)
        {
            cancellationTokenSource.Cancel();
            ++cancelCount;
            await activeTask.SuppressCancellationThrow();
            --cancelCount;
            if (cancelCount > 0)
            {
                return -1;
            }
        }
```
If the task isn't running, then I create a new cancellation token and start the async task:

```csharp
        cancellationTokenSource = new CancellationTokenSource();

        activeTask = Animate(radialActions);

        bool isCancelled = await activeTask.SuppressCancellationThrow();
        if (isCancelled)
        {
            return -1;
        }
        return 1;
```

However, this doesn't work at all. 
When I am debugging it, the UniTaskStatus is ALWAYS == "Succeeded". Even when I stepped into the async method execution, it never changed to "Pending". 
I don't understand why.

Any help would be greatly appreciated.

**Comment by GainDeveloper** [comment]
Yeah I'm not sure activeTask.Status is doing what you expect.
I'd recommend always calling cancellationTokenSource.Cancel(); regardless of the status. Are you handling the OperationCanceledException in the task? For example:

`async UniTaskVoid AsyncMoveInDir(int dir)
{
	if (delayedCallCancellationSource != null)
		delayedCallCancellationSource.Cancel();
	delayedCallCancellationSource = new CancellationTokenSource();

	try
	{
		await UniTask.Delay(delayMilliseconds, true, cancellationToken: delayedCallCancellationSource.Token);
	}
	catch (OperationCanceledException)
	{
		return;
	}

	// Task finishes successfully.
}`

**Comment by neuecc** [comment]
If `ALWAYS == "Succeeded"`, then the problem is in the body of the activeTask,
but your sample code doesn't show that, so I'm not sure.
