### ISSUE TITLE
await UniTask.SwitchToMainThread(); not working on Android

### ISSUE THREAD

**Issue by xabio** [Cysharp/UniTask#212]
I have a MonoBehaviour `GameServerManager` that is injected on every scene of my game
`Container.Bind<GameServerManager>().FromNewComponentOnNewGameObject().AsSingle();`

It contains a SingnalR Client which is listening to events from the server
I have declared, inside `GameServerManager` a list of listeners which are of tipe UnitTask
```C#
private List<GameServerDelegate> GameEventsHandler { get;  set; } = new List<GameServerDelegate>();
public delegate UniTask GameServerDelegate(object sender, GameServerEventArgs e);
```
So, they are called when some events ocurrs in SignalR client, for example, when all users are online it notifies all registered `GameServerDelegate` :
```C#
 _connection.On<string>("allConnected", async (idGame) =>
  {          
       if (GameEventsHandler != null)
           await NotifyEventHandlers( GameServerEventArgs.CreateAllConnected(idGame));
   }    

 public async UniTask NotifyEventHandlers(GameServerEventArgs @event)
        {
            await UniTask.SwitchToMainThread();
            foreach (var eventHandler in GameEventsHandler)
            {
                if (eventHandler != null)
                    await eventHandler(this, @event);
                else
                    UnRegisterFromEvents(eventHandler);
            }
        }
```

An example of a GameServerDelegate is:

```C#
    private async UniTask _gameServerManager_GameEventsHandler(object sender, GameServerEventArgs e)
    {
        await UniTask.SwitchToMainThread(); // this is not working, it does not update UI, only in Editor 
        Debug.Log("UniTask.SwitchToMainThread()");
        if (e.TypeOfEvent == GameServerEventArgs.GameServerEventType.Connected)
        {
            Debug.Log("GameManager.Connected");
            await connected();//it does UI changes, like setting text, textures, etc
        }
  }
```

It works perfectly on editor , but on Android real device, code is not running on UI.
Why?

**Comment by neuecc** [comment]
That's inexplicable, please check `Thread.CurrentThread.ManagedThreadId` and `PlayerLoopHelper.MainThreadId`.
Also, what if we use `await UniTask.Yield()` instead of `SwitchToMainThread`?

**Comment by RamType0** [comment]
> please check `Thread.CurrentThread.ManagedThreadId` and `PlayerLoopHelper.MainThreadId`.

Topic: We have `PlayerLoopHelper.IsMainThread`

**Comment by xabio** [comment]
It was a mistake in code, sorry guys
