### ISSUE TITLE
Usage question : webtexture processing in external library on background thread

### ISSUE THREAD

**Issue by TheBricktop** [Cysharp/UniTask#213]
Hello, 
big thanks for this amazing library.
Im currently close to understanding how to use unitask for async await on main thread but struggling to understand what is possible and how when one wants to use background thread for data processing.

My problem looks like this :
1. webcamtexture goes in to the async function as an input
2. its getting processed where await waits for data
3. Vector3[] gets returned and used on mainthread

The thing is that the thread can safely run constantly, with webcamtexture frames constantly getting processed and vectors outputted. Should I use async/await then?
Secondly im not sure if I can use webcamtexture as an input cause thread are known for not being able to use some of the unity Api. 

currently my code for the async task looks like this : 
(im using code from tf unity samples for mediapipe integration)
   

    public async UniTask<Vector3[]> HandDetectTask()
    {
        await UniTask.SwitchToThreadPool();

        try
        {
            palmDetect.Invoke(webcamTexture);
            var palms = palmDetect.GetResults(0.7f, 0.3f);
            landmarkDetect.Invoke(webcamTexture, palms[0]);
            var landmarkResult = landmarkDetect.GetResult();

            return  ComputeWordJoints(landmarkResult.joints);
        }
        finally
        {
            await UniTask.SwitchToMainThread();
        }
    }

**Comment by RamType0** [comment]
[Are you using this library?](https://github.com/asus4/tf-lite-unity-sample/blob/master/Assets/Samples/HandTracking/PalmDetect.cs)
I'm not familiar with that library,but your code seems to be invalid.

At Invoke method,maybe read or write operation to argument texture performed,and your code doing it from non-main thread.
It is not allowed.

I recommend you to do

1.Do read by AsyncGPUReadback to retrieve data from texture asynchronously 
2.Switch to thread pool
3.Do TensorFlow compute on thread pool
(4. Maybe you need to switch to main thread)

But I'm really not familiar with TensorFlow.TensorFlow itself may not be thread-safe.

**Comment by TheBricktop** [comment]
Yes, thats the one, the author claims that he improved performance on some style transfer example by pushing some computations on the background thread.
Now ive improved my code that it actually works but the performance improvemenet is almost none. As You've pointed out there is a need to rewrite the library to separate the gpu ops, texture reading  and the tf math to safely put the latter on background thread.
On the other hand, how to use async/await properly  with the "for" loop ? Unitask is capable of speeding up some long "for" computations ?

**Comment by RamType0** [comment]
I don't know something which is specific for "for" loop.
Can you describe me detail?

**Comment by TheBricktop** [comment]
I mean for example :
for loop (or foreach), is known for stealing fps if the for is branched and has a lot of iterations, so if there was a way to yield execution of the "for" (without using delay) 

like this :

    async UniTask<int> SpawnEnemies()
    {
	    // wait until there are less than 5 enemies
	    await UniTask.WaitUntil(() => this.activeEnemies < 5);
    
	    int enemiesToSpawn = 5 - this.activeEnemies;
    
	    for (int i = 0; i < enemiesToSpawn; ++i)
	    {
		    Debug.Log(string.Format("spawn enemy {0}", i));
    
		    ++this.activeEnemies;
    
		    // wait for 500 ms before continuing for loop
		    await UniTask.Delay(500);
	    }
    
	    // return the count of enemies spawned
	    return enemiesToSpawn;
    }


so the pseudocode should look like this (if im correct)

    async UniTask<int> SpawnEnemies()
    {
	    // wait until there are less than 5 enemies
	    await UniTask.WaitUntil(() => this.activeEnemies < 5);
    
	    int enemiesToSpawn = 5 - this.activeEnemies;
    
	  // here should be the code where for loop is asynchronously executed
    
	    // return the count of enemies spawned
	    return enemiesToSpawn;
    }

**Comment by RamType0** [comment]
Just call await UniTask.SwitchToThreadPool or await UniTask.SwitchToMainThread to switch threads anywhere in async method.
Including inner "for" loop.

**Comment by TheBricktop** [comment]
Seems very intutitive ill check this out.

**Comment by RamType0** [comment]
This kind of behavior is not a specific for UniTask.

Any kind of compiler generated state machine pattern(yield iterator,async Task,async IAsyncEnumerable) always behave consistently.
