### ISSUE TITLE
Unity 2020.2 で、await UniTask.Yield(PlayerLoopTiming.PostLateUpdate) が正しく機能しない

### ISSUE THREAD

**Issue by Gigacee** [Cysharp/UniTask#214]
Unity 2020.2 にて、以下のようなコードがエラーになります。

```cs
async UniTaskVoid Start()
{
    await UniTask.Yield(PlayerLoopTiming.PostLateUpdate);

    var texture = ScreenCapture.CaptureScreenshotAsTexture();
}
```

Unity 2019.4、Unity 2020.1 で確認したところ、エラーは発生しませんでした。

**Comment by neuecc** [comment]
再現しなかったのですが、どんなエラー内容でした？

**Comment by Gigacee** [comment]
すみません、エラーメッセージを忘れていました。以下になります。

```
CaptureScreenshot(L:0, B:0, W:1920, H:1080) requested a region that exceeds the active Render Target sized [W:1124, H:603].
```

```
CaptureScreenshotAsTexture() failed to generate texture! Was method called before the 'end of frame' state was reached?
UnityEngine.ScreenCapture:CaptureScreenshotAsTexture ()
CaptureScreenshot/<Start>d__0:MoveNext () (at Assets/CaptureScreenshot.cs:10)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1<CaptureScreenshot/<Start>d__0>:Run () (at Library/PackageCache/com.cysharp.unitask@52cdadc035/Runtime/CompilerServices/StateMachineRunner.cs:104)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore () (at Library/PackageCache/com.cysharp.unitask@52cdadc035/Runtime/Internal/ContinuationQueue.cs:194)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:PostLateUpdate () (at Library/PackageCache/com.cysharp.unitask@52cdadc035/Runtime/Internal/ContinuationQueue.cs:163)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run () (at Library/PackageCache/com.cysharp.unitask@52cdadc035/Runtime/Internal/ContinuationQueue.cs:130)
```

**Comment by neuecc** [comment]
なるほど！
親切なエラーメッセージになったということでいいんじゃないかと思います。
PostLateUpdateは `end of frame` じゃないので、テクスチャ作れないよーってことなんじゃないかと。
現状は普通にコルーチンで `yield return new WaitForEndOfFrame` するしか手がないんじゃないかと思ってます。

**Comment by Gigacee** [comment]
そうなのですね。Unity 2020.1 以前ではエラーが発生しなかったのがちょっと気になりますが……。
いくつかの記事で、「`await UniTask.Yield(PlayerLoopTiming.PostLateUpdate);` で `WaitForEndOfFrame` を置き換えられる」という記述を見たのですが、そういうわけではないということなのでしょうか？

**Comment by neuecc** [comment]
PostLateUpdate のあと、UniTaskのPlayerLoopの更に外側でWaitForEndOfFrameが動くというイメージになり、
現状それを置き換える手段がありません。

以前から(2020.1でも)取れなかった or 取れたり取れなかったりだったのが、
完全に取れないという方向に倒してUnityが分かりやすいエラーメッセージを出す、という方向に倒しただけだと思うので
2020.2における改善ポイントとして、これ自体は良いことだと思います。

2020.2 ならば、もしかすると `TimeUpdate` で取れる可能性がワンチャンあるかもしれないので試していただけると……！
(フレーム的には次フレームになるのでWaitForEndOfFrameの置き換えにはならないのですが、
Initializeよりも前に走るようなので ScreenShotのCaptureができる可能性があるかもないかも）

**Comment by Gigacee** [comment]
Unity 2020.2 でより厳格になったということなのですね。ありがとうございます。理解できました。

`await UniTask.Yield(PlayerLoopTiming.TimeUpdate)` で試してみましたが、やはりエラーが発生してしまいました。
素直に `yield return new WaitForEndOfFrame` を使うしかないようです。

**Comment by neuecc** [comment]
ダメでしたかー、しょうがない！
了解ました……！
真のWaitForEndOfFrame相当をいつかUnityが開放してくれることを願って。。。
