### ISSUE TITLE
Useage Question : Awaiting AsyncOperationHandle<SceneInstance>

### ISSUE THREAD

**Issue by nindim** [Cysharp/UniTask#219]
Hi,

I have created a static helper class with a function that uses Addressable to load a scene and return the AsyncOperationHandle<SceneInstance> for later use. The AsyncOperationHandle<SceneInstance> is is not intended to be awaited, it is just used to call Addressables.UnloadSceneAsync() later on.

I am having an issue awaiting the AsyncOperationHandle<SceneInstance> where i recive this message:

"yield SceneInstance is not supported on await IEnumerator or IEnumerator.ToUniTask(), please use ToUniTask(MonoBehaviour coroutineRunner) instead."

I don't have a MonoBehaviour instance to use with ToUniTask(MonoBehaviour coroutineRunner) or actually understand why it is necessary.

Any help on how best to structure this would be really appreciated, thank you!

```csharp
    public static async UniTask<AsyncOperationHandle<SceneInstance>> LoadSceneAsync(object key, LoadSceneMode loadMode = LoadSceneMode.Single, bool activateOnLoad = true, int priority = 100)
    {
        var asyncOphandle = Addressables.LoadSceneAsync(key, loadMode, activateOnLoad, priority);
        
        // These commented out lines cause: "yield SceneInstance is not supported on await IEnumerator or IEnumerator.ToUniTask(), please use ToUniTask(MonoBehaviour coroutineRunner) instead."
        //await asyncOphandle;
        //await asyncOphandle.ToUniTask();

        // I can't do this as I don't have a MonoBehaviour to pass in
        //await asyncOphandle.ToUniTask(this);
        
        // This works, but is very inefficient as its using Unity's implementation
        // await asyncOphandle.Task;
        
        // This is what I have settled on for now, is there a better way?
        while (!asyncOphandle.IsDone)
            await UniTask.Yield();
        
        return asyncOphandle;
    }
```

**Comment by neuecc** [comment]
please write

```
asyncOphandle.GetAwaiter();
```

and F12  on GetAwaiter via your Editor.
If the jump destination is this code, it should work correctly.
https://github.com/Cysharp/UniTask/blob/7d21a75e/src/UniTask/Assets/Plugins/UniTask/Runtime/External/Addressables/AddressablesAsyncExtensions.cs#L230

Please check to see which code you jumped to.

**Comment by nindim** [comment]
Thanks for the quick reply.

It is jumping to:

https://github.com/Cysharp/UniTask/blob/7d21a75ea8abbc3ed43afedeb450c8d44f244ece/src/UniTask/Assets/Plugins/UniTask/Runtime/EnumeratorAsyncExtensions.cs#L15

All the best

**Comment by neuecc** [comment]
Indeed, `AsyncOperationHandle<TObject> : IEnumerator` may execute its extension method.
But if `UniTask.Addressables` is enabled, AddressableAsyncExtensions has priority.
Maybe this method is defined in another `asmdef` and there is no reference to `UniTask.Addressables`?
Add `UniTask.Addressables` as a reference.

**Comment by nindim** [comment]
Hi,

Do you mean I need to add UNITASK_ADDRESSABLE_SUPPORT to my project settings' Scripting Define Symbols? I am on Unity 2018.4 so do not have access to the new Assembly Definition Version defines https://blogs.unity3d.com/2019/04/16/introducing-unity-2019-1/#assembly

Thank you.

**Comment by neuecc** [comment]
If code is grayed out, yes.
