### ISSUE TITLE
Func<T>  =>  UniTask<T>

### ISSUE THREAD

**Issue by ToddGitHub** [Cysharp/UniTask#221]
原来是有返回值的委托Func<T> 怎么改为UniTask<T>

**Comment by neuecc** [comment]
UniTask.Lazy(func)

**Comment by ToddGitHub** [comment]
我想是把原来注入某个类的func 替换为异步的 比如 某个类内的 Func<string, Sprite>onGetSprite 
怎么替换为异步获取的

**Comment by ToddGitHub** [comment]
目前 我只能替换为  Func<String, UniTask<Sprite>> onGetSpritAsync;

**Comment by neuecc** [comment]
like this you want to?

```csharp
void GetSprite(Func<Sprite> onGetSprite)
{
    loader.onCompleted = (sprite) => onGetSprite(sprite);
}

// to

UniTask<Sprite> GetSpriteAsync();
```

In this case, you can use UniTaskCompletionSource.

```csharp
UniTask<Sprite> GetSpriteAsync()
{
    var cs = new UniTaskCompletionSource<Sprite>();
    loader.onCompleted = (sprite) => cs.TrySetResult(sprite);
    return cs.Task;
}
```

**Comment by ToddGitHub** [comment]
public class A
{
    public Func<string, Sprite> onGetSprite;

    public void Run()
    {
        Sprite sprite = null;
        if (onGetSprite != null)
        {
            sprite = onGetSprite("id");
        }
    }
    public void Init()
    {
        this.onGetSprite =C. OnGetSprite;
    }

}
public class B
{
    public Func<string, UniTask<Sprite>> onGetSprite;

    public async void Run()
    {
        Sprite sprite = null;
        if (onGetSprite != null)
        {
            sprite = await onGetSprite("id");
        }
    }
    public void Init()
    {
        this.onGetSprite = C.GetSpriteByID;
    }

    private Sprite OnGetSprite(string arg)
    {
        return null;
    }
}
public class C
{
    public  static async UniTask<Sprite> GetSpriteByID(String id)
    {
        await UniTask.Yield();
        return null;
    }
    public static Sprite OnGetSprite(string arg)
    {
        return null;
    }
}

**Comment by neuecc** [comment]
I'm sorry, I'm not quite sure, but I think I've given you an idea of the method, so think about it.
