### ISSUE TITLE
UniTask fails to compile when Physics or Physics2D module is disabled

### ISSUE THREAD

**Issue by Razenpok** [Cysharp/UniTask#222]
As per title, you can disable built-in Unity modules which causes errors during compilation.

![image](https://user-images.githubusercontent.com/8434406/106149667-95698100-618b-11eb-8815-ee7f1f385b5d.png)

**Comment by RamType0** [comment]
I made PR which will fix this, but this issue also present for many other packages(Include unity official packages).
So you will continue to have headache for this issue even if it merged.

**Comment by neuecc** [comment]
I disagree with adding it to dependencies.

**Comment by Razenpok** [comment]
I agree with @neuecc 

Probably conditional defines would be better
https://docs.unity3d.com/2020.1/Documentation/Manual/ScriptCompilationAssemblyDefinitionFiles.html#define-symbols

**Comment by Razenpok** [comment]
Smth like this
![image](https://user-images.githubusercontent.com/8434406/107006869-d1f83680-67a2-11eb-8d63-8ab8bb16c4ef.png)

**Comment by RamType0** [comment]
> I agree with @neuecc
> 
> Probably conditional defines would be better
> https://docs.unity3d.com/2020.1/Documentation/Manual/ScriptCompilationAssemblyDefinitionFiles.html#define-symbols

Note that conditional defines doesn't work in Unity 2018.4.
![image](https://user-images.githubusercontent.com/39725073/107105907-316e4900-686c-11eb-977f-512f85f2ac53.png)

Manually define all of these symbol in Unity 2018.4 is seems to be troublesome.
Also, I previously tried to solve this kind of issue with conditional defines in #126, but it was not merged.

I have not heard clear answer yet(I just heard that not desirable or disagree).

**Comment by Razenpok** [comment]
This feature can be applied starting from Unity 2019.1

```csharp 
#if UNITY_2019_1_OR_NEWER && UNITASK_PHYSICS_2D
```

This shouldn't be a big deal since Unity 2018.4 will be out of support very soon

https://unity3d.com/unity/qa/lts-releases

> Unity 2018.4 is now the legacy LTS; it will be updated monthly until it reaches the end of its support cycle in spring 2021.

**Comment by RamType0** [comment]
> This shouldn't be a big deal since Unity 2018.4 will be out of support very soon
> 
> https://unity3d.com/unity/qa/lts-releases
> 
> > Unity 2018.4 is now the legacy LTS; it will be updated monthly until it reaches the end of its support cycle in spring 2021.

Personally, I agree with it.

I am ready to make PR with conditional define , but I'm really not sure about what @neuecc disagree and what will he agree.

**Comment by neuecc** [comment]
@Razenpok 
Already UniTask defines `com.unity.modules.assetbundle` -> `UNITASK_ASSETBUNDLE_SUPPORT` so I'll define same way for physics.
I've released `2.1.2`, it defined for Physics, Physics2D, ParticleSystem, uGUI, WebRequest.

**Comment by neuecc** [comment]
@RamType0
#126 is completely different.
It separates dependency, to asmdef.
If you think they are the same thing, then you have a mind problem.
Unfortunately, I'm going to block you from this repository for a while.

**Comment by Razenpok** [comment]
Thanks!
