### ISSUE TITLE
Using UniTask to load assets in tests

### ISSUE THREAD

**Issue by jchown** [Cysharp/UniTask#225]
What's the best way to handle a Task that is loading an asset in a test? I couldn't find it mentioned in the documentation.

I either lock up the editor (when doing anything on the main thread) or get "not main thread" exceptions when I (say) try to turn it into a coroutine.

My current workaround is to have an async (in app) loader and coroutine (in test) loader - what am I doing wrong?

**Comment by neuecc** [comment]
Are you using `Task` API?
This repository is `UniTask`, `Task` is not concern us.

**Comment by jchown** [comment]
Sorry, I didn't describe that very well!

In preparing an example for you, I found this construct works:

```
[UnityTest]
    public IEnumerator TestLoaderTask() => UniTask.ToCoroutine(async () =>
    {
        SomeAssetType asset = await Loader.LoadAsset("ExampleResource");

        Assert.AreEqual(4, asset.names.Count);
    });
 ```
 
 I was trying to call `ToCoroutine` directly on the `UniTask` which didn't work as it used the thread pool.
