### ISSUE TITLE
How would you do web requests?

### ISSUE THREAD

**Issue by angelhodar** [Cysharp/UniTask#231]
Hey! Just watched your asset and it seems incredibly useful to be able to run async tests and avoid the boilerplate code I had to write to do it, thank you so much! I just wanted to know your opinion about what is the most efficient way to make web requests to get textures and avoid the main thread to be blocked. I have like a museum where for each painting in the scene I have to make web requests to get the information I am going to display from a wordpress (title, images, links, etc). The current workflow is that I have a controller that implements a cache to avoid extra requests, and on Start every paint prefab makes a request with the query specified in its script to the controller (to search in the cache) which makes the real web request via API. Would it be better to change that flow? I mean, for example the controller searches every painting script and makes the web requests for each one. What do you think?

**Comment by neuecc** [comment]
As for architecture, I don't have any advice to offer.
Well, there's nothing wrong with having a cache, is there?
Caching, async/await, and UniTask are pretty good together.
