### ISSUE TITLE
Cannot call Delay twice in a unit test

### ISSUE THREAD

**Issue by benoitdion** [Cysharp/UniTask#234]
While working on a test that exercises code with delays, I ran into an issue where the test runners hangs when running more than 1 delay. I was able to reduce the issue to a simple test:

```
    [UnityTest]
    public IEnumerator DelayTwice() => UniTask.ToCoroutine(async () => {
      await UniTask.Delay(TimeSpan.FromSeconds(1));
      await UniTask.Delay(TimeSpan.FromSeconds(1));
    });
```

environment: Unity 2019

**Comment by neuecc** [comment]
Do you run on `EditMode` test?
In `EditMode`, default Delay's DelayType does not work correctly.
use `DelayType.Realtime` instead or use `PlayMode` test.

**Comment by benoitdion** [comment]
That sounds like the issue. Thank you.

If it's possible, it might be worth throwing an exception instead of the undeterministic behavior.

**Comment by neuecc** [comment]
Sounds good.
I'll do automatically fallback to DelayType.Realtime when run on editor play.

**Comment by neuecc** [comment]
v2.2.0 implements it.

**Comment by benoitdion** [comment]
Thank you! It might still be useful to show a warning letting the user know it's happening since you're now overriding an option specified
