### ISSUE TITLE
UniTask cannot await during batchmode

### ISSUE THREAD

**Issue by KAJed82** [Cysharp/UniTask#237]
Trying to await on UniTask.Yield(), UniTask.Delay( ttt ) does not function during batch mode. Task.Delay( ttt ) functions as expected.

**Comment by neuecc** [comment]
Is batchmode run on EditMode?
same issue as https://github.com/Cysharp/UniTask/issues/234

however, Yield has to work....

**Comment by KAJed82** [comment]
Yes, I'm fairly certain it does. However, I'm not confident that EditorApplication.update gets called during batch mode. Yield simply hangs though.

Unity supports an async void function as the entry point to batch mode so this is what I'm using. UniTask.Yield() hangs the call indefinitely in this case as does UniTask.Delay(); I imagine others do as well.

**Comment by neuecc** [comment]
ok, -batchmode and -quit does not run EditorApplication.update.
(-quit means run only one frame and quit after frame end)
remove -quit and quit manually will work.

**Comment by KAJed82** [comment]
That does seem to allow the delay / yield to function. However, I've noticed that await UniTask.Delay( 10000 ) and await UniTask.Delay( 10000, DelayType.RealTime ) are behaving differently. Without specifying realtime the wait on the first one is about 3 seconds, whereas the realtime one lasted the correct 10 seconds. This was attempted with the 2.1.2 release. Based on the reading I've done it should be defaulting to realtime during edit mode?

**Comment by neuecc** [comment]
automatically fallback is not yet implemented.

**Comment by KAJed82** [comment]
Ah, I must be getting ahead of myself. Closing Issue.
