### ISSUE TITLE
ToObservable of non-generic UniTask does not propagate an exception of a faulted task

### ISSUE THREAD

**Issue by andreimamlay** [Cysharp/UniTask#239]
こんにちは！

Is it intended that calling `ToObservable()` of a non-generic faulted `UniTask` does not propagate exception to observable? 
Meanwhile calling `ToObservable()` of
* non-generic `UniTask` that is not _yet_ faulted but will fault eventually
* generic faulted `UniTask`
* generic `UniTask` that is not _yet_ faulted but fill fault eventually

causes exception to propagate into the observable

```csharp
private async UniTask<bool> GenericFaulted()
{
    throw new DivideByZeroException();
}

private async UniTask<bool> GenericWillFault()
{
    await UniTask.Delay(1);
    throw new DivideByZeroException();
}

private async UniTask NonGenericFaulted()
{
    throw new DivideByZeroException();
}

private async UniTask NonGenericWillFault()
{
    await UniTask.Delay(1);
    throw new DivideByZeroException();
}
```

```csharp
GenericFaulted().ToObservable().Subscribe(
    _ => Debug.LogWarning("generic faulted success"), 
    ex => Debug.LogWarningFormat("genric faulted ex {0}", ex.Message), // <====
    () => Debug.LogWarning("generic faulted completed")
);

GenericWillFault().ToObservable().Subscribe(
    _ => Debug.LogWarning("generic will fault success"),
    ex => Debug.LogWarningFormat("genric will fault ex {0}", ex.Message), // <====
    () => Debug.LogWarning("generic will fault completed")
);

NonGenericFaulted().ToObservable().Subscribe(
    _ => Debug.LogWarning("non-generic faulted success"), // <====
    ex => Debug.LogWarningFormat("non-generic faulted ex {0}", ex.Message),
    () => Debug.LogWarning("non-generic faulted completed") // <====
);

NonGenericWillFault().ToObservable().Subscribe(
    _ => Debug.LogWarning("non-generic will fault success"),
    ex => Debug.LogWarningFormat("non-generic will fault ex {0}", ex.Message), // <====
    () => Debug.LogWarning("non-generic will fault completed")
);
```
`// <====` denotes an output

This happens because `public static IObservable<AsyncUnit> ToObservable(this UniTask task)` procuses `new ReturnObservable<AsyncUnit>(AsyncUnit.Default)` for any non-pending task (including Faulted and Canceled). Changing `task.Status.IsCompleted()` to `task.Status.IsCompletedSuccessfully()` makes all four cases propagate exception into the observable

**Comment by neuecc** [comment]
Thanks, this is a bug as you said.
I've changed to call `task.GetAwaiter().GetResult();` before return.
and released `2.2.3`.
