### ISSUE TITLE
Awaiting scene load permits `Start` to run in loaded scene before returning control flow.

### ISSUE THREAD

**Issue by rhys-vdw** [Cysharp/UniTask#240]
Consider a scene containing this component:
```cs
void Start() {
  Debug.Log("Start");
}
```

A coroutine such as this will log "Loaded", "Start":
```cs
yield return SceneManager.LoadSceneAsync(...);
Debug.Log("Loaded");
```

But on conversion to async/await the order of operation is flipped:
```cs
await SceneManager.LoadSceneAsync(...).ToUniTask();
Debug.Log("Loaded");
```
The above logs "Start", "Loaded".

This is a small change, but it would be nice if we could get control back to the async function before the scene starts running. I'm not sure if this is possible or whether it stems from Unity's async implementation.

It's nice to have this order of execution so that loaded objects can be configured before `Start` runs (in the same way you can when `Instantiating` prefabs).

**Comment by neuecc** [comment]
would you try await SceneManager.LoadSceneAsync(...) ?

**Comment by neuecc** [comment]
ReadMe's PlayerLoop section, I've noticed about it.
https://github.com/Cysharp/UniTask#playerloop

---

AsyncOperation is returned from native timing. For example, await SceneManager.LoadSceneAsync is returned from EarlyUpdate.UpdatePreloading and after being called, the loaded scene's Start is called from EarlyUpdate.ScriptRunDelayedStartupFrame. Also await UnityWebRequest is returned from EarlyUpdate.ExecuteMainThreadJobs.

In UniTask, await directly uses native timing, WithCancellation and ToUniTask use specified timing. This is usually not a particular problem, but with LoadSceneAsync, it causes a different order of Start and continuation after await. So it is recommended not to use LoadSceneAsync.ToUniTask.

**Comment by rhys-vdw** [comment]
Ah, my apologies @neuecc, you're quite right! Thanks for the explanation.
