### ISSUE TITLE
Confusing in multiple awaiting of UniTaskCompletionSource

### ISSUE THREAD

**Issue by KichangKim** [Cysharp/UniTask#241]
Hi.  In document, 
```
Also UniTaskCompletionSource can await multiple times and await from many callers.
```
But UniTask cannot be awaited multiple time. So what is correct usage for multiple awaiting? (Case A or Case B)

```csharp
// Case A
var task = tcs.Task;

await task;
await task;

// Case B
await tcs.Task;
await tcs.Task;
```

If Case B is correct, accessing to tcs.Task return new task instance for every call internally?

Thanks in advance.

**Comment by neuecc** [comment]
If both case A and B does not throws excetion, correct both.
tcs.Task is struct wrapper so does not create class instance.

**Comment by KichangKim** [comment]
> If both case A and B does not throws excetion, correct both.

how about throwing exceptions? any difference?

**Comment by neuecc** [comment]
If you encount `InvalidOperationException: "Already continuation registered, can not await twice or get Status after await."`, incorrect.
If not, correct.
