### ISSUE TITLE
expose ForceEditorPlayerLoopUpdate publicly

### ISSUE THREAD

**Issue by extrawurst** [Cysharp/UniTask#245]
I need to run UniTask inside regular synchronous Unittests:
```
[Test]
public void TestSomethingThatUsesUniTask(){
  UniTaskTestHelper.Run(async () =>
  {
    await UniTask.Yield();
   });
}
```

in order to be able to run `UniTask` synchronously to completion I am currently calling `Cysharp.Threading.Tasks.PlayerLoopHelper.ForceEditorPlayerLoopUpdate` via reflection inside `UniTaskTestHelper.Run`.
This works fine, even in `-batchmode -quit` and makes for well defined/deterministic behaviour if you use `DelayRealtime`. 

It would be nice to expose this publicly.

(maybe related to  #237)

**Comment by neuecc** [comment]
I recommend `[UnityTest]` and `ToCoroutine` for UnityTest.
https://github.com/Cysharp/UniTask#for-unit-testing
Only in a limited number of cases can the problem be solved by manually run it arbitrarily.

**Comment by extrawurst** [comment]
Well like I said the whole point is that I can't use `[unitytest]`

**Comment by neuecc** [comment]
That doesn't seem to be a common demand.

**Comment by extrawurst** [comment]
@neuecc to me it looks like common demand is not to use UniTask in a headless continuous integration environment, which makes using `[UnityTest]` a unreliable pain. 

Ok more context:

For us integrating unittests into the build process via `TestRunnerApi` and `IPreprocessBuildWithReport` to make sure no single build succeeds if there are unittests failing is paramount. 
Unfortunately switching `runSynchronously` to `true` (which would be required by `[UnityTest]` does not make the build wait for the unittests to finish anymore). 
In the past we were using `RSG.Promise` for async functionality which allowed to `tick` promises to completion manually aswell in synchronous unittests. 

It would simply be great to have the same functionality in `UniTask` aswell.

**Comment by neuecc** [comment]
Why don't you test it in PlayMode?
In the CI process, independently of each other, you can just run the PlayMode test first and stop the pipeline if it fails.
