### ISSUE TITLE
怎么在运行时一键关闭所有的UniTask，就像DoTween的 KillAll() 方法一样

### ISSUE THREAD

**Issue by ToddGitHub** [Cysharp/UniTask#248]
如题，在一些静态的网络请求后运行业务逻辑的异步方法中 ，一旦再请求中跳转场景和销毁物体 需要处理很多地方的Cancel，怎么像DoTween的 KillAll() 方法一样 ，在调用时不用传入Canceltoken 也可以在需要的时候 统一停止

**Comment by neuecc** [comment]
There is no other way but to create and pass a common cancellationToken.
