### ISSUE TITLE
Support UPM?

### ISSUE THREAD

**Issue by Thaina** [Cysharp/UniTask#25]
I think this project could just add support to UPM just by adding `package.json`

**Comment by bdominguez** [comment]
Any news?

**Comment by neuecc** [comment]
Yes, I should add support it.

**Comment by AntiGuide** [comment]
@neuecc Are you still planning on adding support? If you put up some guidelines on what you want the change to look like I'm sure someone could add it.

**Comment by bdovaz** [comment]
Any news?

**Comment by shiena** [comment]
You can use path query parameter from unity2019.3.4f1 and unity2020.1a21.
https://forum.unity.com/threads/some-feedback-on-package-manager-git-support.743345/#post-5425311

**Comment by neuecc** [comment]
![image](https://user-images.githubusercontent.com/46207/79446433-2914fb00-8019-11ea-82ef-ea766a8009f6.png)

Path works fine (thanks @shiena ), I want to choose it.

**Comment by shiena** [comment]
@neuecc package.json.meta is missing, so please add it.
![image](https://user-images.githubusercontent.com/1295639/79450065-519ff380-801f-11ea-89a5-11522bc67ece.png)

**Comment by neuecc** [comment]
yes, now committed.

**Comment by neuecc** [comment]
Add documantation.
https://github.com/Cysharp/UniTask#upm-package

**Comment by shiena** [comment]
@neuecc Thank you very much. It works perfectly.
