### ISSUE TITLE
Nested task cancelation

### ISSUE THREAD

**Issue by yadreny** [Cysharp/UniTask#250]
Hello, there is a code in the examples the essence of which can be reduced to
 ```
private async UniTask MainTask(CancellationToken ct)
{
    Debug.Log("Started");
    while (!ct.IsCancellationRequested)
    {
        await UniTask.Delay(100);  
    }
    Debug.Log("Finished");
}
 ```
It works fine, but if you change 100 to 100000, we won't see "finished" very soon.
I thought it may be fixed by adding the token to nested task
 ```await UniTask.Delay(1000000, CancellationToken:ct); ```
however, in this case,  "finished" will never be shown.

My goal is to have an option to cancel nested task and execute some code after the loop,
is it possible?
Thank you.

**Comment by neuecc** [comment]
when cancel deteced, await throws `OperationCanceledException`.

```csharp
private async UniTask MainTask(CancellationToken ct)
{
   Debug.Log("Started");
   try
    {
       while (!ct.IsCancellationRequested)
      {
           await UniTask.Delay(100, ct.Token);  
       }
    }
    finally
    {
       Debug.Log("Finished");
    }
}
```

see https://github.com/Cysharp/UniTask#cancellation-and-exception-handling section.

**Comment by yadreny** [comment]
Thank you so much, you've been very helpful.
