### ISSUE TITLE
Using Unitask inside OnApplicationQuit and OnApplicationPause

### ISSUE THREAD

**Issue by ragavendranbala** [Cysharp/UniTask#252]
I'm trying to call an coroutine that sends some values to the server using UnityWebRequest on Android and I have written this segment in OnAppicationPause and OnAppicationQuit. But unfortunately the coroutine got paused and it's not hitting the server.
How to use this UniTask to solve my problem? if code snippets are available, kindly share that.

**Comment by neuecc** [comment]
can not wait asynchronously at OnApplicationQuit and OnAPplicationPause.

**Comment by dimmduh** [comment]
@ragavendranbala did you find solution?
I'm trying to FileStream WriteAsync in OnApplicationPause. The file is empty.

**Comment by ragavendranbala** [comment]
Hi @dimmduh , nope, I didn't
