### ISSUE TITLE
Ignore warnings in Unity instead of .Forget

### ISSUE THREAD

**Issue by iliaJelly** [Cysharp/UniTask#254]
In this section
https://github.com/Cysharp/UniTask#async-void-vs-async-unitaskvoid

It reads - "If you don't require awaiting (fire and forget), using UniTaskVoid is better. Unfortunately to dismiss warning, you're required to call **Forget**()."

I believe that adding 
-nowarn:1998
-nowarn:4014

to the csc.rsp file Will ignore these warnings. At least thats what I do.
https://docs.unity3d.com/Manual/PlatformDependentCompilation.html <-- has info about csc.rsp files in Unity

**Comment by neuecc** [comment]
Yes.
However, I don't recommend stopping at the assembly level, as this also removes the warning of a situation where you really need to await.

**Comment by iliaJelly** [comment]
Ok, seems legit.
