### ISSUE TITLE
Typo in Enumerable

### ISSUE THREAD

**Issue by iliaJelly** [Cysharp/UniTask#255]
In this section
https://github.com/Cysharp/UniTask#asyncenumerable-and-async-linq

Reads - "UniTaskAsyncEnumerable is the entry point like Enumerbale"

Should be - "UniTaskAsyncEnumerable is the entry point like Enumerable"

**Comment by neuecc** [comment]
thanks, fixed at PR.

**Comment by neuecc** [comment]
thanks, fixed at PR.
