### ISSUE TITLE
plan to support ui toolkit

### ISSUE THREAD

**Issue by tangxianbo** [Cysharp/UniTask#261]
Is there any plan to support unity's new ui framework UI Toolkit?

**Comment by neuecc** [comment]
What api do you want to?

**Comment by tangxianbo** [comment]
like this:

VisualElement button;
button.OnPointUpAsAsyncEnumerable()
           .ForEachAwaitWithCancellationAsync(async (_, ct) =>
            {
                Debug.Log("Clicked!");
            }, token);

**Comment by neuecc** [comment]
thanks, interesting.
I'll investigate it.

**Comment by tangxianbo** [comment]
thanks

**Comment by Iblis** [comment]
@tangxianbo I implemented initial UIToolkit Support and created a PullRequest. I did not implement the API as you suggested, but I hope it still works for you the way I did it.
