### ISSUE TITLE
WhenAny and WhenAll with two parameters of type UniTask

### ISSUE THREAD

**Issue by SolidAlloy** [Cysharp/UniTask#262]
Currently, UniTask supports WhenAny and WhenAll only with a number of `UniTask<T>` parameters. When multiple UniTask parameters are passed, it is accepted with the _params_ keyword and as such, allocates an array each time. In NET 5, [WhenAny accepts two Task parameters](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.whenany?view=net-5.0#System_Threading_Tasks_Task_WhenAny_System_Threading_Tasks_Task_System_Threading_Tasks_Task_). Can we add this override to UniTask too? Supporting even more UniTask parameters is a plus (I would like to see an override with three UniTask parameters. Anything more than that can be passed as _params_).

**Comment by neuecc** [comment]
already has T1~T15 overload.
https://github.com/Cysharp/UniTask/blob/master/src/UniTask/Assets/Plugins/UniTask/Runtime/UniTask.WhenAny.Generated.cs#L12

**Comment by SolidAlloy** [comment]
But I can't use it with a non-generic UniTask, can I?
```csharp
async UniTask MainMethod()
{
    await UniTask.WhenAny(DummyWithoutReturn1(), DummyWithoutReturn2());
}

async UniTask DummyWithoutReturn1() => await UniTask.NextFrame();
async UniTask DummyWithoutReturn2() => await UniTask.NextFrame();
```

**Comment by neuecc** [comment]
You're right, I don't make a non-generics version.
I think it's worth preparing this, so I'll try it.
Thank you.

**Comment by SolidAlloy** [comment]
Thank you!

**Comment by neuecc** [comment]
discussions will moved to PR.
