### ISSUE TITLE
Cancel UniTask when object get destroyed

### ISSUE THREAD

**Issue by jrmgx** [Cysharp/UniTask#264]
Hi,
First, thank you for this wonderful library!

I have a question, I did not find the right way (did not find anything about it in the doc)
to cancel all awaiting UniTask when a given GameObject is destroyed.

My scenario is simple,
I have a script attached to a GameObject, things runs, and then this object get destroyed from an external script.

What I would like is to end all awaiting tasks (some may run/wait at the moment of the destroy call)

What is happening in my code, the object get destroyed but the instruction after the last await gets called and most of the time will throw some null exception as the host object is destroyed

I spent plenty of time reading the doc and the part about cancellation but I did not find something that respond to my pretty basic use case.

Am I missing something here?

Thank you

**Comment by neuecc** [comment]
Is this secion not helped for you?
https://github.com/Cysharp/UniTask#cancellation-and-exception-handling

`this.GetCancellationTokenOnDestroy()` gets the CancellationToken.
And pass CancellationToken to all your async operations.

```csharp
var token = this.GetCancellationTokenOnDestroy();
FooAsync(token);

async UniTask FooAsync(CancellationToken token)
{
    await BarAsync(token);
}
```

**Comment by jrmgx** [comment]
It looks like it is what I need, but from the doc it is hard to get how it works.
I'm going to implement it in my code and I may come back to you with a PR to improve the doc if you want.
Thank you for the pointer, now I understand better that part.

**Comment by neuecc** [comment]
I've added more note to ReadMe. thanks.
