### ISSUE TITLE
IPromise in Cysharp.Threading.Tasks

### ISSUE THREAD

**Issue by iliaJelly** [Cysharp/UniTask#267]
Hi, In our studio we are using RSG Promises
https://github.com/Real-Serious-Games/C-Sharp-Promise

We are interested in UniTask because we want to replace our usage of RSGPromises with it.

We are getting naming collisions, its solvable but annoying.

Can I recommend to set the namespace of IPromise/Promise classes to be different than Cysharp.Threading.Tasks. 

If these types are not intended for user uses, maybe have them internal or something?

In anycase we will change the namespace of these types in our project meanwhile.

**Comment by neuecc** [comment]
maybe these interfaces is unused...
I'll remove all.
