### ISSUE TITLE
I want "UniTaskAsyncEnumerable.Merge"

### ISSUE THREAD

**Issue by euglenach** [Cysharp/UniTask#271]
UniRx has Observable.Merge.
UniTask has methods for merging, such as "Concat" and "CombineLatest" and etc..., but not "Merge" .Please think about it.

 I'm sorry if there is a method with the same functionality. (translated by DeepL)

**Comment by neuecc** [comment]
thanks for request, I'll try to implement it.

**Comment by euglenach** [comment]
Thank you!
I'm looking forward to it!

**Comment by itsagam** [comment]
Hi, seeing as the author didn't get the time, how would one go about implementing it?
