### ISSUE TITLE
PlayerLoopTiming.Update should run after ScriptRunBehaviourUpdate

### ISSUE THREAD

**Issue by NikolaNikolov** [Cysharp/UniTask#273]
At the moment tasks run by default just before ScriptRunBehaviourUpdate however that is way too early. Most Unity plugins and all of our own code runs in ScriptRunBehaviourUpdate and that makes tasks use previous frame data. That results is either a 1 frame delay for tasks (in order for the data to catch up) or totally wrong results. For instance reading the same input from Rewired in both MonoBehaviour.Update and a UniTask will result in different values during the same frame.

I'm aware that we can switch timing on demand but its too much boilerplate to do it in every single task and if we forget we are constantly getting unexpected results.
I think it will be more straightforward to either change the default timing or at least provide the option to specify a default timing for all tasks without the need to constantly call UniTask.Yield.

**Comment by neuecc** [comment]
Good point.
I won't change the default, but how about making it customizable?

like this api...
```csharp
PlayerLoopHelper.Initialize(ref loop, (timing) =>
{
   if (timing == PlayerLoopTiming.Update)
   {
        return typeof(ScriptRunBehaviourUpdate);
   }
   return null; // use default.
});
```

**Comment by NikolaNikolov** [comment]
Yeah that sounds great. Would definitely solve our issues. Thanks.
