### ISSUE TITLE
Is there a UniTask.Noop()?

### ISSUE THREAD

**Issue by Ivan-Vankov** [Cysharp/UniTask#275]
The following situation happens frequently in my code.
```
public UniTask Foo() {
    if (someEarlyOutCondition) {
        return UniTask.NextFrame();
    }
    //...
}
```
Awaiting Foo() loses a frame.
Is there a noop UniTask method that I could use here?

**Comment by neuecc** [comment]
`UniTask.CompletedTask`?

**Comment by Ivan-Vankov** [comment]
That works. Thank you!
