### ISSUE TITLE
How to synchronously run and wait a task on main thread ?

### ISSUE THREAD

**Issue by HyVong007** [Cysharp/UniTask#276]
I want to have method "UniTask.Wait(UniTask task)" like "System.Threading.Tasks.Task.Wait". Sometimes i want to sync wait a unitask on main thread.
Surely, there is a time that i must use synchronous over async !

**Comment by neuecc** [comment]
I understand the feeling, but unlike Thread-based Tasks, PlayerLoop-based UniTasks often cause deadlocks.
If the contents of UniTask are completely thread-based, and you really want to wait synchronously, you can convert it to a Task and wait for it.

**Comment by HyVong007** [comment]
ok thank you. I will convert to Task when i want sync wait, thank

**Comment by Skipper0X** [comment]
converting a UniTask to Task to Wait is causing the Unity to freeze, it was coming from an Addressable operation btw.

actually i've to Wait there Cz i'm using it with Legacy code and that code is not Async friendly
