### ISSUE TITLE
What `AttachExternalCancellation(token)` does?

### ISSUE THREAD

**Issue by mnarimani** [Cysharp/UniTask#277]
Every `UniTask` instance has a method called `AttachExternalCancellation` which takes a cancellation token.

How this method works and when should we use it?

**Comment by neuecc** [comment]
I see, the documentation is missing, I'll add it later.

Let me quote from my blog post (translated by DeepL)
http://neue.cc/2021/02/26_599.html

> UniTask.WithCancellation has been renamed to AttachExternalCancellation. AsyncOperation.WithCancellation is a cancellation process from the inside, while UniTask.WithCancellation is a cancellation process from the outside. Internal cancellation is preferable, but it's not good if you can't tell whether it's internal or external cancellation just by looking at the code. It's not good. No good. So I changed it. The name also implies that you don't want to use it, so don't use it too much.

**Comment by mnarimani** [comment]
@neuecc Thanks.

**Comment by Atlinx** [comment]
@neuecc Sorry to resurrect this thread, but I'm still confused as to what `AttachExternalCancellation(token)` does. I have to following code below:

```C#
UniTask.Create(async () =>
{
    Debug.Log("Start");
    await UniTask.Delay(TimeSpan.FromSeconds(1f));
    Debug.Log("End");
}).AttachExternalCancellation(cancelWaitToDeactivate.Token).Forget();
```

If I run the task and then dispose the token, the task doesn't end.

However, the following below works:
```C#
UniTask.Create(async () =>
{
    Debug.Log("Start");
    await UniTask.Delay(TimeSpan.FromSeconds(1), cancellationToken: cancelWaitToDeactivate.Token);
    Debug.Log("End");
}).Forget();
```

**Comment by neuecc** [comment]
I've tested.

// AttachExternalCancellation
![image](https://user-images.githubusercontent.com/46207/183069320-1d3ad240-b629-493a-8533-ab962c1a84ef.png)

// Delay(cancellationToken)
![image](https://user-images.githubusercontent.com/46207/183069408-7aa41056-20f0-466c-a5c2-7a71196639dd.png)

Both works as expected.

**Comment by Atlinx** [comment]
Does external cancellation not stop the task from continuing then, since it looks like End was still fired in your example with `AttachExternalCancellation`?

**Comment by neuecc** [comment]
inside of UniTask.Create is internal task, external cancellation does not stop it as document described.

**Comment by Atlinx** [comment]
Oh wait, is it because UniTask.Create itself is a task, therefore the token is supposed to cancel UniTask.Create and not the task inside?

**Comment by heeen** [comment]
In the example you have a method (the lambda) that itself is awaiting tasks (delay). then you have the outer method that is creating a task wrapping the lambda.

if you attach an external cancellation, the outer method is allowed to continue and handle the cancelled operation, however the lambda and any tasks awaited on within do not get the cancellationToken and thus cannot be cancelled this way.

@neuecc I am curious if this is a good way to use a UniTaskCancellationSource that is awaited by multiple users which each want to abort waiting on it at different times?
