### ISSUE TITLE
(#Documentation) What is "PlayerLoopTiming" ? How to use it ?

### ISSUE THREAD

**Issue by HyVong007** [Cysharp/UniTask#279]
For example: there are 10 gameObjects (with 1 Mono script per each gameObject) currently in the scene.
Each mono script have all the Unity callbacks like Awake, OnEnable, Start....

Now i want to:
1/ Wait for all Awake and OnEnable to be called and completed, then do something. How to do ?
2/ Wait for all Start to be called and completed, then do something. How to do ?
3/ Wait for all Update to be called and completed in ONE CYCLE, then do something. How to do ?
4/ Wait for all FixedUpdate to be called and completed in ONE CYCLE, then do something. How to do ?

...
...

All the scenerios !

=> i spend long time googling but found no good understandable documentation and i feed VERY VERY VERY STUPID CRAZY ! Thank you very much and sorry for my bad english !!!

**Comment by neuecc** [comment]
PlayerLoop and PlayerLoopTiming are documented here.
https://github.com/Cysharp/UniTask/#playerloop

1. can not.
2. can not.
3. can not.
4. can not.
