### ISSUE TITLE
Mobile App Stall

### ISSUE THREAD

**Issue by tgaldi** [Cysharp/UniTask#281]
Hello,

When using UniTask for multithreaded background work, my application stalls for a few seconds on a mobile device when the work is started. 

I'm doing the following:

     
        internal void StartAsync( string filePath )
        {
            Worker( filePath ).Forget();
        }

        private async UniTaskVoid Worker( string filePath )
        {
            await UniTask.SwitchToTaskPool();
            _encoder.Start( filePath );

            for( int i = 0; i < _frames.Count; ++i )
            {
                GifFrame frame = _frames[i];
                _encoder.AddFrame( frame );
            }
            _encoder.Finish();

            await UniTask.SwitchToMainThread();
            _onFileComplete( filePath );
        }

I've tried using `SwitchToThreadPool` and `RunOnThreadPool` as well.

**Comment by codemonkeynorth** [comment]
@tgaldi would be useful to include your solution please if you resolved it ?
