### ISSUE TITLE
[Info Request] Comparison to standard async/await?

### ISSUE THREAD

**Issue by JimmyDeemo** [Cysharp/UniTask#282]
I was wondering if there is a comparison and/or documentation discussing considerations between UniTask and standard async/await calls.

I am evaluating how rolling out async/await throughout our project will help and I'm trying to make an informed decision on what to use.

**Comment by neuecc** [comment]
Is ReadMe not enough for you?
It's allocation free (Task is not) and player loop based (Task is threadpool based).

**Comment by JimmyDeemo** [comment]
Apologies. I appear to have missed things like [this post](https://neuecc.medium.com/unitask-v2-zero-allocation-async-await-for-unity-with-asynchronous-linq-1aa9c96aa7dd) and instead about how to use UniTask. I will do more reading and ask specific questions if not covered.
