### ISSUE TITLE
When to use UniTaskSynchronizationContext?

### ISSUE THREAD

**Issue by mnarimani** [Cysharp/UniTask#283]
Documentations regarding `UniTaskSynchronizationContext` are a little bit confusing for me.  
I cannot figure out if I need to use `UniTaskSynchronizationContext` or not.  
In docs, it says:  

> Unity's default SynchronizationContext(UnitySynchronizationContext) is a poor implementation for performance. UniTask bypasses SynchronizationContext(and ExecutionContext) so it does not use it but if exists in async Task, still used it. UniTaskSynchronizationContext is a replacement of UnitySynchronizationContext which is better for performance.

and later:

> This is an optional choice and is not always recommended; `UniTaskSynchronizationContext` is less performant than `async UniTask` and is not a complete UniTask replacement. It also does not guarantee full behavioral compatibility with the `UnitySynchronizationContext`.

I have some difficulties understanding what is best for performance. Could you elaborate a little more? Do I even need to use `UniTaskSynchronizationContext` if I'm using async UniTask for normal functions and async void for event handlers?

**Comment by neuecc** [comment]
If you don't understand what `SynchronizationContext` means, you don't need to use it.
The best performance is to use only async UniTask/UniTaskVoid.
