### ISSUE TITLE
How to Delay/WaitUntil in .net build?

### ISSUE THREAD

**Issue by fantasyz** [Cysharp/UniTask#286]
Hi,

I tried to use UniTask in .net project outside unity. However, it could not compile. It is missing some functions such as Delay, WaitUntil.

> Error	CS0117	'UniTask' does not contain a definition for 'Delay'
> Error	CS0117	'UniTask' does not contain a definition for 'WaitUntil'

I read that UniTask of .NET Core version is a subset of Unity UniTask with PlayerLoop dependent methods removed.
Are these those PlayerLoop dependent functions?

While I understand DelayFrame is probably normal to be missing, how do I wait for a period of time or for a condition like regular async await task with UniTask? 

Thanks in advance.

**Comment by neuecc** [comment]
`Delay` and `WaitUntil` is depend on Unity's PlayerLoop.
.NET Core, of course, does not have PlayerLoop.
You should call Delay depending on the thread pool, so let's use Task.Delay.

**Comment by fantasyz** [comment]
oh I see. Thanks
