### ISSUE TITLE
Can I use refection method call with UniTask with return value?

### ISSUE THREAD

**Issue by yudi-xiao-letscoze** [Cysharp/UniTask#287]
Hi,

I am trying to use Reflection call in Unity under WebGL platform runtime.
One of the feature required getting the return value from an await-able task.
So I have something like this implemented : 

``` C#
namespace AysncTest{
    public class Tester{
        public Tester() {}
        public async UniTask<bool> Guess(int waitTime)
        {
            await UniTask.Delay(TimeSpan.FromSeconds(waitTime));
            var result = waitTime % 2 == 0;
            return result;
        }
    }

    public class Caller {
        public Caller(){}
        //Usage : await caller.InvokeAsync(tester, "Guess", 2);
        public UniTask<object> InvokeAsync(object target, string methodName, params object[] args){
            var method = Tester.GetType().GetMethod(methodName);
            dynamic task = method.Invoke(target, args); //This can only be use in JIT
            return await task;
        }
    }
}
```

But then I found out the keyword "dynamic" can only be use in JIT, according to an [answer](https://stackoverflow.com/questions/7478387/how-does-having-a-dynamic-variable-affect-performance/7480977#7480977) by Eric Lippert.

Will there be any other alternative way that I can do this?

**Comment by neuecc** [comment]
If return value is `UniTask`, `var task = method.Invoke(target, args) as UniTask; await task`.
If return value is `UniTask<T>`, require to more step, convert `UniTask<T> to `UniTask`.
this is the concept code, I didn't check it works.

```csharp
object task = method.Invoke(target, args);
object preservedTask = preserveMethod.Invoke(task); // task.Preserve();
await (preservedTask as UniTask);
return getResultMethod.Invoke(getAwaiterMethod.Invoke(task)); // task.GetAwaiter().GetResult();
```

**Comment by yudi-xiao-letscoze** [comment]
![image](https://user-images.githubusercontent.com/79615839/120781571-c6076000-c55b-11eb-80ad-afa59b27fe45.png)
I am getting exception from converting UniTask<bool> to UniTask, and I've tried using object as UniTask, the compiler won't let me run due to this :
![image](https://user-images.githubusercontent.com/79615839/120781931-18488100-c55c-11eb-8866-2a294098b348.png)

**Comment by neuecc** [comment]
Yes, can not convert `UniTask<T>` to `UniTask` so you need to implement simila as my concept code.

**Comment by yudi-xiao-letscoze** [comment]
Did you mean I should look into `UniTask.Preserve()` and 'UniTask<T>.Preserve()' and implement something similar?
I am a bit confuse by what you mean by // task.Preserve();

**Comment by yudi-xiao-letscoze** [comment]
``` C#
var awaitableTask = method.Invoke(targetObject, commandTargetTarget.Command.args);
var taskType = awaitableTask.GetType();
var preserveMethod = taskType.GetMethod("Preserve");
preserveMethod?.Invoke(awaitableTask, null);
await (awaitableTask as UniTask);
var taskResult = taskType.GetMethod("GetResult")?
                            .Invoke(taskType.GetMethod("GetAwaiter")?
                                .Invoke(awaitableTask, null), null);
```

This is what I am using in my testing project

**Comment by yudi-xiao-letscoze** [comment]
![image](https://user-images.githubusercontent.com/79615839/120786624-061d1180-c561-11eb-9f34-8058d6447c6c.png)
here is an screenshot of my debugging session information

**Comment by neuecc** [comment]
sorry, It lacked asUniTaskMethod.Invoke(preserveTask).

**Comment by yudi-xiao-letscoze** [comment]
``` C#
var awaitableTask = method.Invoke(targetObject, commandTargetTarget.Command.args);
var taskType = awaitableTask.GetType();
var preserveMethod = taskType.GetMethod("Preserve");
var asUniTaskMethod = taskType.GetMethod("AsUniTask");
var preserveTask = preserveMethod?.Invoke(awaitableTask, null);
var preserveUniTask = (UniTask) asUniTaskMethod?.Invoke(preserveTask, null);
await preserveUniTask;
var preserveType = preserveTask.GetType(); // I think this will always be the same as taskType, maybe I can just use taskType ?
var getResultMethod = preserveType.GetMethod("GetResult");
var getAwaiterMethod = preserveType.GetMethod("GetAwaiter");
var taskResult = getResultMethod?
    .Invoke(getAwaiterMethod?.Invoke(preserveTask, null), null); //Tried `awaitableTask`, 'preserveTask' and 'preserveUniTask' as target object here, both return null
```

I've got the conversion between UniTask<T> and UniTask working, but still getting null as task's result `taskResult  = null`.

**Comment by yudi-xiao-letscoze** [comment]
``` C#
var awaitableTask = method.Invoke(targetObject, commandTargetTarget.Command.args);
var taskType = awaitableTask.GetType();
var preserveMethod = taskType.GetMethod("Preserve");
var asUniTaskMethod = taskType.GetMethod("AsUniTask");
var preserveTask = preserveMethod?.Invoke(awaitableTask, null);
var preserveUniTask = (UniTask) asUniTaskMethod?.Invoke(preserveTask, null);
await preserveUniTask;
var getAwaiterMethod = taskType.GetMethod("GetAwaiter");
var awaiter = getAwaiterMethod?.Invoke(preserveTask, null);
var getResultMethod = awaiter?.GetType().GetMethod("GetResult");
var taskResult = getResultMethod?.Invoke(awaiter, null);
```

Finally get it working, here is my final working code incase anyone have the same problem.

**Comment by yudi-xiao-letscoze** [comment]
Having some wired casting problem on the actual built version, 
> System.InvaildCastException : Unable to cast object of type 'UniTask`1' to type 'UniTask'

This exception was throws when is running at
`var preserveUniTask = (UniTask) asUniTaskMethod?.Invoke(preserveTask, null);`

It cause my code fail to await `preserveUniTask` and getting the result too soon (witch will be null). 

Any idea what might be the cause of this exception?

**Comment by yudi-xiao-letscoze** [comment]
After a lot of try catch, I verified that this bug have nothing to do with UniTask.

I've use custom attributes on the function's return value to identify what is the generic type T of UniTask<T>,
but the IL2CPP compiler must have strip that away.

So I now replace this approach with checking `methodInfo.ReturnType.ContainsGenericParameters` and getting its Type via 
`methodInfo.ReturnType.GenericTypeArguments`.
