### ISSUE TITLE
How to cancel a UniTask.WaitUntil()

### ISSUE THREAD

**Issue by ahmetayrnc** [Cysharp/UniTask#29]
I have a method that plays a particle, waits for that particle to finish then calls another method.

```
//Method Call
await UniTask.WaitUntil((() => !particle.isPlaying));
//Method Call
```

However, when I reload the scene the particle system gets destroyed and I get a 
`The object of type 'ParticleSystem' has been destroyed but you are still trying to access it. ` exception. Is there a way to cancel the UniTask that I could cancel it before reloading the scene?

**Comment by phongsoyenmoc** [comment]
Hello, can you try doing something like this: `    private CancellationTokenSource _cancellationTokenSource;
    [SerializeField] private ParticleSystem particle;

    public void Start()
    {
        _cancellationTokenSource = new CancellationTokenSource();

        WaitParticle();
    }

    public async void WaitParticle()
    {
        try
        {
            await UniTask.WaitUntil((() => !particle.isPlaying), cancellationToken: _cancellationTokenSource.Token);
        }
        catch (OperationCanceledException e)
        {
            Debug.Log(e.Message);
        }

        //TODO
    }

    [ContextMenu("To Menu")]
    public void ChangeScene()
    {
        _cancellationTokenSource.Cancel();
        SceneManager.LoadScene("menu");
    }`

**Comment by ahmetayrnc** [comment]
Thank you for the quick reply, this fixed my issue. Is there any documentation that I could read to find more about the cancellation tokens? I could not find it in my search.

Thank you again!

**Comment by gakkossphynx** [comment]
thanks for example, more example more appreciate :)
