### ISSUE TITLE
Question about defining UNITASK_DOTWEEN_SUPPORT

### ISSUE THREAD

**Issue by andreyshade** [Cysharp/UniTask#290]
Could anyone provide me short short description how to define UNITASK_DOTWEEN_SUPPORT to enable it?

**Comment by yellowisher** [comment]
You can define at `Project Setting -> Player -> Other Settings -> Scripting Define Symbols`

**Comment by andreyshade** [comment]
Thank you @yellowisher  for help. I'm very appreciated. May be It worth to add this tip to official doc?
