### ISSUE TITLE
UniTasks doesn't stop when exiting play mode or switching scenes

### ISSUE THREAD

**Issue by Abdelfattah-Radwan** [Cysharp/UniTask#292]
I came across #22 which mentioned this problem before and @neuecc said in one of his replies to that issue that it was fixed.

Well, I'm running Unity 2021.1.12f1 and UniTask 2.2.5 and it still happens.

Example:

```cs
public sealed class Counter : MonoBehaviour
{
	public bool force;
	
	private int _remaining = 60;
	
	private async UniTask Run()
	{
		while (_remaining > 0)
		{
			_remaining--;
			
			// For this example, force is NEVER true.
			await UniTask.WhenAny(UniTask.Delay(1000), UniTask.WaitUntil(() => force == true));
		}
		
		Debug.Log("Shouldn't execute when I exit play mode but it does...", this);
	}
}
```

`Run` is called from another function like this: `await Run()`.

Am I doing something wrong?!

**Comment by Abdel-Fattah-Radwan** [comment]
By the way, I know that `CancellationToken` exists but isn't there a way to pass one to an entire task instead of having to pass to manually to stuff like `UniTask.Delay`?

**Comment by Last8Exile** [comment]
No. Every task is running independently, so if you cancel main task, running childs still running.
CancelationToken need to be fully propagated to the deepest task.
CancelationToken isn't magic, so every task need to check if cancelation is requested.
Most of time you don't need to check for cancelation and only pass cancelation token to subtasks.
If some of subtasks not support cancelation - place "cancelationToken.ThrowIfCancelationRequested()" on the next row after await call of subtask.

**Comment by develax** [comment]
@Abdel-Fattah-Radwan  Just created an issue #305 and then found yours.
