### ISSUE TITLE
Await async methods with a conditional operator

### ISSUE THREAD

**Issue by SolidAlloy** [Cysharp/UniTask#293]
Currently, if we want to run an async method but only if the instance is not null, we should write this:
```csharp
if (_instance != null)
{
    await instance.Execute();
}
```

I think it would be useful and readable if we can run it as a conditional expression:
```csharp
await instance?.Execute();
```

If the instance is null, the execution of the method just will be skipped.

We can implement it quite simply, by doing an extension method for `Nullable<UniTask>`:
```csharp
public static UniTask.Awaiter GetAwaiter(this UniTask? uniTask)
{
    return uniTask?.GetAwaiter() ?? UniTask.CompletedTask.GetAwaiter();
}
```

We can also implement this for methods that return reference or value nullable types, so that we can use it like this:
```csharp
string str = await instance?.GetString(); // if _instance is null, null will be returned.
```

However, there is a readability issue if we try to use it on a non-nullable value type:
```csharp
// if _instance is null, the default value will be returned (0). This may be not what the developer is expecting.
int integer = await instance?.GetInt();
```

Can we make it so that a nullable type is returned?
```csharp
int? integer = await instance?.GetInt(); // if _instance is null, null will be returned.
```

This will require casting or converting `UniTask<T>.Awaiter` to `UniTask<T?>.Awaiter`. When a non-nullable result is ready, such an awaiter will just wrap it in Nullable and return it. Can we implement it?
```csharp
public static UniTask<T?>.Awaiter GetAwaiter<T>(this UniTask<T>? uniTask) where T : struct
{
    if (uniTask != null)
    {
        // Compile error. Cannot cast UniTask<T>.Awaiter to UniTask<T?>.Awaiter
        return uniTask.Value.GetAwaiter();
    }

    return new UniTask<T?>().GetAwaiter();
}
```

Nullables can be supported in other parts of UniTask, like `UniTask.WhenAll()`
```csharp
await UniTask.WhenAll(var1?.Execute(), var2?.Execute());
```

UniTask users can implement support of Nullables through extension methods and additional static classes, but my suggestion is to include it as a part of UniTask. I think it will extend the usability of UniTask and will be an intuitive feature.

If you don't like the idea of supporting conditional expressions, please consider implementing the casting/converting of `UniTask<T>.Awaiter` to `UniTask<T?>.Awaiter` so that we can use it in extension methods as shown above.

**Comment by neuecc** [comment]
UniTask is not designed to use nullable.
If you want to await directly, just define the extension method yourself and you should be fine.
However, it will not be included in the standard.

**Comment by SolidAlloy** [comment]
Thanks for the answer, I'll close the issue then.
