### ISSUE TITLE
AttachExternalCancellation not working (or perhaps I don't understand it)

### ISSUE THREAD

**Issue by aroman** [Cysharp/UniTask#294]
Hi,

I have some async functions that I'd like to be able to cancel.

consider this function `Foo`, which calls several other async functions, `Bar`, `Baz`, and `Qux`. But those other functions do NOT accept a cancellation token as a parameter.

```cs
public async UniTask Foo() {
  var result1 = await Bar();
  var result2 = await Baz(result1);
  await Qux();
}
```

When I call:

```cs

public class MyComponent : MonoBehaviour {

  public async UniTaskVoid Start() {
    var token = this.GetCancellationTokenOnDestroy();
    token.ThrowIfCancellationRequested();
    await Foo.AttachExternalCancellation(token);
  }

}
```

I would expect that when the `MyComponent` component is removed, `Foo` would be cancelled, and the cancellation would propagate to any of the functions it calls, and an exception would be thrown. 

However, when I destroy `MyComponent`, it does not throw, and none of the async functions called inside `Foo` seem to get cancelled.

Is this a bug, or am I misunderstanding how `AttachExternalCancellation()` is supposed to work?

**Comment by neuecc** [comment]
`AttachExternalCancellation` is `external` cancellation, it does not abort inner task.
If you want to abort inner task, pass CancellationToken.
