### ISSUE TITLE
No good way to know which Task completed after 'WhenAny'

### ISSUE THREAD

**Issue by rollie42** [Cysharp/UniTask#295]
Given something like:

```
await UniTask.WhenAny(someTask, anotherTask);

if (someTask.GetAwaiter().IsCompleted) { // This throws due to ValidateToken
} else {
}
```

`WhenAny` does seem to return the index of the task that first succeeded, but checking an index feels hard to maintain. Out of curiosity, why does `UniTask.Status` throw if its already been awaited?

**Comment by neuecc** [comment]
UniTask returns the internal structure to the Pool when the await completes.
This is a tradeoff for zero allocation.

**Comment by rollie42** [comment]
Would it perhaps be possible to return the UniTask object itself that completed? That would at least allow 

`if (finishedTask == someTask)`

**Comment by neuecc** [comment]
This is impossible because the entity is replaced by a Pool.
Please use the return value of WhenAny to determine it.
