### ISSUE TITLE
Automatic UniTask cleanup on UnityEngine.Object destroy.

### ISSUE THREAD

**Issue by thebeardphantom** [Cysharp/UniTask#296]
One big gotcha when migrating from Coroutines to UniTask is the need to use `CancellationTokens` to handle `UniTasks` sourced from `UnityEngine.Objects`. With Coroutines, all currently running routines are automatically cancelled when the "host" object is destroyed. It makes a lot more sense to me that this behavior is managed by the underlying execution mechanism if possible, instead of being required by the end-user.

While step-thru-debugging the generated state machines in UniTask I noticed that the last field always seems to be the source object of the async function (like the `Target` field on a System.Delegate):
![image](https://user-images.githubusercontent.com/3935328/124182416-aa647c00-da6b-11eb-9b4f-6545c65933ea.png)

I was wondering if the execution of the state machines could be modified such that it would check if the source object (`__this` field) is an instance of `UnityEngine.Object`, and if it has been destroyed. In this case it could cancel/terminate the async function. I only have a broad understanding of the extent of control over task-like objects, so I'm unsure if it would be possible to forcibly terminate a `UniTask` in this manner.

A global cancellation solution would be ideal, as the current solution of relying cancellation tokens creates several issues:
- `this.GetCancellationTokenOnDestroy()` is convenient but incurs an `AddComponent` call, which is expensive, especially at scale.
- Bypassing `this.GetCancellationTokenOnDestroy()` requires either a lot of boilerplate or an abstract class for all `MonoBehaviours` that would have async functions (which is inflexible).

**Comment by neuecc** [comment]
It's not enough to just check the timing of it.
If you are concerned about performance, I actually recommend that you prepare an abstract class.

**Comment by neuecc** [comment]
There's also `CancelTokenSource.RegisterRaiseCancelOnDestroy`.

**Comment by RedHatJef** [comment]
What was the conclusion here @neuecc ?  I don't see if there was any action.  I would love to have a global setting - something like "UniTaskScheduler.RegisterRaiseCancelOnDestroy = true" as something I could set.

**Comment by neuecc** [comment]
The issue with AddComponent has been resolved with the addition of MonoBehaviour.destroyCancellationToken.
The use of CancellationToken as a representation of the lifetime in async/await must be accepted.a

**Comment by Eugen1344** [comment]
@neuecc I second that. This will be a very useful feature. Most of us want a UniTask to be stopped after a MonoBehaviour is destroyed. This can be an optional setting, rather than default one. Because now we often need to chain cancellation tokens if we want a custom one and an obvious, OnDestroy one

**Comment by flowerhouse-dev** [comment]
> @neuecc I second that. This will be a very useful feature. Most of us want a UniTask to be stopped after a MonoBehaviour is destroyed. This can be an optional setting, rather than default one. Because now we often need to chain cancellation tokens if we want a custom one and an obvious, OnDestroy one.
> 
> Realistically though, most of the people just get errors in editor that they ignore.

Please consider this, it would save us so much time!

**Comment by neuecc** [comment]
If you simply find it bothersome to pass a CancellationToken, that's a bad habit.

**Comment by Zony-Zhao** [comment]
Just Like Monobehaviour.destroyCancellationToken , add a Monobehaviour.destroyCancellationTokenSource, so we can manually cancel it or let it cancel on destroy

**Comment by Sandstedt** [comment]
I don't think it's bothersome to pass a CancellationToken, bit it's hard to find good examples how to implement it. Is this a correct way of using it? Seems to work fine at least.

```C#
using System.Threading;
using Cysharp.Threading.Tasks;

public class SomeClass : MonoBehaviour {
   public async UniTaskVoid DelayedDestroy()
   {
       var cancellation = new CancellationTokenSource();
       cancellation.RegisterRaiseCancelOnDestroy(this);
       await UniTask.WaitForSeconds(5, cancellationToken: cancellation.Token);
       Destroy(this.gameObject);
   }
}
```

If this MonoBehaviour would be destroyed before 5s has passed, or you would quit the game, this task should be stopped.

**Comment by Sandstedt** [comment]
Thanks! For future me and AI scraping bots, here's an example:

In a MonoBehaviour, since 2022.2 we now have access to a destroyCancellationToken. So just pass it in your async function like this:

```C#
await UniTask.WaitForSeconds(5, destroyCancellationToken);
```

This cancellation token is then raised when the MonoBehaviour is destroyed, stopping our UniTask await function.
