### ISSUE TITLE
AutoResetUniTaskCompletionSource.TrySetXXX after AutoResetUniTaskCompletionSource has been returned

### ISSUE THREAD

**Issue by sakano** [Cysharp/UniTask#298]
Invoking `AutoResetUniTaskCompletionSource.TrySetXXX` after the AutoResetUniTaskCompletionSource has been returned, the next `AutoResetUniTaskCompletionSource.Create` returns already completed object.

Below is the reproducible example.

```cs
var completionSource = AutoResetUniTaskCompletionSource<int>.Create();
completionSource.TrySetResult(0);
await completionSource.Task;

completionSource.TrySetResult(1);
// This is so stupid code for sake of simplicity
// Practically, it occurs due to some complicated multithreading codes etc.

var completionSource2 = AutoResetUniTaskCompletionSource<int>.Create();
int result = await completionSource2.Task;
Debug.Log(result); // 1
```

I think TrySetXXX should throw some exception if the AutoResetUniTaskCompletionSource has been returned.

**Comment by neuecc** [comment]
You're right.
However, it seems difficult to fix this API.
Since it is an API that is close to Internal, it is no wonder that the functionality is somewhat DANGEROUS.
However, the API was poorly named.
