### ISSUE TITLE
Feature Request: CancellationTokenSource evaluates an expression

### ISSUE THREAD

**Issue by XynanXDB** [Cysharp/UniTask#299]
Hi, I noticed that the current state of CancellationTokenSource can use CancelAfter() to cancel a UniTask on timeout but it would be a big hassle to do something like - projectile with an update function with a lifetime of 2 seconds and will be cancelled upon hitting something. It would be best if we could pass in an expression to determine the cancellation.

**Comment by neuecc** [comment]
What APIs do you want to use?
However, since CancellationTokenSource is a .NET API, there may not be anything UniTask can do.

**Comment by XynanXDB** [comment]
Hi, pardon my inexperience in multithreading haha. My primary use case for
it is to start an UniTask that ticks every frame/fixed frame, that I can
start and end at my will, as this usage will be very useful when doing
update on-demand or doing update-like logic in non-MonoBehaviour.

Currently, I'm doing UniTaskAsyncEnumerable.EveryUpdate with Cancellation
to achieve what I want but the Cancellation token does not evaluate an
expression make it hard to control the lifetime of the limited update. Any
suggestions for a better implementation is much appreciated.

**Comment by neuecc** [comment]
Register(`RegisterWithoutCaptureExecutionContext` and `CancelAfter`(`CancelAfterSlim`) is not enough?
Without concrete sample code, it's hard to get an idea of what to expect.

**Comment by XynanXDB** [comment]
Hmm, I haven't tried both of them yet, I look into them first.
