### ISSUE TITLE
Awaitable DOTween sequence doesn't stop running when canceled under specific conditions

### ISSUE THREAD

**Issue by SolidAlloy** [Cysharp/UniTask#301]
Under specific conditions, a DOTween sequence is not killed and continues running even if the CancellationTokenSource is canceled.

Consider the following class:
```
public class AnimationPlayer : MonoBehaviour
{
    public async UniTaskVoid PlayAnimation(CancellationToken token)
    {
        await DOTween.Sequence().Append(transform.DOMove(Vector3.zero, 2))
            .OnUpdate(() => transform.rotation = Quaternion.identity)
            .SetLoops(-1)
            .WithCancellation(token);

        Debug.Log("completed");
    }
}
```

And a class that starts and stops the animation:
```
public class AnimationController : MonoBehaviour
{
    [SerializeField] private AnimationPlayer _animationPlayer;

    private CancellationTokenSource _source = new CancellationTokenSource();

    public void StartAnimation()
    {
        _animationPlayer.PlayAnimation(_source.Token).Forget();
    }

    public void StopAnimation()
    {
        _source.Cancel();
        Destroy(_animationPlayer);
    }
```

When animation is stopped and the component is destroyed in the same frame, DOTween will start spawning warnings about the MissingReferenceException every frame, and "completed" will never be logged.

The following conditions must be present for the error to happen:
- The animation is a sequence, not a simple tween.
- A component that will be destroyed is accessed in OnUpdate() (so that MissingReferenceException is thrown when the component is destroyed.)

If the component is destroyed the next frame after CancellationTokenSource is canceled, the tween is stopped properly:
```
public void StopAnimation()
{
    async UniTaskVoid StopAnimationAsync()
    {
        _source.Cancel();
        await UniTask.NextFrame();
        Destroy(_animationPlayer);
    }

    StopAnimationAsync().Forget();
}
```

If the tween is not awaited and is killed manually, everything is okay:
```
private Sequence _sequence;

public void PlayAnimation()
{
    _sequence = DOTween.Sequence().Append(transform.DOMove(Vector3.zero, 2))
        .OnUpdate(() => transform.rotation = Quaternion.identity)
        .SetLoops(-1);
}

private void OnDestroy()
{
    _sequence.Kill();
}
```
It does not matter where the CancellationToken is coming from. `this.GetCancellationTokenOnDestroy()` results in the same error.

**Comment by codemonkeynorth** [comment]
@SolidAlloy what happens if you add a `tweenCancelBehaviour` ?
