### ISSUE TITLE
Assembly has reference to non-existent assembly 

### ISSUE THREAD

**Issue by williamj-unity** [Cysharp/UniTask#302]
We have imported the UniTask package via an OpenUPM scoped registry but I am receiving three errors related to 
"Assembly has reference to non-existent assembly "

```
Assembly has reference to non-existent assembly 'Unity.ResourceManager' (Packages/com.cysharp.unitask/Runtime/External/Addressables/UniTask.Addressables.asmdef)

Assembly has reference to non-existent assembly 'DOTween.Modules' (Packages/com.cysharp.unitask/Runtime/External/DOTween/UniTask.DOTween.asmdef)

Assembly has reference to non-existent assembly 'Unity.TextMeshPro' (Packages/com.cysharp.unitask/Runtime/External/TextMeshPro/UniTask.TextMeshPro.asmdef)
```

We don't plan on importing those packages or assemblies and we don't want to edit the UniTask package in any way either. 

We are on unity 2018.4.10f1. Is this an issue with Unity or our project or the UniTask package?

**Comment by williamj-unity** [comment]
Oh I think asmdefs version defines are not supported on 2018.4.10f1 so that causes the issue.

**Comment by williamj-unity** [comment]
Hmm, no that's not it.  For some reason, 2019.4 doesn't throw the errors but 2018.4 does.

**Comment by neuecc** [comment]
In my research, `Unity 2018.4.13f1` support it so recommend to update `.13`.

**Comment by williamj-unity** [comment]
Yes, that was it! Thank you!
