### ISSUE TITLE
What is the difference between SubscribeAwait() and Subscribe()?

### ISSUE THREAD

**Issue by aroman** [Cysharp/UniTask#303]
```cs
 button
     .OnClickAsAsyncEnumerable()
     .SubscribeAwait(async _ => await Foo())
     .AddTo(this);
     
 button
     .OnClickAsAsyncEnumerable()
     .Subscribe(async _ => await Foo())
     .AddTo(this);
```

I do not know when I should use `SubscribeAwait()` instead of `Subscribe`. As far as I can tell they both work the same...

**Comment by neuecc** [comment]
`SubscribeAwait` wait `await Foo()`.
No new OnClick will be received until the `Foo` is complete.

`Subscribe` does not wait `await Foo()`.
It will receive a new OnClick even if the Foo is not completed asynchronously.

**Comment by aroman** [comment]
thank you very much
