### ISSUE TITLE
Why does 'UnityWebRequest / SendWebRequest' throw an exception on failure?

### ISSUE THREAD

**Issue by develax** [Cysharp/UniTask#304]
Original `UnityWebRequest` version is designed to [check `request.result` against `UnityWebRequest.Result.Success`](https://docs.unity3d.com/Manual/UnityWebRequest-RetrievingTextBinaryData.html) and allows to decide how to treat an error (as an expected error or an exceptional situation). 

I believe that if a library adds support for "async/await" to already existing classes, it should do what the word "add" means - just add or extend them, rather than change their behavior. Many projects are written with the idea that only really exceptional situations should be considered as exceptions, and others are just errors after which the application can still continue to work. It's a fairly common idea to use exceptions sparingly. 

I hope you could reconsider this in your library so that it would return `UnityWebRequest` or `UnityWebRequest.Result.Success` instead of throwing an exception, or you could at least make it possible to use it with its original behavior as an option.

**Comment by neuecc** [comment]
The reason why UnityWebRequest uses Result is probably because of the limitation of yield return.
Treating errors as exceptions is a general idea in C#, not just async/await.

**Comment by develax** [comment]
No, it's not a general idea in C#.

**Best practices for exceptions**
https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions

Quotes:
![image](https://user-images.githubusercontent.com/13222593/126978118-c3c29630-82a1-4db2-a93b-1f24e645bddd.png)
![image](https://user-images.githubusercontent.com/13222593/126978161-ddb4abd9-8faa-4b0d-8c1f-a9f5687a0a25.png)

1. Returning error is much cheaper than throwing an exception, especially when operations are performed in a huge number.
2. Doesn't **throwing exceptions cause heap memory allocation** which we try to avoid in the first place using UniTask library?

It's up to the project developers to chose which strategy is better for their project and a library shouldn't incline them.

**Comment by neuecc** [comment]
Are you sure you are reading the sentence correctly?
Handle common condition is a pre-condition check.
In the case of UnityWebRequest, you don't know until you execute it, so it doesn't apply to that.
What we're talking about here is more like checking for error codes (postconditions).
It is common practice to use exceptions in that case.

Also, a UnityWebRequest request is not a huge number of operation.
Do you want to communicate thousands of times per frame?
I don't think so.
And the probability of communication failure is very high?
Then your code is wrong in the first place.

Your technical skills are not at the level to discuss this.

**Comment by 0kk470** [comment]
> No, it's not a general idea in C#.
> 
> **Best practices for exceptions** https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions
> 
> Quotes: ![image](https://user-images.githubusercontent.com/13222593/126978118-c3c29630-82a1-4db2-a93b-1f24e645bddd.png) ![image](https://user-images.githubusercontent.com/13222593/126978161-ddb4abd9-8faa-4b0d-8c1f-a9f5687a0a25.png)
> 
> 1. Returning error is much cheaper than throwing an exception, especially when operations are performed in a huge number. In this case negative results are usually threated as a result of the operation (not an exceptional situation).
> 2. Doesn't **throwing exceptions cause heap memory allocation** which we try to avoid in the first place using UniTask library?
> 
> It's up to the project developers to chose which strategy is better for their project and **a library shouldn't incline them**.
> 
> And awaitable `SendWebRequest()` method still returns `UnityWebRequest` type that has fields like `.error` & `.result` what makes a developer assume that he still controls results without exceptions.

In task-based asynchronous programming, errors are typically represented by exceptions. Maybe UniTask, being a lightweight alternative to Task, follows a similar design principle: successful operations return results, and failures throw exceptions, which just provides a choice that aligns better with C# asynchronous programming practices.

But I'm also more accustomed to handling errors directly using the error codes returned by UnityWebRequest.

So I used an extension method as a non-exception choice.
```C#
        public static async UniTask SendWebRequestSafely(this UnityWebRequest request)
        {
            request.SendWebRequest();
            await UniTask.WaitUntil(() => request.isDone || request.isError);
        }
```
