### ISSUE TITLE
iOS build size up from 23mb to 52mb

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [Cysharp/UniTask#306]
Unity 2020.3.14f1
Using UniTask in the iOS project increase build size for iPhones below 11 twice.
I make two builds with and without UniTask package.

![image](https://user-images.githubusercontent.com/30652592/127183212-4fca745f-7d28-4ef0-83d7-23d7fe4cd084.png)
![image](https://user-images.githubusercontent.com/30652592/127186153-b69cce4f-7628-42a2-9f86-eefe0d0b5d19.png)

**Comment by neuecc** [comment]
Doesn't stripping reduce it to some extent during the release build?

**Comment by Goncharuk-Nikita** [comment]
In the project Stripping Level is set to Low, as Medium / High causes a problem with other libraries and stops working.

**Comment by neuecc** [comment]
For now, let's delete UniTask.Linq completely.
Also, I think it is possible to delete Triggers in UniTask.
Removing these will remove a large amount of boilerplate, which I think will help reduce the size somewhat.

**Comment by Goncharuk-Nikita** [comment]
Thanks.
At the moment I have replaced UniTask with a regular Task and I was able to reduce the size. I will try your option and accomplish your goal.

**Comment by sniperykun** [comment]
Is there a way to just use minimum Unitask? exclude Linq and Triggers?
