### ISSUE TITLE
Compilation errors on importing v2.2.5 .unitypackage in Unity 2020.3.12f1

### ISSUE THREAD

**Issue by sidhants** [Cysharp/UniTask#307]
Hi.
I just imported the latest UniTask .unitypackage (v2.2.5) into an empty Unity 2020.3.12f1 project. I am getting compilation errors when I open any script in the package in Visual Studio Editor saying "The type or namespace 'Cysharp.Threading.Tasks' does not exist (are you missing an assembly reference?)"

![image](https://user-images.githubusercontent.com/18451476/127550834-119ff1c5-a3d0-4ca5-aaea-62efdc958b40.png)

![image](https://user-images.githubusercontent.com/18451476/127550890-85402a63-968d-4ddc-89d3-ae144eaadd2f.png)

Please let me know how I can resolve this.
Thanks,
Sid

**Comment by neuecc** [comment]
I can't reproduce it.
reference is described in asmdef
https://github.com/Cysharp/UniTask/blob/master/src/UniTask/Assets/Plugins/UniTask/Editor/UniTask.Editor.asmdef#L3-L5
