### ISSUE TITLE
Please add Discussions tab to repository

### ISSUE THREAD

**Issue by KAW0** [Cysharp/UniTask#308]
The Discussions tab is a great place to ask when you have a problem with library and you know it's not a problem with it.  Adding this will avoid cluttering the Issues tab and encourage people to ask questions about just how it's works.
https://docs.github.com/en/discussions/quickstart

**Comment by neuecc** [comment]
I've opened it.
Since this will be my first time using Discussions, I may not be able to use it properly at first, but let's give it a try.
