### ISSUE TITLE
Checking status on deferred tasks starts task

### ISSUE THREAD

**Issue by FodderMK** [Cysharp/UniTask#310]
With the following code:
```csharp
private async UniTaskVoid Go()
{
    var deferredTask = UniTask.Defer(() => MyDelay(2));
    Debug.Log(deferredTask.Status);
    await MyDelay(1);
    await deferredTask;
}

private async UniTask MyDelay(int i)
{
    Debug.Log("Starting delay " + i);
    await UniTask.Delay(1000);
    Debug.Log("Ending delay " + i);
}
```

I was expecting the result 
```
Pending
Starting delay 1
Ending delay 1
Starting delay 2
Ending delay 2
```

but what I actually get is
```
Starting delay 2
Pending
Starting delay 1
Ending delay 2
Ending delay 1
```

If I remove the line `Debug.Log(deferredTask.Status);` then it does produce the expected result.  Is the behaviour I'm seeing intended or is this a bug?

**Comment by neuecc** [comment]
Defer's factory will be called when Status is called.
It is not recommended to call Status directly.
Is there a reason you want to do so?

**Comment by FodderMK** [comment]
I have a flow where I want a single task to be running.  If another task is initiated while a task is already running then I want to queue it to run later.    If multiple tasks are initiated while a task is already running then I only care about the newest task.  If no tasks come in while a task is already running then there is no action to take.  I'm thinking of it as similar to how Throttle works.  I thought I could store a pending task and at a later time see if there's a pending task to be executed by checking the status; if the status was anything other than Pending I would know not to run it.

It does feel a bit counter-intutive that checking the status of a task would also start the task, but it sounds like that's the intendended behaviour so I'll probably just queue the arguments and create the task when needed.

**Comment by neuecc** [comment]
when await called, compiler calls 

```csharp
if(task.GetStatus()) // call factory func and check inner task's status
{
    task.GetResult()
}
else
{
    task.OnCompleted(register_callback);
}
```

so factory's generate timing is GetStatus.

**Comment by FodderMK** [comment]
Understood.  Thanks for looking into it!
