### ISSUE TITLE
How to use an Action as a parameter in UniTask?

### ISSUE THREAD

**Issue by juhaelee** [Cysharp/UniTask#312]
I am trying to do have a callback on a progress to update UI from a different class:

AssetManager.cs
```c#
    public async UniTaskVoid DownloadAssets(Action<float> onLoad)
    {
        Addressables.ClearDependencyCacheAsync("default");

        var downloadSize = await Addressables.GetDownloadSizeAsync("default");

        if (downloadSize > 0)
        {
            await Addressables
                .DownloadDependenciesAsync("default", autoReleaseHandle: true)
                .ToUniTask(Progress.Create<float>(percent => onLoad(percent)));
        }
    }
```

OtherClass.cs
```c#
    async UniTaskVoid DownloadAssets()
    {
        Debug.Log("starting download");
        _progress = 0f;
        await AssetManager.Instance.DownloadAssets((float x ) => _progress = x); // error being thrown here
        Debug.Log("download complete");
        _progress = 1.0f;
    }
```

However, I end up getting the following error in my `OtherClass.cs` file:
`
CS0315: The type 'Cysharp.Threading.Tasks.UniTaskVoid' cannot be used as type parameter 'T' in the generic type or method 'EnumeratorAsyncExtensions.GetAwaiter<T>(T)'. There is no boxing conversion from 'Cysharp.Threading.Tasks.UniTaskVoid' to 'System.Collections.IEnumerator'.
`

How would I go about doing something like this?

**Comment by neuecc** [comment]
UniTaskVoid can not await.
If you want to await method, use `UniTask` instead.
`public async UniTask DownloadAssets(Action<float> onLoad)` will work.
