### ISSUE TITLE
Add a custom linter rule for yield on UnitTask 

### ISSUE THREAD

**Issue by Baccanno** [Cysharp/UniTask#314]
I faced the issue quite often in my unity tests :

This will not yield 
```c#
//Should probably warn "yield on Task or UniTask will not await completion. Use ToCoroutine()"
yield return myStandardCShaprTask; 
yield return myStandardCShaprTask.AsUniTask(); 

```

This will yield effectively until task completion
```c#
yield return myStandardCShaprTask.AsUniTask().ToCoroutine();
```

However it's pretty hard to debug. I feel there should be a linter rule that flags a warning.
Rules can be added through : https://docs.unity3d.com/2020.2/Documentation/Manual/roslyn-analyzers.html

**Comment by neuecc** [comment]
I've just added analyzer project for UniTask,
https://github.com/Cysharp/UniTask/tree/master/src/UniTask.Analyzer
I'm interested in adding a Rule to detect it.
Thanks.

**Comment by Baccanno** [comment]
That is very great. Looking forward to it
