### ISSUE TITLE
Exceptions are never reported when UniTask is executed without await and Forget()

### ISSUE THREAD

**Issue by SolidAlloy** [Cysharp/UniTask#315]
An exception that happens inside a UniTask is never reported, not even after **GC.Collect**, under specific conditions:
- the UniTask method is run without `await` and `Forget()`
- the exception is thrown in the same frame the UniTask is launched

An example:
```
public class TestBehaviour : MonoBehaviour
{
    private void Awake()
    {
        TestAsync();
    }

    private async UniTask TestAsync()
    {
        throw new Exception();
    }
}
```

The exception will not be logged to the console even if I press **GC.Collect** in the UniTask Tracker window.
However, if the exception is thrown in subsequent frames, everything is fine:
```
private async UniTask TestAsync()
{
    await UniTask.NextFrame();
    throw new Exception(); // logged after GC.Collect
}
```

The bug is unlikely to happen because usually there is a CS4014 warning that warns us the call is not awaited. However, when using async methods through interfaces, the warning is not reported, so you can forget to use either `await` or `Forget()`:
```
public interface ITestInterface
{
    UniTask Test();
}

public class TestClass : ITestInterface
{
    public async UniTask Test()
    {
        throw new Exception();
    }
}

public class TestBehaviour : MonoBehaviour
{
    private void Awake()
    {
        ITestInterface interfaceInstance = new TestClass();
        interfaceInstance.Test(); // There is no CS4014 warning because there is no async keyword in the interface declaration.
    }
}
```

So when you forget to put `await` or `Forget()` in such a case, it is a very big pain to debug it later because there is no sign of what went wrong.

**Comment by neuecc** [comment]
How about after Destroying TestBehaviour?
It may be that the StateMachine reference generated by async/await is still in TestBehaviour.

**Comment by SolidAlloy** [comment]
Destroying TestBehaviour doesn't help, unfortunately, not even destroying the game object it is in

**Comment by neuecc** [comment]
Thanks.
You are correct, I'm sorry to didn't investigate.
It would be better to change the `Exception ex;` field to `ExceptionHolder`.
