### ISSUE TITLE
Request: Remove or fix `UniTask.WaitForEndOfFrame`

### ISSUE THREAD

**Issue by rhys-vdw** [Cysharp/UniTask#316]
From README:

> await UniTask.WaitForEndOfFrame() is not equivalent to coroutine's yield return new WaitForEndOfFrame(). Coroutine's WaitForEndOfFrame seems to run after the PlayerLoop is done. Some methods that require coroutine's end of frame(ScreenCapture.CaptureScreenshotAsTexture, CommandBuffer, etc) do not work correctly when replaced with async/await. In these cases, use a coroutine instead.

This caused huge problems for us, as we had assumed that UniTask methods are one-to-one equivalents to Unity's. Given that Unity's `WaitForEndOfFrame` exists primarily to serve `ScreenCapture.CaptureScreenshotAsTexture` etc. it is almost guaranteed to cause confusion. In our case `CaptureScreenshotAsTexture` was failing silently on certain platforms, just creating grey textures.

Is it not possible to have a coroutine run in the background that called `yield WaitForEndOfFrame()` and then continues the async function containing user code? If not then I suggest this method is deprecated and then either renamed or removed completely.

**Comment by neuecc** [comment]
That's right.
When I first introduced this method, I mistakenly thought it was equivalent.
Now that I know it is not, I should not include it.
I would like to add a Deprecated guide.

**Comment by rhys-vdw** [comment]
You can add [ObseleteAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?view=net-5.0) so that it warns anyone who tries to use it without being a breaking change.

**Comment by rhys-vdw** [comment]
@neuecc I am curious why you can't support a continuation from `WaitForEndOfFrame` though? Do you not run a coroutine in the background? I haven't looked into how it all works.

**Comment by neuecc** [comment]
UniTask is run on PlayerLoop, not coroutine.
Coroutine requires specified MonoBehaviour as runner, so can not simulate it.

**Comment by rhys-vdw** [comment]
> Coroutine requires specified MonoBehaviour as runner, so can not simulate it.

You can do this actually, although it might require some changes. Basically you create an object at runtime ([you can hide it in the editor](https://docs.unity3d.com/ScriptReference/HideFlags.html)) and have it run a single coroutine that fires callbacks every frame.

I do something like this to convert PUN messages to callbacks in one of our games using this [lazy singleton pattern](https://gist.github.com/rhys-vdw/f6aef9b819f642890f796b045cbe2702) (you could set hide flags there). Then you'd basically expose a bunch of delegates on it.

Something like this:

```cs
class CoroutineRunner : LazySingleton<CoroutineRunner> {
  public Action WaitForEndOfFrame;
  
  // cache to avoid heap allocations.
  static readonly WaitForEndOfFrame  _waitForEndOfFrame = new WaitForEndOfFrame();
  
  IEnumerator Start() {
    while (true) {
      yield return _waitForEndOfFrame;
      // main async runner waits for this callback
      WaitForEndOfFrame?.Invoke();
    }
  }
}
```

I'm not familiar with UniSharp source, but I had assumed you were using a pattern like this for everything.

**Comment by neuecc** [comment]
I've been working with the UniRx implementation, so I understand.
In UniTask, the principle is to make it MonoBehaviour free, so we will not include such an implementation.

**Comment by rhys-vdw** [comment]
> In UniTask, the principle is to make it MonoBehaviour free, so we will not include such an implementation.

Reasonable. Perhaps we could petition Unity to add a callback for this event.

**Comment by rhys-vdw** [comment]
@neuecc request that this issue is not closed.

**Comment by neuecc** [comment]
I've add `UniTask.WaitForEndOfFrame(MonoBehaviour)`, it reuse task and coroutine so more lightweight than standard coroutine.
It will release soon.

**Comment by rhys-vdw** [comment]
Great solution, thanks @neuecc.
