### ISSUE TITLE
ContinueWith() extension does not continue after exception

### ISSUE THREAD

**Issue by iliaJelly** [Cysharp/UniTask#318]
Hi.

In C# Tasks, the ContinueWith continues regardless if the Task has finished or has thrown an exception.
https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcontinuationoptions?view=net-5.0
There are also options to configure the behaviour of this functionality.

In UniTasks, the ContinueWith is not replicating the default behaviour of c#. And instead it continues only if the task succeded.
https://github.com/Cysharp/UniTask/blob/master/src/UniTask/Assets/Plugins/UniTask/Runtime/UniTaskExtensions.cs#L712

Are we planning to change this?

I would prefer to replicate the default c# behaviour. + to add the similar functionality to optionally configure the continue with.

**Comment by neuecc** [comment]
UniTask is close to ValueTask, so it is not possible to simulate as Task.
Also, since ContinueWith is an API before async/await, it is better to use async/await whenever possible.
