### ISSUE TITLE
The thread before awaiting UniTask may not match with the thread after awaiting 

### ISSUE THREAD

**Issue by imixal** [Cysharp/UniTask#319]
According to documentation "_UniTask bypasses SynchronizationContext(and ExecutionContext) so it does not use it_". So UniTask always works like Task.ConfigureAwait(false) and not guaranteed that the thread before awaiting UniTask may not match with the thread after awaiting. It's unexpected behavior if you worked with Task early.

Do you plan to add any possibilities to run UniTask without bypasses SynchronizationContext?

**Comment by neuecc** [comment]
UniTask bypasses SynchronizationContext, but almost everything is driven directly by PlayerLoop.
Task needs a SynchronizationContext because it uses Thread, but UniTask doesn't need one.

**Comment by imixal** [comment]
Let see an example: 

    public static async UniTask TestUniTask()
    {
        await UniTask.SwitchToThreadPool();
        Debug.Log($"Thread In UniTask {Thread.CurrentThread.ManagedThreadId}");
    }
    
    public static async Task TestTask()
    {
        await UniTask.SwitchToThreadPool();
        Debug.Log($"Thread In Task {Thread.CurrentThread.ManagedThreadId}");
    }


![image](https://user-images.githubusercontent.com/18143518/134154259-1a1e7be3-3957-4177-8a11-3cf599a758a8.png)

From my point of view for the mental model of the written code - it's very important

**Comment by neuecc** [comment]
In UniTask, SwitchToThreadPool does not write frequently.
Task uses thread implicitly so requires implicitly return main-thread mechanism.
However UniTask explicitly switch thread, so you should explicitly return main-thread.

**Comment by imixal** [comment]
Ok, but what do you think about adding behavior like in Task? If I'm not mistaken, you are not using SynchronizationContext in order to avoid overheads. But It's really will be useful to have a possibility run task don't mind about the thread after. How about adding uniTask.ConfigureAwait(true) like you are doing in UniTask.Run(configureAwait: true ...) ?

**Comment by neuecc** [comment]
You probably don't use UniTask at all, and don't understand anything about it.
First of all, use it.

**Comment by imixal** [comment]
I've just wanted to avoid exceptions when you run Unitask in another thread and make a UnityApi call (from not the main thread) after await.

Sorry, If I hurt your feelings.
