### ISSUE TITLE
Operations wait indefinitely (until scene close) after UniRx import

### ISSUE THREAD

**Issue by lmaxsmith** [Cysharp/UniTask#320]
I built my app on UniTask and recently brought in UniRx as a dependency for other new plugins. Suddenly parts of my app were failing to finish without throwing exceptions. I noticed that the break points I set were being hit when I stopped playmode. 

I narrowed down the point the code reached to an await `Unitask.NextFrame();` and never continued until scene close. 

Is this some kind of conflict with both plugins being included in the same project? Is there a recommended fix?

**Comment by neuecc** [comment]
If it is a crash, are you on the crash report?
If you have an older version of UniRx, you may still have the old UniTask (UniRx.Async).
Otherwise, there shouldn't be any conflicts.

**Comment by lmaxsmith** [comment]
Update: I was using a current Unitask but an old UniRx. When I updated UniRx, everything started working again. Thanks!
