### ISSUE TITLE
Unity issue resolved - bug in Il2CPP VM

### ISSUE THREAD

**Issue by NuclearCookie** [Cysharp/UniTask#321]
Hello,
I wanted to give a headsup that the unity bug https://issuetracker.unity3d.com/issues/il2cpp-incorrect-results-when-calling-a-method-from-outside-class-in-a-struct has been fixed in LTS 2020.3.20f1.
You have a comment here https://github.com/Cysharp/UniTask/blob/master/src/UniTask/Assets/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs about a workaround related to this bug.

Cheers!

**Comment by timcassell** [comment]
It's rather unfortunate that they fixed it in such a late patch of the LTS version, and don't provide OR_NEWER define symbols for minor versions.

In any case, I think this should do it (untested):

```cs
#undef OPTIMIZED_ASYNC_MODE

#if UNITY_2021_1_24 || UNITY_2021_1_25 || UNITY_2021_1_26 || UNITY_2021_1_27 || UNITY_2021_1_28 || UNITY_2021_2_OR_NEWER || (UNITY_2020_3_OR_NEWER && !UNITY_2021_OR_NEWER)
#define OPTIMIZED_ASYNC_MODE
#endif
#if UNITY_2020_3_0 || UNITY_2020_3_1 || UNITY_2020_3_2 || UNITY_2020_3_3 || UNITY_2020_3_4 || UNITY_2020_3_5 || UNITY_2020_3_6 || UNITY_2020_3_7 || UNITY_2020_3_8 || UNITY_2020_3_9
#undef OPTIMIZED_ASYNC_MODE
#endif
#if UNITY_2020_3_10 || UNITY_2020_3_11 || UNITY_2020_3_12 || UNITY_2020_3_13 || UNITY_2020_3_14 || UNITY_2020_3_15 || UNITY_2020_3_16 || UNITY_2020_3_17 || UNITY_2020_3_18 || UNITY_2020_3_19
#undef OPTIMIZED_ASYNC_MODE
#endif

#if !ENABLE_IL2CPP
#define OPTIMIZED_ASYNC_MODE
#endif
```

```
#if !OPTIMIZED_ASYNC_MODE
...
#endif
```

**Comment by akeit0** [comment]
@neuecc 
I think this issue should be addressed.
