### ISSUE TITLE
Leaving play mode while awaiting a task still runs the task

### ISSUE THREAD

**Issue by Andy-Weber-iicorporate** [Cysharp/UniTask#326]
I may have misunderstood, but I thought one of the bonuses of this package was because when you await a task and leave playmode in unity it will still run the task. 
So I Installed this package and replaced my awaits, but it still seems to run my addressable asset loading after leaving play mode.
I am simply importing the using statment and awaiting the AsyncOperation
`var obj= await Addressables.InstantiateAsync(key, parent);`

**Comment by frostebite** [comment]
@neuecc ?

**Comment by neuecc** [comment]
Leaving PlayMode will stop the PlayerLoop of UniTask (it will no longer drive the await).
Some AsyncOperations are driven from their own callbacks (and work differently than UniTask's PlayerLoop), so they will sometimes run as is and sometimes stop.
