### ISSUE TITLE
UniTask.Run does nothing in WebGL

### ISSUE THREAD

**Issue by kameninc** [Cysharp/UniTask#328]
I have the following code:

```
UniTask.Run(SomeFunc);

async SomeFunc() {
...
}
```

For some reason SomeFunc does not get called at all when running in WebGL, in the Editor it works fine. Any hints why that might be?

**Comment by kameninc** [comment]
To answer my own questions, threading is not support on WebGL, so there I should use only StartCoroutine(UniTask.ToCouroutine(SomeFunc)) in order to run it?

**Comment by neuecc** [comment]
don't need Run.

```csharp
await SomeFunc();

async UniTask SomeFunc() { }
```
