### ISSUE TITLE
How do you pass parameter types to a "UniTask.Action"?

### ISSUE THREAD

**Issue by danielmahon** [Cysharp/UniTask#329]
How do you pass parameter types to a "UniTask.Action"?

```cs
  void OnEnable() {
    _loadSceneEvent.Register(UniTask.Action(OnLoadScene)); // this doesnt work, need to use regular "async void" callback or delegate with no parameters
  }

  async UniTaskVoid OnLoadScene(GameScene gameScene) {
    await LoadScene(gameScene);
  }
```

**Comment by danielmahon** [comment]
Is this possible or am I missing something simple?

**Comment by danielmahon** [comment]
@neuecc before you close this for good, is there a solution or how would you recommend using an `Action<T>` delegate with a parameter with UniTask?

**Comment by danielmahon** [comment]
Would you accept a pull request with adding the 16 (I think) generic overrides?
```cs
public static Action<T> Action(Func<T, UniTaskVoid> asyncAction) {
    return (t1) => asyncAction(t1).Forget();
}
public static Action<T, T> Action(Func<T, T, UniTaskVoid> asyncAction) {
    return (t1, t2) => asyncAction(t1, t2).Forget();
}
```

**Comment by danielmahon** [comment]
nevermind, I'm an idiot, I can just include the overrides in my own project... I did not think that through the last time I tried to use it

**Comment by neuecc** [comment]
Could you use lambda?

```csharp
_loadSceneEvent.Register(UniTask.Action(async () => OnLoadScene(scene)))
```

**Comment by danielmahon** [comment]
Not with `UniTask.Action` because it doesn't support returning an `Action<T>` delegate.
In your example, where are you getting `scene` from? It would need to be the following which doesn't work as is.
```cs
_loadSceneEvent.Register(UniTask.Action(async (scene) => OnLoadScene(scene))) // not supported
```
but I could just use my own helper class:

```cs
public static class UniTaskHelper {

  public static Action<T> Action(Func<T, UniTaskVoid> asyncAction) {
    return (t1) => asyncAction(t1).Forget();
  }

}
```
then it would work
```cs
_loadSceneEvent.Register(UniTaskHelper.Action(async (scene) => OnLoadScene(scene)))
```
Maybe it still makes sense to support the overrides in the library though? Seems like a pretty common pattern... 🤷 

The only downside is that I typically unsubscribe from these events too... so using anonymous functions (lambdas) isn't suggested because you're not keeping a single reference to subscribe/unsubscribe:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events#to-subscribe-to-events-by-using-an-anonymous-function

Is something like this possible?
```cs
  void OnEnable() {
    _loadSceneEvent.Register(OnLoadScene);
  }

  // new UniTaskAction<T> type
  async UniTaskAction OnLoadScene(GameScene gameScene) {
    await LoadScene(gameScene);
  }
```

**Comment by neuecc** [comment]
Oh, I see.
Well, I don't know what _loadSceneEvent is, but it is not UniTask issue.

**Comment by danielmahon** [comment]
Sorry, yea I just realized I put the `Register` method in the example instead of the event
```cs
  void OnEnable() {
    _loadSceneEvent.OnChanged += OnLoadScene;
  }
  ```

**Comment by danielmahon** [comment]
OK, I was completely overthinking this, I just need to store a reference to the action returned by my `UniTaskHelper.Action` for proper unsubscribing. I should really go to bed early 😬 
I do think adding the generic overrides into UniTask would be useful, but that's up to you. Thank you for your time.
```cs

  public static class UniTaskHelper {
    public static Action<T> Action<T>(Func<T, UniTaskVoid> asyncAction) {
      return (t1) => asyncAction(t1).Forget();
    }
  }

    Action<GameScene> _fooAction;

    void Awake() {
      _fooAction = UniTaskHelper.Action<GameScene>(OnSceneReady);
    }

    void OnEnable() {
      _sceneReadyEvent += _fooAction;
    }

    void OnDisable() {
      _sceneReadyEvent -= _fooAction;
    }
    
    async UniTaskVoid OnSceneReady(GameScene scene) {
      _logger.Info("Scene ready: " + scene);
      // await something
      await UniTask.Yield();
    }

```

**Comment by zrp2016** [comment]
> OK, I was completely overthinking this, I just need to store a reference to the action returned by my `UniTaskHelper.Action` for proper unsubscribing. I should really go to bed early 😬 I do think adding the generic overrides into UniTask would be useful, but that's up to you. Thank you for your time.
> 
> ```cs
>   public static class UniTaskHelper {
>     public static Action<T> Action<T>(Func<T, UniTaskVoid> asyncAction) {
>       return (t1) => asyncAction(t1).Forget();
>     }
>   }
> 
>     Action<GameScene> _fooAction;
> 
>     void Awake() {
>       _fooAction = UniTaskHelper.Action<GameScene>(OnSceneReady);
>     }
> 
>     void OnEnable() {
>       _sceneReadyEvent += _fooAction;
>     }
> 
>     void OnDisable() {
>       _sceneReadyEvent -= _fooAction;
>     }
>     
>     async UniTaskVoid OnSceneReady(GameScene scene) {
>       _logger.Info("Scene ready: " + scene);
>       // await something
>       await UniTask.Yield();
>     }
> ```

I think its necessa too
