### ISSUE TITLE
Can I use UniTask outisde of Unity, in standalone library for tests?

### ISSUE THREAD

**Issue by mkrzaczek** [Cysharp/UniTask#33]
As in the title. I want to create a DLL (.NET library) and use it outside of Unity. The potential use cases are unit testing and using this library on a backend server, without Unity.
Is this something that is supported out of the box? Or can I at least make it work without too much hassle? 
Thanks!

**Comment by neuecc** [comment]
Support is not realistic because it uses many Unity-dependent APIs such as PlayerLoop.
It is recommended to use Task or ValueTask for the shared part.

**Comment by jeffward01** [comment]
Sorry to revive this after such a long time. Do you know of any `non-unity dependent` alternatives where we can achieve the same?

I read your super excellent blog post here: https://neuecc.medium.com/patterns-practices-for-efficiently-handling-c-async-await-cancel-processing-and-timeouts-b419ce5f69a4 and was looking for some libraries to help implement the pattern you presented without re-inventing the wheel.

----

Side note:

I very much appreciate your libraries! You write some of the best, and most high performant code in the entire C# realm.  I have been a long time fan of your work and your team `Cysharp` -- thank you very much for everything.
