### ISSUE TITLE
Getting exception from UniTask

### ISSUE THREAD

**Issue by adozzer** [Cysharp/UniTask#335]
With a regular Task it is [possible](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.exception?view=net-6.0) to get an Exception from the Task itself.
It may be useful to distinguish tasks in aggregated methods, e.g.
```c#
var task = Task.WhenAll(tasks);

try
{
    var results = await task;
}
catch (Exception ex)
{
    if (tasks[0].Exception != null){
        // We know, it was 0 task which caused failure, thus we behave accordingly
    }
}
```
Can a similar functionality be achieved with UniTask? How can I get an Exception from UniTask? How can I tell, which task threw an Exception?

**Comment by neuecc** [comment]
no supports it.
