### ISSUE TITLE
Compilation error with Firebase Unity SDK 8.8.0

### ISSUE THREAD

**Issue by nodchip** [Cysharp/UniTask#339]
A compilation error occurred with Firebase Unity SDK 8.8.0.

The code is below.
```
using Cysharp.Threading.Tasks;
using UnityEngine;

public class OnStartupLoaded : MonoBehaviour
{
	async void Start()
	{
		await Firebase.FirebaseApp.CheckAndFixDependenciesAsync();
	}
}
```

The compile error message is below.
`error CS0311: 型 'System.Threading.Tasks.Task<Firebase.DependencyStatus>' はジェネリック型またはメソッド 'EnumeratorAsyncExtensions.GetAwaiter<T>(T)' 内で型パラメーター 'T' として使用できません。'System.Threading.Tasks.Task<Firebase.DependencyStatus>' から 'System.Collections.IEnumerator' への暗黙的な参照変換がありません。
`

The environment is below:
- Unity Hub 3.0.1
- Unity 2020.3.12f1
- Visual Studio 2022 17.1.0
- Firebase Unity SDK 8.8.0
- UniTask 2.2.5

~~Compilation succeeded with Firebase Unity SDK 8.1.0.~~ Also a compile error occurred.

Could you please take a look?

Thanks,

**Comment by neuecc** [comment]
Firebase includes Task compatible SDK?
If so please check and remove dlls.

**Comment by nodchip** [comment]
Thank you for the advice.  I removed 

- Assets/Parse/Plugins/Unity.Compat.dll
- Assets/Parse/Plugins/Unity.Compat.dll.meta
- Assets/Parse/Plugins/Unity.Tasks.dll
- Assets/Parse/Plugins/Unity.Tasks.dll.meta

, and compile errors are resolved.
