### ISSUE TITLE
No Delay method in await UniTask

### ISSUE THREAD

**Issue by Atmosferrum** [Cysharp/UniTask#341]
I was trying to use UniTask in my Unity project, but I stumbled upon 2 problems: 
- After adding UniTask package in my Unity project the Cysharp.Threading.Tasks cannot be found, so I download UniTask through nuget packages, and it kinnda solved problem but :
- I was trying to use "await UniTask.Delay(TimeSpan.FromSeconds(10), ignoreTimeScale: false);" but got the error : Error	CS0117 UniTask' does not contain a definition for 'Delay'.
I'm using Unity 2020.3.25f1, VS Community 2022.

**Comment by neuecc** [comment]
I can't reproduce.

**Comment by AntonPetrov83** [comment]
The same, used NuGet for Unity to install UniTask 2.5.3:
```
UIDialogue.cs(37,31): error CS0117: 'UniTask' does not contain a definition for 'Delay'
```

**Comment by neuecc** [comment]
Ah, I understand. When using UniTask in Unity, please do not install it from NuGet.
