### ISSUE TITLE
In webgl, if the browser loses focus(e.g. switching to other application), UniTask.Delay is not working 

### ISSUE THREAD

**Issue by zhengyi73** [Cysharp/UniTask#342]

**Comment by neuecc** [comment]
You can pass DelayType.
Default(DeltaTime) is affected timescale, unity's running state.
`DelayType.Realtime` uses realtime seconds.

**Comment by zhengyi73** [comment]
Add the DelayType.Realtime parameter, like: await UniTask.Delay(timeoutMSec, DelayType.Realtime);
but it is still the same, switching to other tab or app causes the problem.

**Comment by neuecc** [comment]
It does not move while PlayerLoop is stopped, we are talking about time progression when the focus is shifted again.
