### ISSUE TITLE
UniTask Ver 2.3.1のUnity packageからウイルスが検出される

### ISSUE THREAD

**Issue by pepoipod** [Cysharp/UniTask#343]
Unitask Ver.2.3.1
windows10
Google Chrome バージョン: 98.0.4758.102（Official Build） （64 ビット）

1. https://github.com/Cysharp/UniTask/releases/tag/2.3.1 より[UniTask.2.3.1.unitypackage](https://github.com/Cysharp/UniTask/releases/download/2.3.1/UniTask.2.3.1.unitypackage)をクリックし、ダウンロードを試みる
2. Chromeのダウンロード結果に、「失敗 - ウイルスを検出しました」と表示される

このような事態が発生します。
Microsoft Defenderには「Trojan:HTML/Phish.ST!MTB」が検出されたと表示されています。
ご確認お願いいたします。

![SnapCrab_NoName_2022-3-4_14-6-58_No-00](https://user-images.githubusercontent.com/9960464/156704307-bfcadb61-fb69-44bd-b4c5-f1fc04f3b54e.png)
![SnapCrab_NoName_2022-3-4_14-6-39_No-00](https://user-images.githubusercontent.com/9960464/156704312-1ac45ca2-3016-4bbd-9522-ee3a5526ed0b.png)

**Comment by neuecc** [comment]
こちら複数の環境で確認してみましたが、検出されたケースはありませんでした。

**Comment by pepoipod** [comment]
すみません、ご確認ありがとうございます。
となりますと、こちらのPCの問題の可能性が高いのでこちら閉じさせていただきます…
お騒がせしました………申し訳ございません
