### ISSUE TITLE
is it possible to update UniTask manually? Custom player loop

### ISSUE THREAD

**Issue by Romaleks360** [Cysharp/UniTask#345]
We are using UniTask with the Photon Fusion multiplayer library. It features a custom update loop callback called FixedUpdateNetwork(), which runs at the fixed server tickrate. It is required to change the game state inside this callback. 

Is it possible to run UniTasks on the custom loop like this? Probably extending the PlayerLoopTiming?

DOTween, for example, has this static ManualUpdate method for tweens that were created with UpdateType.Manual. I am looking for something similar.

Thanks!

**Comment by sableangle** [comment]
Also wondering about this possibility.
