### ISSUE TITLE
EditorMode : MainLoop suspended on WaitForEndOfFrame or DelayFrame after Debug.LogError

### ISSUE THREAD

**Issue by eplesse** [Cysharp/UniTask#346]
In release 2.3.1. 
It seems that when launched from editor, a script logging an error within an async method then making subsequent call to UniTask.WaitForEndOfFrame(this), UniTask.WaitForFixedUpdate() or UniTask.DelayFrame() will suspend script MainLoop.

Steps to reproduce:

* Attach follwing Monobehaviour on an empty gameobject in scene:

```
using Cysharp.Threading.Tasks;
using UnityEngine;

public class UniTaskLoopSuspendOnError : MonoBehaviour
{
    public bool useDelayFrame = false;
    public bool useError = true;

    async void Start()
    {
        await LogOrWarningLoop();
    }

    async UniTask LogOrWarningLoop()
    {
        while(true)
        {
            if (useError)
                Debug.LogError("error in loop");
            else
                Debug.LogWarning("warning in lopp");
            if (!useDelayFrame)
                await UniTask.WaitForEndOfFrame(this);
            else
                await UniTask.DelayFrame(100);
        }
    }
}
```
* select Delay mode and log type
* click on "Play"

What is observed:
* no matter the delay mode, if log type is error, MainLoop suspends after first Wait or Delay
* in all delay mode, loop executes if log type is a warning

Thanks for your feedback on this.
Sincerly, Emmanuel

**Comment by Lncxr** [comment]
Same issue here with task-based additive scene loading in 2021.2.19f1, at first I thought it was an issue with SynchronizationContext and had partial success with:
```
UniTask.ReturnToMainThread(this.GetCancellationTokenOnDestroy());
UniTask.ReturnToSynchronizationContext(SynchronizationContext.Current);
```

But the only fix was to completely remove any `Debug.LogError()` statements, likely something going wrong with how the library attaches to `PlayerLoop`.
