### ISSUE TITLE
DOTween ToUniTask vs WithCancellation

### ISSUE THREAD

**Issue by codemonkeynorth** [Cysharp/UniTask#348]
is there any difference between:

`await transform.DOScale(1, 1).ToUniTask(cancellationToken: token);`

and 

`await transform.DOScale(1, 1).WithCancellation(token);`

Presumably the first one can be assigned to a variable and returned ?

Thanks

**Comment by codemonkeynorth** [comment]
I see from here 

https://twitter.com/su10_dev/status/1356186330535919620?s=20&t=U_29PEjZvwqOHMKlkTbFOA

they are similar.. allowing the tween to be cancelled, with the first being preferable?

**Comment by YegorStepanov** [comment]
Press F12 :)

```C#
public static UniTask WithCancellation(this Tween tween, CancellationToken cancellationToken)
{
    Error.ThrowArgumentNullException(tween, nameof(tween));

    if (!tween.IsActive()) return UniTask.CompletedTask;
    return new UniTask(TweenConfiguredSource.Create(tween, TweenCancelBehaviour.Kill, cancellationToken, CallbackType.Kill, out var token), token);
}

 public static UniTask ToUniTask(this Tween tween, TweenCancelBehaviour tweenCancelBehaviour = TweenCancelBehaviour.Kill, CancellationToken cancellationToken = default)
{
    Error.ThrowArgumentNullException(tween, nameof(tween));

    if (!tween.IsActive()) return UniTask.CompletedTask;
    return new UniTask(TweenConfiguredSource.Create(tween, tweenCancelBehaviour, cancellationToken, CallbackType.Kill, out var token), token);
}
```

**Comment by farhnmh** [comment]
> Press F12 :)
> 
> ```cs
> public static UniTask WithCancellation(this Tween tween, CancellationToken cancellationToken)
> {
>     Error.ThrowArgumentNullException(tween, nameof(tween));
> 
>     if (!tween.IsActive()) return UniTask.CompletedTask;
>     return new UniTask(TweenConfiguredSource.Create(tween, TweenCancelBehaviour.Kill, cancellationToken, CallbackType.Kill, out var token), token);
> }
> 
>  public static UniTask ToUniTask(this Tween tween, TweenCancelBehaviour tweenCancelBehaviour = TweenCancelBehaviour.Kill, CancellationToken cancellationToken = default)
> {
>     Error.ThrowArgumentNullException(tween, nameof(tween));
> 
>     if (!tween.IsActive()) return UniTask.CompletedTask;
>     return new UniTask(TweenConfiguredSource.Create(tween, tweenCancelBehaviour, cancellationToken, CallbackType.Kill, out var token), token);
> }
> ```

where can I put this code?

**Comment by OrangeCocoa** [comment]
@farhnmh 
This just shows that the internal implementation is almost the same, so there is no need to write it.
These differences can only be specified externally using tweenCancelBehaviour.
