### ISSUE TITLE
Request for Separating Editor Scripts as Independent Plugin Scripts

### ISSUE THREAD

**Issue by hiradyazdan** [Cysharp/UniTask#35]
Hi @neuecc, 

Firs of all, great library! 

I was wondering if it would be possible for you to separate the editor scripts to their own independent directory/namespace/repository so that we can use the editor scripts inside the `Plugins` directory and manage the asmdefs on the outer scope by ourselves. 

I Understand that I can make these changes on the source myself once imported the package, but it would be nice if this is by default so we can keep up with the latest update without the need to change every time.

Thanks

**Comment by bdominguez** [comment]
It should use package layout:

https://docs.unity3d.com/Manual/cus-layout.html

**Comment by neuecc** [comment]
Thank you, your suggestion is right.
I'll try it.

**Comment by neuecc** [comment]
memo, keep opens:)

**Comment by hiradyazdan** [comment]
ah sorry :)
