### ISSUE TITLE
typo CompleteWithSeqeunceCallback 

### ISSUE THREAD

**Issue by codemonkeynorth** [Cysharp/UniTask#350]
`TweenCancelBehaviour.CompleteWithSeqeunceCallback` should be  `TweenCancelBehaviour.CompleteWithSequenceCallback`

(same for other instances of `Seqeunce`)

that is, please: replace `qeu` with `que` 

thank you

**Comment by yellowisher** [comment]
Fixed in #280

**Comment by codemonkeynorth** [comment]
thanks
