### ISSUE TITLE
DOTween: please explain difference TweenBehaviour.Complete and TweenBehaviour.CompleteAndCancelAwait

### ISSUE THREAD

**Issue by codemonkeynorth** [Cysharp/UniTask#351]
wit the following code, please explain the difference `TweenBehaviour.Complete` and `TweenBehaviour.CompleteAndCancelAwait`
```csharp
await text.DOFade(0, 0.5f)
          .OnComplete(() => isTextDisplayed = false)
          .ToUniTask(tweenCancelBehaviour: TweenCancelBehaviour.Complete, cancellationToken: cts.Token);

Debug.Log("Complete");
```

both would continue with the next line, so I'm not sure the difference?

thanks
J.

**Comment by yellowisher** [comment]
`TweenCancelBehaviour` is about how to react to `UniTask` cancellation.
If you cancel the task (via `cts.Cancel()` somewhere),
- `Complete`: call complete callback of tween
- 'CompleteAndCancelAwait': call complete callback of tween AND throw `OperationCanceledException`

**Comment by codemonkeynorth** [comment]
ah thank you! closing
