### ISSUE TITLE
Jetbrain Rider

### ISSUE THREAD

**Issue by unicomp21** [Cysharp/UniTask#352]
After adding the Cysharp package, why doesn't it who up in Jetbrains Rider for Unity?  Like all the other packages?

**Comment by ManuelRauber** [comment]
It does, as expected. Do you have any compile error?

**Comment by unicomp21** [comment]
I must be doing something wrong, just not sure what that would be.  I'm running on the latest intel macbook pro?  Same on your end?  @ManuelRauber

**Comment by ManuelRauber** [comment]
> I must be doing something wrong, just not sure what that would be. I'm running on the latest intel macbook pro? Same on your end? @ManuelRauber

M1 MacBook, but worked in Intel MacBook before with no issues.

Can you go to Unity Settings -> External Tools and check if JetBrains Rider is set a external tool? If yes, click on "Regenerate Project Files". Then check again.

**Comment by unicomp21** [comment]
maybe this is the problem, it's not showing up under external tools.  but when i click on files in unity, it opens them in rider.

**Comment by ManuelRauber** [comment]
> maybe this is the problem, it's not showing up under external tools. but when i click on files in unity, it opens them in rider.

You should fix that first. There is plenty of documentation online how to connect Unity to Rider correctly.

**Comment by unicomp21** [comment]
Got it, thanks, appreciate the help.  Quick question, how's the m1?  I'm thinking about getting an m2 mac when they come out.  I hear the performance is pretty incredible?

**Comment by ManuelRauber** [comment]
> Got it, thanks, appreciate the help. Quick question, how's the m1? I'm thinking about getting an m2 mac when they come out. I hear the performance is pretty incredible?

Go for it. 

Performance-wise its an incredible machine. 

But note, that not all Unity processes utilize M1 yet. Editor itself runs native M1, but some external processes are still Intel based. Unity itself is faster than on Intel, but there is more to come when everything runs natively on M1.

**Comment by ThunderSword99** [comment]
> > I must be doing something wrong, just not sure what that would be. I'm running on the latest intel macbook pro? Same on your end? @ManuelRauber
> 
> M1 MacBook, but worked in Intel MacBook before with no issues.
> 
> Can you go to Unity Settings -> External Tools and check if JetBrains Rider is set a external tool? If yes, click on "Regenerate Project Files". Then check again.

I have the same issue, thanks a lot.
