### ISSUE TITLE
Reentering the Update method is not allowed Exception

### ISSUE THREAD

**Issue by ymfact** [Cysharp/UniTask#353]
I got "Reentering the Update method is not allowed" exception on WaitForCompletion.

Here's a reproducible example.

```C#
await Addressables.LoadContentCatalogAsync(someValidCatalogPath);
Addressables.LoadAssetAsync<Sprite>(someValidKey).WaitForCompletion();
```

**Comment by allenz8512** [comment]
Is it possible to fix this conflict？

**Comment by foriequal0** [comment]
We could fix this by detaching the continnuation from AsyncOperationHandle.Completed callback with Yield. https://github.com/foriequal0/UniTask/commit/97e1e07e08e72d4aa244b72ee9cc7626d7130e63
