### ISSUE TITLE
How to cancel a foreach(EveryUpdate) loop?

### ISSUE THREAD

**Issue by Zony-Zhao** [Cysharp/UniTask#358]
pseudo code:
```
cts.cancel() //cancel last one(cts is a private field in  the class)
cts= new CancellationTokenSource();
await foreach (var _ in UniTaskAsyncEnumerable.EveryUpdate()){
  Do(B)
  if(A)break;
 }

```
Maybe I can add something in the loop like: ` if (cts.isCanceled()) break;`, but I'm constantly creating new cts(basiclly create new one as soon as I cancel it). I'm not sure the update playerloop would find out the cts canceled(old one), or a new cts(which is not canceled yet).
By the way, is there something like `Unitask.doUntil( ()=>Do(B),()=>CheckA(),cts.token)`? I'd be happy to accept some more natural way to implement this function, still Unitask freshman here.

**Comment by neuecc** [comment]
`UniTaskAsyncEnumerable.EveryUpdate().WithCancellation(cts.Token)`
