### ISSUE TITLE
Limiting Threads and/or Task

### ISSUE THREAD

**Issue by haitheredavid** [Cysharp/UniTask#359]
Hello! 🧇

I've been integrating UniTask into a package of mine but I've been hitting some issues with memory allocation, and I wanted to see if you could toss some knowledge my way. This might not have anything to do with UniTask, but the bit of googling hasn't helped.

I'm hitting an issue with pulling a large object down from an API. The API has a `async` helper function that does all the setup and REST calls, returning a `Task<>`. I tagged that helper function with `AsUniTask()` and that works perfectly. However, whenever I use the API function my CPU immediately hits 100% on all cores and blocks Unity until the CPU has dropped down. 

😢 
![image](https://user-images.githubusercontent.com/30870056/170573165-363f2eca-1f98-46a1-9878-4588d340fac0.png)
 
Is there a way to throttle the CPU with UniTask? The bit of digging showed that I could use `TaskPool.SetMaxThreadSize()` but that didn't seem to help any. I've replicated the same code I used for my package but filled in the API logic with `UniTask.Delay()` and that didn't cause a block with unity. I figure this most likely means that the API code needs to be handled differently, but the same code works on different clients and doesn't cause a cpu block like it does with unity.  

Here is an [example](https://github.com/sasakiassociates/speckle-unity-core/blob/da9eb0a2ca2891b743f2d471552bcce684ef6c40/Runtime/Operations/Receiver.cs#L135-L158) of how that code is setup

**Comment by neuecc** [comment]
What happens if it don't use AsUniTask?

```csharp
var commit = await client.CommitGet(
    token,
    stream.Id,
    stream.CommitId
); // .AsUniTask();

SpeckleUnity.Console.Log($"obj id ={commit.referencedObject}");

@base = await Operations.Receive(
    commit.referencedObject,
    token,
    transport
); // .AsUniTask();
```

**Comment by haitheredavid** [comment]
yeah, that fixed it! Thank you.  Still having a high CPU usage but unity doesn't get blocked by that. I thought converting a `Task` with `ToUniTask` would be the solution to heavy tasks in unity. Maybe because there is multiple `Tasks` within those API calls?

**Comment by haitheredavid** [comment]
@neuecc Bump 🤓! 

Something I was thinking is that converting a task to unitask might create overhead for large API REST calls
