### ISSUE TITLE
How to use unitask both unity and .net core side?

### ISSUE THREAD

**Issue by halleyxu** [Cysharp/UniTask#36]
we have lot of gamelogic share between unity and .net core, in the .net core side i'm try to inherit Task class as solution. but i found .net core can't return null  of Unitask but Task can..

allowed
public async Task Load(string mapName)
{
        return 
}

//not allowed , defined public class UniTask:Task
public async UniTask Load(string mapName)
{
        return 
}

is there any best practices ?

**Comment by bdominguez** [comment]
I'm tempted to use this asset by I have the same problem. I have a lot of logic using .NET Task class that I can't change as it's generic code decoupled from Unity API.

I see that this asset uses a specific UniTask class...

**Comment by neuecc** [comment]
I'm not thinking to upload .NET Core version of UniTask.

**Comment by bdominguez** [comment]
I'm not speaking about .NET Core, I'm speaking about supporting standard .NET "Task" class to be compatible with decoupled code (from Unity API).

**Comment by neuecc** [comment]
use Task as is:)

**Comment by halleyxu** [comment]
we could use Task，but the code can't shared both client and server side...so we must use #if NET_CORE then use Task,too ugly...
