### ISSUE TITLE
UnityWebRequestException extra line in exception message

### ISSUE THREAD

**Issue by nolimet** [Cysharp/UniTask#368]
Yes I know odd case.

But there is a extra white line when you are using the `DownloadHandlerBuffer` which in this case does not contain any message.
It will not have a message when you are using a very much invalid url. 
Used this `0ebdL28so/u4yjQ33M:oxfbM:BkN84XGmXudE:Kx1I</SpcHVQ` as a path.
Resulting in 
![image](https://user-images.githubusercontent.com/2866064/175062226-41b9b500-1b18-4dfb-848d-08bc476dd957.png)
When using any other downloadhandler.
![image](https://user-images.githubusercontent.com/2866064/175062656-ff2d21cf-1866-4adb-bed0-179514e9cd06.png)

This is causing a whole heap of issues when writing unit tests for our project.

Getting a exception here was very very very much expected as the path used does not exist as far as I know.

The exact issue is in Cysharp.Threading.Tasks.UnityWebRequestException line 52
```cs
if (msg == null)
{
    if (Text != null)
    {
        msg = Error + Environment.NewLine + Text;
    }
    else
    {
        msg = Error;
    }
}
```
Where if msg is not null it will do `Error + newline + Text` even when Text is a String.Empty or "".
A possible fix might be adding in `string.IsNullOrWhiteSpace()` or `string.IsNullOrEmpty()`
Wich ever way the current implementation might cause some strange effects.

**Comment by neuecc** [comment]
merged, thank you!
