### ISSUE TITLE
Unitasks don't work properly in edit mode

### ISSUE THREAD

**Issue by BattlefieldNoob** [Cysharp/UniTask#37]
I've tried to use Unitask into a "edit mode only" project (the unity project only creates assetbundles automatically), and UniTask runners and continuations don't work like play mode.
This example show the issue

```
public class UniTastEditModeIssue : MonoBehaviour
{
    [MenuItem("executeHeavyOperationByAsync", menuItem = "EditorTest/Execute Task")]
    static async Task VeryHeavyOpTask()
    {
        Debug.Log("Very Heavy Operation start (Task)");
        await Task.Delay(TimeSpan.FromSeconds(5));
        Debug.Log("Very Heavy Operation end (Task)");
    }
    
    [MenuItem("executeHeavyOperationbyUniTask", menuItem = "EditorTest/Execute UniTask")]
    static async UniTask VeryHeavyOpUniTask()
    {
        Debug.Log("Very Heavy Operation start (UniTask)");
        await UniTask.Delay(TimeSpan.FromSeconds(5));
        Debug.Log("Very Heavy Operation end (UniTask)");
    }
}
```

as you can see, the c# native Task works well, the UniTask version instead only print the first Debug.Log

After some research, i found the problem in PlayerLoop updates called in edit mode, and i found a solution using

```EditorApplication.QueuePlayerLoopUpdate();```

which forces unity to execute PlayerLoop lifecycle

i've made a pull request with my solution for the issue

(i'm sorry for any inadvertency, it's my first issue and pull request)

**Comment by kobechenyang** [comment]
Can we have this in the release? Experience same issue in editor mode.
