### ISSUE TITLE
How to create and immediately schedule UniTask from other thread or regular Task in thread pool.

### ISSUE THREAD

**Issue by hellozyemlya** [Cysharp/UniTask#370]
Assuming I have following code:

```
        public void Start()
        {
            Task.Run(RegularTask);
            
        }
        async Task RegularTask()
        {
            Debug.Log($"RegularTask before loop {Thread.CurrentThread.ManagedThreadId}");
            while (true)
            {
                Debug.Log($"RegularTask loop {Thread.CurrentThread.ManagedThreadId}");
                await RunUniTask(); 
            } 
        }
        async UniTask RunUniTask()
        {
            Debug.Log($"RunUniTask before yield {Thread.CurrentThread.ManagedThreadId}");
            await UniTask.Yield();
            Debug.Log($"RunUniTask after yield {Thread.CurrentThread.ManagedThreadId}");
        }
```
This code "switches" RegularTask to main thread after Yield awaited, and first pring of "before yield" happens in thread pool. How I can ensure that RunUniTask starts its execution in main thread and not touching RegularTask(keep it running in previous thread pool or previous synchronization context)?

With regular tasks I can use TaskFactory and specify synchronization context manually, but how I can do this with UniTask?

**Comment by neuecc** [comment]
Waiting in a previous thread (thread pool) is not possible, even in Task or SynchronizationContext.
If you want to wait on SynchronizationContext, you can use SwitchToSynchronizationContext.
