### ISSUE TITLE
[Feature request] UniTask.Delay(float seconds)

### ISSUE THREAD

**Issue by Romaleks360** [Cysharp/UniTask#371]
We almost never use milliseconds in Unity, it's always seconds. I am constantly writing `UniTask.Delay((int)(delay * 1000f))`, which is pretty tedious (and we can't have static extensions in c#, sadly). Considering the runtime, it would be really useful to include this overload.

**Comment by neuecc** [comment]
Providing two overloads is difficult to add because we believe it will have chaotic results.
I agree with you that it would have been better not to follow Task.Delay.

Since the UniTask class is partial, it may be possible to add your own methods by `.asmref`.

**Comment by Romaleks360** [comment]
That's an awesome tip, didn't notice it is partial. Thank you very much!

**Comment by Cdddo** [comment]
Couldn't we just have it be named Wait or WaitForSeconds, or even DelayForSeconds, in order to prevent confusion without overloading Delay, and not have to make the partial class with assembly refs?

**Comment by sgaumin** [comment]
Just created a pull request for adding WaitForSeconds method declarations. 

Following this thread, hoping that it will be useful :love_you_gesture:
