### ISSUE TITLE
Does UniTaskAsyncEnumerable poll at every loop?

### ISSUE THREAD

**Issue by erraineon** [Cysharp/UniTask#373]
I had a question regarding the performance of IUniTaskAsyncEnumerable. When I initialize an object like...
```
public class UniTaskTriggerTest : MonoBehaviour
{
    private void Start()
    {
        this.GetAsyncCollisionEnter2DTrigger().Subscribe(OnCollision);
    }

    private void OnCollision(Collision2D obj)
    {
        // do something
    }
}
```

**Is there a performance penalty at every frame?**

My confusion comes from the following section in the documentation:
> [...] but UniTaskAsyncEnumerable is a pull-based asynchronous stream, whereas Rx was a push-based asynchronous stream.

This made me wonder if there's some kind of check running at every loop, which would cause a performance hit if thousands of objects use async triggers or AsyncReactiveProperty.

Outside of the initial allocation overhead, is there any performance reason to use the built-in unity methods (for example `OnCollisionEnter2D`) instead of the async triggers?

**Comment by neuecc** [comment]
> Is there a performance penalty at every frame?

No.
await is only wait once.
Pull based means register every after trigger called.

```csharp
whle(await MoveNextAsync()) // wait collision enter(register as pulling)
{
    // do.
}
```
