### ISSUE TITLE
Concurrent 

### ISSUE THREAD

**Issue by michaellu88** [Cysharp/UniTask#376]
I am new to unitask, and I am building a webgl game importing vrm at runtime.
I am trying to modified the univrm code to use unitask. And I found a system.collection.concurrent which are not supported by webgl. The code https://github.com/vrm-c/UniVRM/blob/master/Assets/VRMShaders/GLTF/IO/Runtime/AwaitCaller/TinyManagedTaskScheduler.cs

Is it possible to rewrite this to pair with unitask?

Tq

**Comment by neuecc** [comment]
You can use `Channel`?
