### ISSUE TITLE
DOTween cancellation token not immediate

### ISSUE THREAD

**Issue by Atlinx** [Cysharp/UniTask#378]
I've noticed that whenever I wanted to cancel a tween immediately, I'd have to wait until the end of the frame for the tween to stop. Is it possible to kill the tween immediately, so my cancel logic can become synchronous instead of asynchronous?

Ex. (What I'm doing right now)
```C#
cancelTween?.Cancel();
cancelTween?.Dispose();
cancelTween = new CancellationTokenSource();
await UniTask.WaitForEndOfFrame(this); // Tween is actually not cancelled yet!
transform.SetParent(canvas.transform, true); // Tween has been cancelled, now we can do what we want with the tweened object
```

**Comment by kandreyc** [comment]
this is my workaround
`public static async UniTask ToUniTaskWithImmediateCancel(this Tween tween, CancellationToken token)
        {
            await using var _ = token.Register(() =>
            {
                if (tween.IsActive())
                {
                    tween.Kill();
                }
            }, true);

            await tween.ToUniTask(TweenCancelBehaviour.Kill, token);
        }`

**Comment by neuecc** [comment]
Because of Performance (Register has allocations), it is not immediate.
However, I understand the needs, I will try to find a way to implement it efficiently.

**Comment by yellowisher** [comment]
Another workaround; call `tween.onUpdate` just after cancel. (quite cumbersome though)

```
cancelTween.Cancel();
tween.onUpdate(); // Instead of WaitForEndOfFrame
transform.position = Vector3.zero;
```

Looking forward to neat implementation. 👀

**Comment by keenanwoodall** [comment]
I'm not sure if this is related, but I am running a chain of sequences and passing using `this.GetCancellationTokenOnDestroy` for the cancellation token. If the game-object is destroyed during the first tween, a cancellation exception doesn't seem to be thrown. You can see `IsCancellationRequested` is true, but execution continues and I get a `MissingReferenceException` on the `transform`.
![image](https://user-images.githubusercontent.com/9631530/184726479-c3b5fcb6-cb14-4b52-a353-84716f9c1694.png)

**Comment by neuecc** [comment]
use the TweenCancelBehaviour?
default is Kill.
CancelAwait, ***AndCancelAwait are throws OperationCanceledException.

**Comment by keenanwoodall** [comment]
I see, thanks. I switched to the `ToUniTask` extension method so I can set the cancel behaviour, tho I would expect `WithCancellation` to throw an exception by default :P

**Comment by vachh** [comment]
mark
