### ISSUE TITLE
confused about Unitask.delay

### ISSUE THREAD

**Issue by sebas77** [Cysharp/UniTask#382]
Hi,

I am confused by UniTask.Delay returning to the mainthread. What I am supposed to use to wait some time and not return to the mainthread? (of course I don't want just a sping wait, but something smart that works out if to use sleep,yield or spinning)

P.s.: do you have a discord server?

**Comment by neuecc** [comment]
Delay returns to MainThread for timers using PlayerLoop.
It is the same as Task.Delay returning to ThreadPool because it uses ThreadPool Timer.
There is no such thing as a timer that returns to "the same thread."

**Comment by sebas77** [comment]
thanks, my mistake I meant what to use to not return to the mainthread.
I guess you are suggesting using Task.Delay.

**Comment by neuecc** [comment]
If you want to go to another thread while turning the Timer in PlayerLoop, you can use SwitchToThreadPool after Delay.
It's all about which timer you want to use for Delay.

**Comment by sebas77** [comment]
the method was not in the mainthread to start with. I was disoriented when I realised that Delay was taking the method back to the mainthread (which can add lag that I don't want). at the moment I solved using Task.Delay.
