### ISSUE TITLE
Run abstract UniTasks in parallel

### ISSUE THREAD

**Issue by cckelly** [Cysharp/UniTask#384]
Hello! I have a base class that has a `Run` function that returns type `UniTask`. I have a collection of this base class that I want to call the `Run` function on all of them in parallel. Is this possible? Thanks in advance

**Comment by cckelly** [comment]
Basically - is there a way to store a collection of functions that return UniTask that can be ran either in serial or parallel

**Comment by neuecc** [comment]
You can store the return value of Run (UniTask) in an array so that it is eligible for WhenAll.

**Comment by cckelly** [comment]
The problem is that if you do that you run them before you want to:
```
var sequences = _originalSequences.Select(seq => seq.Run());
await UniTask.WhenAll(sequences);
```

This will call Run before we actually get to the `WhenAll`

**Comment by neuecc** [comment]
Task (UniTask) was originally designed that way.
Wrap it with UniTask.Lazy to delay its execution.

**Comment by cckelly** [comment]
How do you pass that to WhenAll when you wrap `seq.Run` in `UniTask.Lazy` at that point?

**Comment by neuecc** [comment]
`Select(seq => UniTask.Lazy(() => seq.Run()))`

**Comment by cckelly** [comment]
No I tried that, it doesn't compile: `Cannot convert expression type 'Cysharp.Threading.Tasks.AsyncLazy' to return type 'Cysharp.Threading.Tasks.UniTask'`. This also wouldn't be able to be passed into WhenAll.

**Comment by neuecc** [comment]
sorry, It was an old specification.
What about `UniTask.Defer`?

**Comment by cckelly** [comment]
That worked, thank you!
