### ISSUE TITLE
Cancelling all running Unitask operations

### ISSUE THREAD

**Issue by fsener** [Cysharp/UniTask#386]
Hi,

Is there a way to kill all running UniTask operations without attaching a cancellation token to each of them? We have a state where we need to "soft restart" the game which requires suspension of everything UniTask related.

We have tried modifying the PlayerLoopHelper by adding the following and it works but we're currently looking for a way to deal with this without modifying the code; 

        public static void StopAll() {
            IsEditorApplicationQuitting = true;
            
            if (runners != null) {
                for (var i = 0; i < runners.Length; i++) {
                    runners[i].Clear();
                }
            }

            if (yielders != null) {
                for (var i = 0; i < yielders.Length; i++) {
                    yielders[i].Clear();
                }
            }
            
            IsEditorApplicationQuitting = false;
        }

Thanks in advance.

**Comment by fesener** [comment]
bump

**Comment by PMelch** [comment]
we have the same issue. would appreciate an official solution and not messing with the PlayerLoopHelper

**Comment by perholmes** [comment]
Also bump here. Hot reloading is a thing in game engines, and this is a choice between a single call to reset the UniTask framework, or about 500 lines of code made much more noisy by schlepping around a universal cancellation token.

Will try the PlayerLoopHelper hack until a property solution exists for this very obvious and real problem.

**Comment by perholmes** [comment]
I was trying to come up with a better way to do this, and looking through the PlayerLoopHelper code, it looks like UniTask is already making some accommodation for this in the Init() method:

```
#if UNITY_EDITOR && UNITY_2019_3_OR_NEWER
            // When domain reload is disabled, re-initialization is required when entering play mode; 
            // otherwise, pending tasks will leak between play mode sessions.
            var domainReloadDisabled = UnityEditor.EditorSettings.enterPlayModeOptionsEnabled &&
                UnityEditor.EditorSettings.enterPlayModeOptions.HasFlag(UnityEditor.EnterPlayModeOptions.DisableDomainReload);
            if (!domainReloadDisabled && runners != null) return;
#else
            if (runners != null) return; // already initialized
#endif

            var playerLoop =
#if UNITY_2019_3_OR_NEWER
                PlayerLoop.GetCurrentPlayerLoop();
#else
                PlayerLoop.GetDefaultPlayerLoop();
#endif
```

This looks like it's aware of restarts without domain reloads, which was the situation I was concerned about. I'm wondering if the original poster has a more particular situation of needing to soft-reset the game without actually exiting or entering the play loop, which I think is relevant, but is not our situation.

But looking through the code, it seems like it would be possible to called the Initialize(...) function from the outside, which resets both the runners and the yielders queues, which is all the OP's code snippet does anyway:

```
public static void Initialize(ref PlayerLoopSystem playerLoop, InjectPlayerLoopTimings injectTimings = InjectPlayerLoopTimings.All)
        {
#if UNITY_2020_2_OR_NEWER
            yielders = new ContinuationQueue[16];
            runners = new PlayerLoopRunner[16];
#else
            yielders = new ContinuationQueue[14];
            runners = new PlayerLoopRunner[14];
#endif
```

Key, it's already public, so it may be possible to call this with the right config and not need to fork UniTask into a local package.

Either way, I'm guessing this does what we need already, so I'll just try some startups without domain reload and monitor the UniTask task inspector.

**Comment by adrian-bio** [comment]
Any news on this? I tried to play with the Initialize method, but I could not manage it to work. We also need a proper way to reload the game and cancel all unitasks without adding 500 lines of code.

**Comment by perholmes** [comment]
I hope the maintainers will take this seriously. Stopping all tasks wholesale has legitimate use-cases, including exception handling in a deployed app.

There's currently no way to properly stop UniTask if the app needs to do a warm-start after a major error. Your only options seem to be (a) forcing a crash needlessly just to stop UniTask, (b) cancellation tokens on EVERYTHING just for being able to shut down the app in-process, (c) forking UniTask just to add this very basic feature.

I beg of the maintainers to not be idealistic or elitist about this. This is a real need.

**Comment by Blackclaws** [comment]
Looking at the code, one solution should be to run the ```Initialize``` method like this twice:
```
PlayerLoopHelper.Initialize(PlayerLoop.GetCurrentPlayerLoop(), (InjectPlayerLoopTimings) 0);
PlayerLoopHelper.Initialize(PlayerLoop.GetCurrentPlayerLoop());
```

The first call should remove all existing runnings, the second one readds them.

You should probably call:
```
GC.Collect();
```

after any of this.

I'd still massively advise against doing this as you might be leaking memory left and right by leaving your system in an inconsistent state. That's the reason why we run a ```CancellationToken``` from the main entry point of our application all the way to the bottom, a clean exit/restart. You might still have inflight requests that return from external libraries that find that their continuation has been ripped out from under them which might or might not crash your app anyway or at the very least result in garbage memory that you need to collect.

**Comment by hadashiA** [comment]
HI, 
Things like UniTask and Task are fairly low-layer utilities, and a situation where everything is stopped uniformly is unnatural.
(For example, not all processes stop while the OS is running)
Perhaps the request in this issue is to stop all UniTasks in a particular context. Stopping PlayerLoop to do that is undesirable.
I agree that bucket relay of CancellationToken can be complicated, but unfortunately that is the only way we can officially support it!
