### ISSUE TITLE
How TakeLast work?

### ISSUE THREAD

**Issue by datndwolffun** [Cysharp/UniTask#387]
Hi guys,
I try to test async LINQ `TakeLast` and I don't know how it works.
Testing with this code snippet, nothing happens.
Can someone help me to explain? Thank you!
```
    [SerializeField] private Button button;
    AsyncReactiveProperty<int> point = new AsyncReactiveProperty<int>(0);
    private void Start()
    {
        button.onClick.AddListener(() =>
        {
            point.Value += 1;
        });
        
        point.TakeLast(2).ForEachAsync(x => Debug.Log(x));
    }
```

**Comment by felixngd** [comment]
`TakeLast` will take n created values of a completion async stream. Your async stream is not completed, so call point.Dispose() you will see the result :)
