### ISSUE TITLE
UniTask.WhenAny

### ISSUE THREAD

**Issue by fakegood** [Cysharp/UniTask#388]
Hello, I would like to ask how can I replicate this [Task.WhenAny example](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete?pivots=dotnet-6-0) with UniTask? I am having trouble with this because I kept running into `InvalidOperationException: Already continuation registered, can not await twice or get Status after await.` exception.

Specifically this part
```
int total = 0;
    while (downloadTasks.Any())
    {
        Task<int> finishedTask = await Task.WhenAny(downloadTasks);
        downloadTasks.Remove(finishedTask);
        total += await finishedTask;
    }
```

**Comment by neuecc** [comment]
UniTask is similar as `ValueTask`, does not applicable some samples of Task.

**Comment by fakegood** [comment]
> UniTask is similar as `ValueTask`, does not applicable some samples of Task.

if I want to do something similar, is there any example you can provide?

**Comment by neuecc** [comment]
convert to Task(`ToTask`).
However, it is not recommended due to the overhead.
You may want to consider a different approach.
