### ISSUE TITLE
How  fix this bug  'ArrayPool<TSource>' does not contain a definition for 'Shared'

### ISSUE THREAD

**Issue by ErDon** [Cysharp/UniTask#393]
two project ,one is ok, the other  Assets\Plugins\UniTask\Runtime\Linq\ToLookup.cs(234,43): error CS0117: 'ArrayPool<TSource>' does not contain a definition for 'Shared'

**Comment by AskedYORK** [comment]
I have same problem in Unity2019.4.29f1c2, have you solved it?

**Comment by 0watermelon0** [comment]
代码改成
var pool = Cysharp.Threading.Tasks.Internal.ArrayPool<TSource>.Shared;

**Comment by ccyr119** [comment]
应该是微信小游戏将System.Buffers设置成了global using.
应该将这个issue提给微信小游戏
https://github.com/wechat-miniprogram/minigame-unity-webgl-transform

**Comment by ccyr119** [comment]
应该有个全局的ArrayPool类和Cysharp.Threading.Tasks.Internal.ArrayPool冲突了，可以随便找个C#文件写个ArrayPool，然后用Ctrl+鼠标左键点击，跳转过去看一下，是在哪里声明的。
以我情况为例，我使用tolua，他里面附带了CString.dll的库，这个库自己定义了一个全局的ArrayPool，就会导致其他地方用的ArrayPool都指向了CString.dll中的ArrayPool

**Comment by 0watermelon0** [comment]
> 应该有个全局的ArrayPool类和Cysharp.Threading.Tasks.Internal.ArrayPool冲突了，可以随便找个C#文件写个ArrayPool，然后用Ctrl+鼠标左键点击，跳转过去看一下，是在哪里声明的。 以我情况为例，我使用tolua，他里面附带了CString.dll的库，这个库自己定义了一个全局的ArrayPool，就会导致其他地方用的ArrayPool都指向了CString.dll中的ArrayPool

我和你情况一样，看来只能反编译dll修改源码了

**Comment by Eric1042017370** [comment]
Same Issues, Got it! 
Fix： Use full name class "Tasks.Internal.ArrayPool<T> " instead of "ArrayPool<T>"
