### ISSUE TITLE
Change default logging for unhandled exceptions

### ISSUE THREAD

**Issue by randomPoison** [Cysharp/UniTask#40]
Currently, an unhandled exception thrown in a `UniTask` will be logged as a warning. Normally, an unhandled exception would be logged by Unity with `Debug.LogException()`. This behavior can be changed by setting `UniTaskScheduler.UnobservedExceptionWriteLogType`:

```
UniTaskScheduler.UnobservedExceptionWriteLogType = LogType.Exception;
```

I think it's good that the behavior can be customized, but it would be better to have the default behavior match what Unity does by default.

If this is acceptable, I would be happy to open a pull request for the work! :grin:

**Comment by neuecc** [comment]
I am very sorry for the delay in replying.
If it is Exception, the information that it is via UnobservedException will be lost.
such as the following.
`msg = "UnobservedTaskException:" + ex.ToString();`
If it is Error, it will be retained.

With that in mind, I'm wondering if an Error would be better?
Warning is unpopular, to be sure.

**Comment by randomPoison** [comment]
If you log an exception with `Debug.LogException()`, the type of the exception is still logged. For example, with the following code:

```csharp
public class CustomExceptionTest : MonoBehaviour
{
    private void Start()
    {
        Debug.LogException(new CustomException("This is a custom exception!"));
    }
}

public class CustomException : Exception
{
    public CustomException(string message) : base(message) { }
}
```

Unity logs the following

```text
CustomException: This is a custom exception!
UnityEngine.Debug:LogException(Exception)
CustomExceptionTest:Start() (at Assets/Scripts/CustomExceptionTest.cs:8)
```

I can also confirm that logging an exception with `Debug.LogException()` preserves the stack trace for the original exception:

```text
CustomException: Exception throw with callstack
CustomExceptionTest.SecretlyThrows () (at Assets/Scripts/CustomExceptionTest.cs:27)
CustomExceptionTest.DoAThing () (at Assets/Scripts/CustomExceptionTest.cs:22)
CustomExceptionTest.Start () (at Assets/Scripts/CustomExceptionTest.cs:12)
UnityEngine.Debug:LogException(Exception)
CustomExceptionTest:Start() (at Assets/Scripts/CustomExceptionTest.cs:16)
```

So it seems like using `Debug.LogException()` would be the best approach. Or am I misunderstanding what your original concern was?

Also, sorry for taking a long time to respond myself 😅

**Comment by neuecc** [comment]
Unhandled exceptions are normally logged when GCed.
If it appears in a form similar to a normal log, will be confused as to where the log came from.
For that reason, the prefix "UnobservedTaskException:" is added.

**Comment by randomPoison** [comment]
Ah! I think I see what you mean: If a `NullReferenceException` where thrown in an unobserved task, it would only say "NullReferenceException: ...", it wouldn't include the "UnobservedTaskException: ..." part since there's no actual `UnobservedTaskException` type being thrown. Sorry about the confusion!

That said, I'm not sure I understand why the "UnobservedTaskException:" prefix is necessary? If the exception were logged with `Debug.LogException()` it would appear in the console the same way that any uncaught exception would. This includes the ability to jump to the location that threw the exception, so users could see that it was thrown from inside a task:

![image](https://user-images.githubusercontent.com/1900829/80780873-1c72c580-8b36-11ea-9c83-936a895b1de3.png)

If exceptions were logged this way by UniTask, what would be confusing for users?

**Comment by neuecc** [comment]
The exception is raised from user code or `GC`.
to distinguish it.

**Comment by randomPoison** [comment]
Sorry if I'm missing something obvious here, but I'm still not sure why logging with `LogError()` would be less confusing than logging with `LogException()` 😅 To better see how Unity handles uncaught exceptions I setup an example with some side-by-side comparisons. [You can see the test script here](https://github.com/randomPoison/UniTask/blob/7fee9f441558429e9bec7448c501071db82f6e85/Assets/ExceptionExamples.cs).

---

As a baseline, here's an uncaught exception thrown from regular (non-async) code. This is how Unity users are expecting uncaught exceptions to be handled. Double-clicking the log entry takes you to the place where the exception was thrown, and in Unity 2019 you can also click on each location in the stack trace.

![image](https://user-images.githubusercontent.com/1900829/80822783-0f3ef080-8ba1-11ea-8ba3-6f9aa61b6322.png)

---

This is what an uncaught exception looks like in `async void` function. This looks basically the same as an exception in non-async code. The stack trace is more complicated due to how `async` works, but double clicking the log entry still takes you to the place where the exception was thrown, and you can still click on each location in the exception's stack trace.

![image](https://user-images.githubusercontent.com/1900829/80823439-4366e100-8ba2-11ea-984c-a7409c8c28ae.png)

---

This is what an uncaught exception looks in a `UniTask` looks like if we configure `UniTaskScheduler` to log unobserved exceptions with `LogType.Exception`. This looks and behaves the same way as any other uncaught exception in terms of being able to jump directly to where the exception was thrown and being able to jump to any point in the exception's stack trace.

I do see what you mean about the exception showing up as "logged from user code", since you can also see `UniTaskScheduler` showing up below the exception's stack trace. However I don't think that's a big issue since the user still has full access to the exception's stack trace.

![image](https://user-images.githubusercontent.com/1900829/80823493-5aa5ce80-8ba2-11ea-9b8d-86a851d5fcfb.png)

---

This is what an uncaught exception looks like in a `UniTask` if we configure `UniTaskScheduler` to log unobserved exceptions with `LogType.Error`. Double clicking the log entry takes you to `UniTaskScheduler.cs` instead of where the the exception is logged. You can see all of the stack trace for the exception, but you can't click on the locations anymore. The only parts you can click on are the stack trace for where the log was made, which is inside of `UniTask` code rather than user code.

This seems more confusing to me as a Unity developer, since this behaves very differently than other uncaught exceptions.

![image](https://user-images.githubusercontent.com/1900829/80823639-9fca0080-8ba2-11ea-9f35-4b87784cf7e3.png)

---

Looking at how the exception is actually surfaced to users, I'm still not seeing how logging with `Debug.LogException()` is any more confusing. You don't have the explicit call out that the exception is coming from an unobserved task, however I don't think that matters in practice: Whether the exception was thrown from a task or from non-async code, it was unhandled either way. What's most important is that users are able to quickly identify why the exception was thrown, which is much harder to do when you can't easily jump to different parts of the stack trace.

At this point, I think it'd actually be better to remove the `UnobservedExceptionWriteLogType` configuration option and **always** log exceptions with `Debug.LogException()`. If users _really_ want to suppress uncaught exceptions, they would still be able to register a callback for the `UnobservedTaskException` event and log the exceptions however they want.

Hopefully that comparison makes sense! Please let me know if I'm still missing something about why it would be better to log with `Debug.LogError()` 😅

**Comment by kamyker** [comment]
I'm not sure why but in builds (il2cpp windows) my stack traces from UniTasks are completely wrong. It could be related to this issue.

**Comment by randomPoison** [comment]
@kamyker are you able to post what the stack traces look like? I wouldn't expect anything in this issue to cause the stack traces to be wrong 🤔 It only impacts how how they're visualized in the editor.

**Comment by kamyker** [comment]
Never mind, ignore me, updated to newest version and it's better.

**Comment by neuecc** [comment]
@randomPoison 

In your example, the `Throw from async Task` is not captured.
Normal tasks must be set explicitly via `TaskScheduler.UnobservedTaskException`.
In other words, this is where we identify whether it's Unobserved or not.

It's also listed at the top in Error.

```
UnobservedTaskException:System.Exception: Thrown from `async UniTask` function
  at ExceptionExamples+<<ThrowFromUniTask>g__ThrowInner|7_0>d.MoveNext () [0x0006f] in C:\...\Scenes\ExceptionExamples.cs:72 
```

The problem, however, is that, as you say, the InnerException dump is Log-unfriendly in Unity.
It's a choice between making the Log jump friendly or marking it as Unobserved.

Now, I think most people don't understand the meaning of Uobserved in the first place,
and jump-friendly seems to benefit a lot of people.
Ok, I'd like to make Exception the default, at least in v2.

**Comment by randomPoison** [comment]
Ah yeah, I had noticed that exceptions thrown from an unobserved `Task` don't get logged at all in Unity. Seems like it would normally crash a C# application, but Unity doesn't let that happen. I'm glad you have UniTask logging exceptions in unobserved tasks by default, I think that's the right thing to for a Unity project 😁 

Do you expect v2 to be ready for release soon? If not, it might make sense to at least change the default log level for exceptions in the next v1.x release. I can throw up a quick pull request for that, it's a small change.

For v2, I'd also suggest fully removing `UniTaskScheduler.UnobservedExceptionWriteLogType`. If you're okay with pull requests against the `unitask2` branch I'd be happy to set that up as well 😄

**Comment by neuecc** [comment]
> v2 release
Soon.

> fully removing UniTaskScheduler.UnknownExceptionWriteLogType

I don't think there's any harm in leaving it out,
so I don't think it's necessary to erase it on purpose.

**Comment by randomPoison** [comment]
You're right, there's not a lot of harm in leaving that option in there, especially if it's set to log using `Debug.LogException()` by default. However, there's also not much value in leaving it in I think. It's a bad practice to log exceptions with anything other than `Debug.LogException()`, so leaving that option in just allows users to make their projects harder to debug with no benefit. It also adds a bit of unnecessary code complexity to `UniTaskScheduler`. So even if there's not much harm in leaving it, I only see benefits to removing it.

That said, once the default is changed to `Debug.LogException()` my main concern will be addressed! So it won't matter a ton to me if you do leave it in.
