### ISSUE TITLE
Threadpool and WebGL

### ISSUE THREAD

**Issue by RichardGSchmidt** [Cysharp/UniTask#402]
Is the Threadpool not supported under a WebGL build?  It's not indicated in the documentation, but it looks like it's non-functional post build for me.

**Comment by BoysheO** [comment]
base on document of unity3d ,WebGL not support multithreading

**Comment by RichardGSchmidt** [comment]
This line makes that unclear in the UniTask docs and should be altered: 

> Runs completely on Unity's PlayerLoop so doesn't use threads and runs on WebGL, wasm, etc.

My assumption based on that statement was UniTask's threadpool wasn't actually truely threading since it ran in the player loop.

**Comment by BoysheO** [comment]
Is it the bug about unity version?

**Comment by RichardGSchmidt** [comment]
No.  The Threadpool functions are simply non functional on webgl builds with no error codes.  UniTask Async and Coroutines seem to work fine however.

**Comment by RichardGSchmidt** [comment]
> Most UniTask methods run on a single thread (PlayerLoop), with only UniTask.Run(Task.Run equivalent) and UniTask.SwitchToThreadPool running on a thread pool. If you use a thread pool, it won't work with WebGL and so on.

> UniTask.Run` is now deprecated. You can use UniTask.RunOnThreadPool instead. And also consider whether you can use UniTask.Create or UniTask.Void.

Found in the docs.
