### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by wojciech-turek** [Cysharp/UniTask#403]
Hey 👋 

I am importing the package via GitHub URL in my Package Manager but after I do that my Unity does not find the package.

I am using Unity 2021.3.8

![image](https://user-images.githubusercontent.com/61434499/191460998-916946f6-6a35-4f8b-90eb-3eeca6e1d2e6.png)

What am I missing?

**Comment by JoshOtter** [comment]
I ran into the same issue when I first installed the package via the GitHub URL in the Package Manager, but then I tried closing the Unity Editor and opened it back up with Unity Hub, and the `using Cysharp.Threading.Tasks;` worked fine after that.

**Comment by gramiro** [comment]
In my case I'm using VSCode on MacOS and the following worked for me:

Go to Unity Preferences > External Tools > Select Visual Studio Code as the code editor.

Mark the necessary checkboxes of `Generate .csproj files for:` and then proceed to `Regenerate project files`

<img width="686" alt="Screenshot 2022-12-19 at 03 25 06" src="https://user-images.githubusercontent.com/2124882/208335627-fcb6518c-7ca0-4b78-98e5-7a8cd7844361.png">

**Comment by Add-HX** [comment]
I have the same problem with Unity 2021.3.12, regenerating project files, reopening Unity Editor, reinstalling the package, and changing to VS Code does not work.
