### ISSUE TITLE
FirstValueToUniTaskObserver cancellation

### ISSUE THREAD

**Issue by battleroy** [Cysharp/UniTask#406]
Hello! I've found a little issue with cancellation propagation at FirstValueToUniTaskObserver:
`static void OnCanceled(object state)
            {
                var self = (FirstValueToUniTaskObserver<T>)state;
                self.disposable.Dispose();
                self.promise.TrySetCanceled();
            }`
Here FirstValueToUniTaskObserver.cancellationToken not passed into promise.TrySetCanceled. It's may be a bug, isn't it?

So when clause comparing cancellation tokens of OperationCanceledException in a catch section doesn't work as supposed.

As I see this issue can also be relevant for ToUniTaskObserver.

**Comment by neuecc** [comment]
Thank you, indeed, this should be passed.
