### ISSUE TITLE
Subscribe to Fire and Forget async calls?

### ISSUE THREAD

**Issue by cckelly** [Cysharp/UniTask#407]
Is there a way to `Subscribe` to a generic `UniTask`? For example, I don't want to `await` a `UniTask` but I want to do something with the result when it's complete.

```csharp
private async UniTask<string> GetPlayerName()
{
    string playerName = await GetPlayerNameFromServer();
    return playerName;
}

private void Awake()
{
    GetPlayerName().Subscribe(name => PlayerPrefs.Set("playerName", name));
    // other initialization
}
```

**Comment by GainDeveloper** [comment]
Perhaps not what you're wanting but in these cases I've just created a UniTaskVoid method and call it with Forget().

`private async UniTask<string> GetPlayerName()
{
    string playerName = await GetPlayerNameFromServer();
    return playerName;
}

private async UniTaskVoid GetAndSetPlayerName()
{
    var playerName = await GetPlayerNameFromServer();
    PlayerPrefs.Set("playerName", playerName);
}

private void Awake()
{
    GetAndSetPlayerName().Forget();
    // other initialization
}`

**Comment by cckelly** [comment]
I'm aware of the `Forget` function, but that doesn't provide a way to actually do something once the async task is complete.

**Comment by GainDeveloper** [comment]
What I posted above does exactly what you've asked, it's just not wrapped in a delegate call.

**Comment by cckelly** [comment]
I'm aware of the functionality you call out, but IMO it's a cleaner syntax to be able to wrap in a delegate that passes an Action<T>

**Comment by GainDeveloper** [comment]
Would just making an extension method work then?

`public static async void OnComplete<T>(this UniTask<T> task, Action<T> onComplete) => onComplete(await task);
`

You could then just call,

`MethodReturningString().OnComplete((x) => { Debug.Log(x); });`

Ofcourse I might be missing this functionality in UniTask but I've not come across it.

**Comment by lightjiao** [comment]
`ContinueWith<T>()` maybe help:
```csharp
private async UniTask<string> GetPlayerName()
{
    string playerName = await GetPlayerNameFromServer();
    return playerName;
}

private void Awake()
{
    GetPlayerName().ContinueWith(name => PlayerPrefs.SetString("playerName", name)).Forget();
    // other initialization
}
```

**Comment by cckelly** [comment]
I was just coming back here to callout `ContinueWith`, it has several useful overrides that make this work. Thanks all.
