### ISSUE TITLE
Il2cpp build fails when assigning UniTask to static readonly field

### ISSUE THREAD

**Issue by Last8Exile** [Cysharp/UniTask#408]
Having this code in project break il2cpp build and i don't know why.
```
using Cysharp.Threading.Tasks;

public struct Result
{
    public static readonly UniTask<Result> SucceededTask = UniTask.FromResult(new Result());
}

```

This is isolated case from big project that using UniTask and start failing to build after addition of member SucceededTask to Result class.
Any clues why this is happening?

UniTask 2.3.1
Unity 2021.3.9f1
Windows build with il2cpp scripting backend.
[Editor.log](https://github.com/Cysharp/UniTask/files/9659085/Editor.log)
Log contains some error messages with wrong encoding, i also can't read them.
But they are about unable to find type Result

Also created bug report for Unity.

**Comment by neuecc** [comment]
thank you for reporting, I'll wait reply from unity.

**Comment by Last8Exile** [comment]
Unity reproduced error.
https://issuetracker.unity3d.com/issues/il2cpp-build-fails-when-unitask-variable-is-declared-in-the-struct

**Comment by bholmes** [comment]
This is a limitation of il2cpp (.Net Framework and CoreCLR). At code generation time and at runtime il2cpp processes instance and static fields at the same time. Your case creates a circular dependency between `Result` and the inflated `UniTask<Result>`.

We do not plan to fix this in il2cpp as CoreCLR also does not handle this case and we are in the process of adding CoreCLR support to the Unity Player.

If Microsoft decides to fix this issue we will re-evaluate the bug for il2cpp.

https://github.com/dotnet/runtime/issues/5479

Can you try something like this to work around the problem?

```
using Cysharp.Threading.Tasks;

public struct Result
{
    public static UniTask<Result> SucceededTask => ResultStatics.SucceededTask;
}

internal class ResultStatics
{
    public static readonly UniTask<Result> SucceededTask = UniTask.FromResult(new Result());
}
```

**Comment by Last8Exile** [comment]
Now i undestand why it won't compile and can avoid it.

Thanks for investigation and explanation.
