### ISSUE TITLE
Stepping over await in the Visual Studio debugger crashes the Unity editor

### ISSUE THREAD

**Issue by randomPoison** [Cysharp/UniTask#41]
I'm running into an issue where using Visual Studio in combination with UniTask is causing the Unity editor to crash.

## Reproduction Steps

1. Write an `async` function that returns a `UniTaskVoid`, `UniTask`, or `UniTask<T>` and `await`s at least once.
2. Using Visual Studio, set a breakpoint on the `await` statement and attach the debugger to the editor.
3. Run your game in the editor until Visual Studio hits the breakpoint.
4. Try to step over the `await` statement.

## Notes

* I've tested this with Visual Studio 2019 on Windows with Unity 2019.2.4f1.
* Stepping over `await` statements appears to work correctly when using `async void`, `async Task`, and `async Task<T>`, so the issue appears to have something to do with UniTask.
* It's not clear if the issue is with Visual Studio, Unity, or UniTask. To test this, it would be good to try the following things:
  * Create a non-Unity C# project with Visual Studio 2019 and create a custom task-like type, matching what UniTask provides. See if you can use the debugger here.
  * Create a basic task-like type, similar to what UniTask provides but as minimal as possible, and see if that still causes the editor to crash.

---

I'll try to dig into this issue more, but I wanted to open this ticket in case I don't have time.

**Comment by NoxMortem** [comment]
Just wanted to create the same ticket. Also happens with Rider 2019.3 and Unity 2019.3.3f1

**Comment by neuecc** [comment]
It certainly happens, but it seems to be difficult to solve here.

**Comment by neuecc** [comment]
discussed at #66 and fixed in `1.3.1`.
