### ISSUE TITLE
Question about GC in Profiler

### ISSUE THREAD

**Issue by Kotsuha** [Cysharp/UniTask#412]
I may be mistaken or missing something because I am new to profiling/performance stuff. It seems like it's not zero allocation? My test shows the following result.

GC Alloc                                               | Coroutine | Task                     | UniTask
------------------------------------------------------ | --------- | ------------------------ | -------
In Editor (CodeOptimization: Debug)                    | 64 B      | 288 B                    | 264 B
In Editor (CodeOptimization: Release)                  | 64 B      | 296 B (160 B each frame) | 248 B
In WebGL Development Build (CodeOptimization: Debug)   | 36 B      | 152 B                    | 200 B
In WebGL Development Build (CodeOptimization: Release) | 36 B      | 152 B (80 B each frame)  | 200 B

The [video](https://github.com/Kotsuha/Test-GC-Coroutine-Task-UniTask/blob/main/Videos/2022-10-09_07-36-40.mp4) shows how I test it in [this repo](https://github.com/Kotsuha/Test-GC-Coroutine-Task-UniTask).
Unity: 2020.3.30f1
Build Platform: WebGL

I'd be grateful if someone could answer my question. Thank you.

**Comment by neuecc** [comment]
UniTask is reuse when using `await`.
Your benchmark code is not awaiting.

```csharp
_ = _DoUniTask(_delayFrameCount);
```

**Comment by Kotsuha** [comment]
Thank you for the response.

I've done more testing and currently have two questions:

1. Is my understanding correct? It allocates for the first time and is reused (no alloc) when awaited.

2. In the following code sample, why do `_Do_UniTaskDelayFrame` and `_Do_UniTaskDelayFrameLocal` have different GC Alloc behaviors in Profiler? `_Do_UniTaskDelayFrame` has GC Alloc in the first frame it is called, and has zero GC Alloc afterwards. Whereas `_Do_UniTaskDelayFrameLocal` has GC Alloc afterwards.
 
[Full code (65faef4)](https://github.com/Kotsuha/Test-GC-Coroutine-Task-UniTask) and [video](https://github.com/Kotsuha/Test-GC-Coroutine-Task-UniTask/blob/main/Videos/2022-10-11%2002-59-13.mp4)

```
private async UniTaskVoid _Do_UniTaskDelayFrame()
{
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrame").Auto()) { }
    _tr.transform.localPosition = Vector3.zero;
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrame 1").Auto()) { }
    await UniTask.DelayFrame(10);
    _tr.transform.localPosition = Random.onUnitSphere;
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrame 2").Auto()) { }
    await UniTask.DelayFrame(10);
    _tr.transform.localPosition = Random.onUnitSphere;
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrame 3").Auto()) { }
    await UniTask.DelayFrame(10);
    _tr.transform.localPosition = Random.onUnitSphere;
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrame 4").Auto()) { }
    await UniTask.DelayFrame(10);
    _tr.transform.localPosition = Random.onUnitSphere;
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrame 5").Auto()) { }
    await UniTask.DelayFrame(10);
    _tr.transform.localPosition = Random.onUnitSphere;
    Debug.Break();
}

private async UniTask<int> UniTask_DelayFrame_10_()
{
    await UniTask.DelayFrame(10);
    return 0;
}

private async UniTaskVoid _Do_UniTaskDelayFrameLocal()
{
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrameLocal").Auto()) { }
    _tr.transform.localPosition = Vector3.zero;
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrameLocal 1").Auto()) { }
    await UniTask_DelayFrame_10_();
    _tr.transform.localPosition = Random.onUnitSphere;
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrameLocal 2").Auto()) { }
    await UniTask_DelayFrame_10_();
    _tr.transform.localPosition = Random.onUnitSphere;
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrameLocal 3").Auto()) { }
    await UniTask_DelayFrame_10_();
    _tr.transform.localPosition = Random.onUnitSphere;
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrameLocal 4").Auto()) { }
    await UniTask_DelayFrame_10_();
    _tr.transform.localPosition = Random.onUnitSphere;
    using (new ProfilerMarker("[MyTest] UniTaskDelayFrameLocal 5").Auto()) { }
    await UniTask_DelayFrame_10_();
    _tr.transform.localPosition = Random.onUnitSphere;
    Debug.Break();
}
```

**Comment by neuecc** [comment]
1. yes
2. The timing of the return to the pool of async UniTasks is a bit delayed, this is so in response to a bug in IL2CPP
