### ISSUE TITLE
Error when running in Editor...not in Build

### ISSUE THREAD

**Issue by Jayme65** [Cysharp/UniTask#419]
```
private async UniTask<bool> saveImage(string serverPath, string folderPath, string name)
    {
        try
        {
            using (UnityWebRequest www = UnityWebRequestTexture.GetTexture(serverPath))
            {
                await www.SendWebRequest();
                if (www.result != UnityWebRequest.Result.Success)
                {
                    LogInfo("Error: " + www.error);
                    return false;
                }

                loadedTexture = DownloadHandlerTexture.GetContent(www);
                
                byte[] textureBytes = loadedTexture.EncodeToPNG();
                using (var fileStream = File.OpenWrite($"{folderPath}{pathSeparator}{name}.png"))
                    await fileStream.WriteAsync(textureBytes);
            }
        }
        catch (Exception ex)
        {
            LogError(ex, "");
            return false;
        }
        return true;
    }
```
Hi,
Could you please explain me why this code runs correctly when run in standalone build...but raises a "Create can only be called from the main thread" on the 'using (UnityWebRequest www = UnityWebRequestTexture.GetTexture(serverPath))' line when run from Editor?
To be complete, I have the impression that this code "passes" on its first use and then raises an error when called again!

Thanks!

**Comment by freeschool** [comment]
UnityWebRequestTexture should be called in the main thread. 
I am not sure where this function is called. You must call this function somewhere in a work thread.
Lack of information to say more than that.
