### ISSUE TITLE
Allow scoping of tasks to component lifecycles

### ISSUE THREAD

**Issue by asarazan** [Cysharp/UniTask#42]
I love almost everything about UniTask, but I would really like to have a task cancel itself when its "owner" object is destroyed, or when the scene is closed. Similar to how `StartCoroutine` currently works in Unity.

See also https://github.com/BastianBlokland/componenttask-unity for reference.

**Comment by VacuumBreather** [comment]
I'm upvoting this :)

**Comment by neuecc** [comment]
use `GetCancellationTokenOnDestroy` of `UniRx.Async.Triggers`.
