### ISSUE TITLE
Aggregate Exceptions are not unwrapped when awaiting a UniTask

### ISSUE THREAD

**Issue by discodonut** [Cysharp/UniTask#422]
If you `await` a `System.Task` that throws an `AggregateException`, it unwraps it and throws the first inner exception, but with UniTask, it just throws the `AggregateException`.  This creates an inconsistency with the language standard as defined here https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch#exceptions-in-async-methods

```
var task = <a task that throws InvalidOperationException>
await Task.WhenAll(task); // throws InvalidOperationException
await Task.WhenAll(task).AsUniTask();  // throws AggregateException with inner exception of InvalidOperationException
```

This should probably be called out in the docs if this is intended.

**Comment by neuecc** [comment]
Thanks, may need to change the implementation, will check.

**Comment by krisrok** [comment]
I've just had a stab at it here: https://github.com/Cysharp/UniTask/pull/428

**Comment by birdkingz** [comment]
May I know what's the status of this? Is this an intended design or there will be a fix coming?

**Comment by hadashiA** [comment]
Hi, we have fixed this behavior so that InnerException can be caught.  #500 
Thanks for the suggestion :)
