### ISSUE TITLE
UniTask.WhenAny can't be called multiple times for the same task

### ISSUE THREAD

**Issue by JohannesPaivinen** [Cysharp/UniTask#423]
I'm trying to use UniTask.WhenAny to maintain a queue of tasks. I need to be notified every time one of the tasks completes.

However, this code
```
        async UniTask Test()
        {
            List<UniTask> tasks = new List<UniTask>();
            tasks.Add(UniTask.Delay(1000));
            tasks.Add(UniTask.Delay(2000));
            while (tasks.Count > 0)
            {
                var completedIndex = await UniTask.WhenAny(tasks);
                tasks.RemoveAt(completedIndex);
            }
        }
```
Results in 
`
InvalidOperationException: Already continuation registered, can not await twice or get Status after await.
`

**Comment by Tommigun1980** [comment]
Awaiting multiple times is allowed in the regular tasks implementation.

UniTask mentions that this can be handled by calling .Preserve() (which is alluded to incur a performance hit) or by using UniTaskCompletionSource, but none of these alternatives are documented.

**Comment by slan** [comment]
This limitations comes from ValueTask on which UniTask is based (see YOCO in https://blog.stephencleary.com/2020/03/valuetask.html).
I found `UniTask.WhenAny` usefullness very questionable (especially since you need the `cts` ceremony to avoid leaking).
One example could be a popup:

```C#
var go = Instantiate(_popupPrefab, parent);
using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
var buttonIndex = await UniTask.WhenAny(go.GetComponentsInChildren<Button>()
    .Select(b=>b.OnClickAsync(cts.Token)));
cts.Cancel();
Destroy(go);
```

For other use cases, I fall back to either polling:
```C#
UniTask<PointerEventData> CreateTapTask(CancellationToken ct)
    => _image.GetAsyncPointerDownTrigger().OnPointerDownAsync(ct);

using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct); 
var tapTask = CreateTapTask(cts.Token);
while (true)
{
    if (closeButtonTask.Status.IsCompleted()) return;
    if (tapTask.Status.IsCompleted())
    {
        Debug.Log($"{Time.frameCount} tap: {await tapTask}");
        tapTask = CreateTapTask(cts.Token);
    }
    await UniTask.Yield(ct);
}
```
or (probably better in your scenario) standard `Task.WhenAny()` with `.AsTask()` converter from UniTask.

**Comment by lucasmontec** [comment]
This was not resolved and renders `WhenAny` unusable.
