### ISSUE TITLE
How use UnityAction with parameters

### ISSUE THREAD

**Issue by Magistrix93** [Cysharp/UniTask#427]
Hi!

I have a UniTask<object> function.
I'm trying to use a UnityAction<object> as parameter for a function passing by a the function that need to be called inside, but I can't understand how because is expecting a parameter of course

```
async UniTask FirstFunction (object par)
{
     //do stuff
}

async UniTask ModularFunction (UnityAction<object> action)
{
    object obj = null;
    //get object
    await action.invoke(obj);
}

async UniTask CallModularFunction()
{
   await ModularFunction(???)
}
```
Thanks in advance

**Comment by ALEXTANGXIAO** [comment]
In your function of "ModularFunction", you try await "action.Invoke",but UnityAction could not be await,so this operation is not allowed.
