### ISSUE TITLE
Null Reference on destroying tweened object

### ISSUE THREAD

**Issue by Akilaydin** [Cysharp/UniTask#429]
Greetings!
There is an issue, that throws DoTween null reference if destroying tweened GameObject, while the tween is still playing if using extension method GetCancellationTokenOnDestroy() and pass the given token to the AwaitForComplete()/ToUniTask()/WithCancellation() methods. 
I wrote an extension method that solves this problem: https://github.com/Cysharp/UniTask/pull/404

```
var token = this.GetCancellationTokenOnDestroy();

transform.DOScale(Vector3.one, 2f).WithCancellation(token); //throws null reference on destroy
			
transform.DOScale(Vector3.one, 2f).AwaitForComplete(cancellationToken: token); //throws null reference on destroy
			
transform.DOScale(Vector3.one, 2f).ToUniTask(cancellationToken: token); //throws null reference on destroy
			
transform.DOScale(Vector3.one, 2f).AwaitWithCancellation(token); //Do not throw null reference on destroy
```

**Comment by kondratov-saritasa** [comment]
@neuecc Can confirm the same problem.

**Comment by kondratov-saritasa** [comment]
I fixed it in this way, I found suggested option (https://github.com/Cysharp/UniTask/pull/404) quite dangerous due to cross subscription and the fact `OnKill` overwrite existing delegate.

```
        public static async UniTask AwaitAsync(this Tween tween, CancellationToken cancellationToken)
        {
            if (!tween.IsActive())
            {
                return;
            }

            await using var registration = cancellationToken.Register(() =>
            {
                if (tween.IsActive())
                {
                    tween.Kill();
                }
            });

            await tween.ToUniTask(TweenCancelBehaviour.KillAndCancelAwait, cancellationToken);
        }
```

Perhaps you guys can see something wrong in this code..

**Comment by Akilaydin** [comment]
I created new pull-request with with extension method based on code that @kondratov-saritasa has provided.

https://github.com/Cysharp/UniTask/pull/434

**Comment by kondratov-saritasa** [comment]
@Akilaydin `await using` is not necessary here. We can have only `using` here to support older .NET versions.

However - in your PR you do not convert function to async and do not await the following line:
```
 await tween.ToUniTask(TweenCancelBehaviour.KillAndCancelAwait, cancellationToken);
```

This makes the compiler to Dispose registration right after this line so that will stop the animation immediately when you launch it.

**Comment by Akilaydin** [comment]
@kondratov-saritasa Yes, you are right, thanks for pointing out, I've fixed it
