### ISSUE TITLE
Threads don't stop when gameObject is disabled

### ISSUE THREAD

**Issue by gslopez** [Cysharp/UniTask#433]
In my current project, instead of destroying/creating game objects, I'm using an object pool (i.e, I just do `gameObject.SetActive(false);`) to avoid having to create/destroy objects.

I tried using UniTask instead of Coroutines, and on barrier I found is that the `this.GetCancellationTokenOnDestroy()` object) only works when the gameObject is destroyed. I know I can create my own token, but would be nice to have this implemented by default

**Comment by hoangcuongzk1** [comment]
> In my current project, instead of destroying/creating game objects, I'm using an object pool (i.e, I just do `gameObject.SetActive(false);`) to avoid having to create/destroy objects.
> 
> I tried using UniTask instead of Coroutines, and on barrier I found is that the `this.GetCancellationTokenOnDestroy()` object) only works when the gameObject is destroyed. I know I can create my own token, but would be nice to have this implemented by default

you can use CancelToken to do it. Execute it on OnDestroy
