### ISSUE TITLE
AsyncDestoryTrigger AwakeMonitor performance issue

### ISSUE THREAD

**Issue by a3dline** [Cysharp/UniTask#435]
Hey guys, i found small performance problem in my project with AwakeMonitor for AsyncDestroyTrigger.

We know that MonoBehaviour which never been awaked never been destroyed. 
Because the class provide the CancelationToken we want to Dispose them if object is destoyed.
Specifically for this case we have AwakeMonitor LoopItem which check that MonoBehaviout is alive every Player Loop. 
We created it in a CancelationToken getter.

![image](https://user-images.githubusercontent.com/7162435/211592547-b6331866-fb70-49d7-b22b-6c70f23891cd.png)

![image](https://user-images.githubusercontent.com/7162435/211592509-aaf0357b-44bb-4d7a-8cd9-1653cbc54c4e.png)

But if MonoBehaviour was awaked we still check it alive every frame. 
But we know that if object is awaked the unity event OnDestory will be invoke guaranteed. 

I think we can optimize the AwakeMonitor for check that object already awaked and return "false" for Runner. 

For example:
![image](https://user-images.githubusercontent.com/7162435/211592414-47f9b092-f598-44bb-ae7b-2c995f9972e5.png)

**Comment by yuryyi** [comment]
Also there is a potential issue - if we try to get CancellationToken multiple times before awake, then multiple AwakeMonitors will be added to PlayerLoop, that leads to extra calls of MoveNext (so some extra null checks will be performed)

![8ba19ec7-7b63-4232-b17c-27c10c3e10d3](https://user-images.githubusercontent.com/122440383/211767766-ac27d29b-d838-44f6-8cd0-2c24779a9475.jpg)

Seems like this "!awakeCalled" check should be moved to first "if" condition to be performed only once

**Comment by neuecc** [comment]
Indeed, I'll check it out.

**Comment by hadashiA** [comment]
#493 We have adopted @a3dline and @yuryyi's proposal. Thanks a lot !
