### ISSUE TITLE
Version on Nuget.org does not have UniTask.WaitUntil()

### ISSUE THREAD

**Issue by hoangcuongzk1** [Cysharp/UniTask#436]
I install UniTask 2.3.3 on Nuget.org for my external library unity. But it does not contain WaitUntil().

**Comment by BinaryJared** [comment]
I have the same issue, is there a resolution for this?

**Comment by neuecc** [comment]
WaitUntil is dependent on Unity PlayerLoop so can't use it on Nuget version.

**Comment by BinaryJared** [comment]
Understood - for anyone in the future, made a portable version by taking the Unity package code, slapping it in a DLL project referencing the Unity DLL and removing the editor code so it's runtime only. Only needed to add pre-processor directives for Unity and it was good to go! :)
