### ISSUE TITLE
UniTask Delay

### ISSUE THREAD

**Issue by sebas77** [Cysharp/UniTask#440]
simple question:

as an end user, I am wondering how I am supposed to know that UniTask Delay would fall back on the main thread. In my mind, it is about replacing Task with UniTask in any scenario.

If I want to not fall back to the unity main thread, am I supposed to use Task.Delay instead? In hindsight, I think this is the case, but for some reason, I didn't realise it.

**Comment by krisrok** [comment]
Documentation is not perfect. There's some hints like this though: https://github.com/Cysharp/UniTask#threadpool-limitation but I guess most users will learn their way around the library the "hard way" ;)
