### ISSUE TITLE
Support  Android & Ios  ？

### ISSUE THREAD

**Issue by qq294716498** [Cysharp/UniTask#447]
unitask support Android and iso？

**Comment by daihaminkey** [comment]
@qq294716498 

Yep.

**Comment by Inspyro** [comment]
However I would not count that everything works, for example the `UniTask.WhenAll` function will lead to crashes on Android with IL2Cpp, see: https://github.com/Cysharp/UniTask/issues/463

Unfortunately the whole repo seems to be neglected recently.
