### ISSUE TITLE
queue method calls with interval in Unitask. #help

### ISSUE THREAD

**Issue by Zony-Zhao** [Cysharp/UniTask#449]
In a class, a method is called at same frame for several times.
class{
 OnPress(){
  //do something here
 }
}

What I want is let these calls queue themselves with a interval. For example. call the method for 4 times in a same frame, but do something at 0 s,0.1s, 0,2s, 0.3s.

Right now, Im doing it with Unity's Time.time, which is pretty much original Unity way to do it.
![image](https://user-images.githubusercontent.com/50739849/225200080-799f0f7f-844f-45f1-a831-87825aee9e3a.png)
Is there a more elegant way to do this in UniTask? I know something like `UniTaskAsyncEnumerable.EveryUpdate()`. Can I create something like `UniTaskAsyncEnumerable.EveryPress.Queue.Foreach(()=>await 0.1s)`?
A little bit code snippet would be really helpful.

**Comment by hadashiA** [comment]
It is hard to say with that information alone.

At any rate, there is no "queue" in this code. You will need to provide your own queue. It does not necessarily have to be AsyncEnumerable. It depends.

I don't see any problem using UniTask.WaitUntil way. If interval is the only thing that matters, you can use UniTask.
Also, the `async void` method is not recommended. It may not handle exceptions. Please check the documentation.
