### ISSUE TITLE
DOTween CS4014

### ISSUE THREAD

**Issue by truenoob141** [Cysharp/UniTask#452]
I get an error `warning CS4014: Because this call is not awaited, 
execution of the current method continues before the call is completed. 
Consider applying the 'await' operator to the result of the call.`

In the following code:
```csharp
private async UniTask DoMagic()
{
  // await logic here
  ...
  // DOTween
  var seq = DOTween.Sequence();
  for (int i = 0; i < n; ++i) {
    seq.Insert(time, transform.DOScale(0.3f, 0.1f); // CS4014
      .Insert(time, transform.DOMove(Vector3.zero, 0.1f);
  }
}
```

How to suppress it?

**Comment by desmondfernando** [comment]
Use something like:

```
#pragma warning disable CS4014 // disable warning

private async UniTask DoMagic()
{
  // await logic here
  ...
  // DOTween
  var seq = DOTween.Sequence();
  for (int i = 0; i < n; ++i) {
    seq.Insert(time, transform.DOScale(0.3f, 0.1f); // CS4014
      .Insert(time, transform.DOMove(Vector3.zero, 0.1f);
  }
}

#pragma warning restore CS4014 // restore warning
```

You could also just use a single pragma at the top of the file.

**Comment by truenoob141** [comment]
> Use something like:
> You could also just use a single pragma at the top of the file.

@desmondfernando thanks for reply! But it's not the best solution to write pragma everywhere :(

**Comment by loto** [comment]
Thanks for the trick! A permanent solution would even better :)

**Comment by hadashiA** [comment]
Hmm.. there seems to be no better way than `#pragma ` .

Note: 
C# does not make extension methods a warning until after UniTask was released.
If extension method is in a different namespace, it may be possible to control the use of extension method only when you want to wait, but it is difficult to change it now.

**Comment by joelbschwartz** [comment]
@hadashiA What about using discards? https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/discards

This line gives me the compiler warning about not awaiting a tween:
`myGameObject.transform.DOLocalMoveY(1, .5f).SetEase(Ease.InBack);`

But the compiler warning goes away when I use a discard, like this:
`_ = myGameObject.transform.DOLocalMoveY(1, .5f).SetEase(Ease.InBack);`

**Comment by hadashiA** [comment]
>@hadashiA What about using discards? https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/discards

Ah yeah. I don't think that's too bad.

However, isn't it a bit confusing that the presence or absence of `using UniTask` changes whether or not a discard is required?

**Comment by joelbschwartz** [comment]
I agree that it's confusing, and seems to leave the compiler as a guide to where to use the discards because it's not readily apparent where and why they are used. Maybe at best it's a preferable alternative to `#pragma warning disable CS4014` and at worst, it's confusing without a comment in the code to explain the purpose?

**Comment by brinca** [comment]
If this happens because of UniTask, another way to handle this is to convert it `ToUniTask`, and then `Forget` it , like `myGameObject.transform.DOLocalMoveY(1, .5f).SetEase(Ease.InBack).ToUniTask().Forget();`
