### ISSUE TITLE
Can't assign value to the reactive property from the handler assigned to the same property

### ISSUE THREAD

**Issue by nicloay** [Cysharp/UniTask#454]
here is a unit test that fails. and demonstrate the issue
```
[Test]
public void ReactivePropertyTest()
{
       var testProp = new AsyncReactiveProperty<int>(0);
       var invocationCounter = 0;
       testProp.ForEachAwaitAsync(i =>
       {
           invocationCounter+=i;
           if (i == 3)
           {
               testProp.Value = 5;
           }
           return UniTask.CompletedTask;
       }, CancellationToken.None);
       testProp.Value = 1;
       testProp.Value = 2;
       Assert.That(invocationCounter, Is.EqualTo(8)); // should be 1+2+5, but it's only 3(1+2)
}
```
Are there any patterns or workaround on this? I want to keep the game state in the reactive property, and state-machine handler inside the reactive property handler, but obviously it doesn't work at the moment.

Thanks.

**Comment by hadashiA** [comment]
Hello,
`ForEachAwaitAsync` is recommended to await. If you do so, you will probably get an exception like the following:

> InvalidOperationException: Can not trigger itself in iterating.

It seems that it is not allowed to set value during Iterate.
