### ISSUE TITLE
Exception happen on UniTask Start not be reported on Android

### ISSUE THREAD

**Issue by hoainam1593** [Cysharp/UniTask#467]
for example, I have code
```
async UniTask Start()
{
    throw new System.Exception("-----------exception from start");
}
```
on Editor, I got exception report on console, but on Android, no exception report on logcat.
This is a serious problem, because sometimes, there's odd behavior, I have to spend too much time to figure out due to missing exception report

**Comment by Last8Exile** [comment]
Unity does not await any tasks started via MonoBehaviour event messages.
Exception is reported only when task is garbage collected.
I am suggest you this code:
```
private void Start()
{
    StartAsync().Forget();
}

private async UniTaskVoid StartAsync()
{
    throw new System.Exception("-----------exception from start");
}
```

Forget assigns continuation for task and reports any errors immedeatly.

**Comment by hadashiA** [comment]
Last8Exile's comment is correct :)

Note that `Start` in Unity does not await the async method correctly.
The reason your Start appears to work is because Unity looks for the name `Start` and calls it dynamically without concern for the return value.
