### ISSUE TITLE
DOTween still updates for a single frame after cancelling the token.

### ISSUE THREAD

**Issue by brantkings** [Cysharp/UniTask#468]
Doing something like this:

```
TweenValues values = GetTweenValues(on);

  Tween t = DOTween.To(Get,Set, values.final, values.duration).SetUpdate(values.unscaled);

  if (values.ease != Ease.Unset) t.SetEase(values.ease);

  else t.SetEase(values.curve);

  await t.ToUniTask(TweenCancelBehaviour.KillAndCancelAwait, cancellationToken);
```

And after cancelling cancellationToken, the tween still Set()s for one frame. Any fix for this?

My fix was checking token.IsCancellationRequested on every Set(). Is that expected?

**Comment by hadashiA** [comment]
I think #485 solved this problem.
we used CancellationToken.Register, as suggested in similar Issues, and it is now tween killed synchronously.
Thanks for the sample code and workaround info.
