### ISSUE TITLE
Serious Bug: task.IsCompleted == false after await task, but when using System.Threading.Tasks.Task, task.IsCompleted == true !

### ISSUE THREAD

**Issue by HyVong007** [Cysharp/UniTask#47]
Here is my code:
using UnityEngine;
using System.Threading.Tasks;
using UniRx.Async;

public class Test : MonoBehaviour
{
private Task task = Task.CompletedTask;
private UniTask uniTask = UniTask.CompletedTask;

private async void Start()
{
	await (task = Task.Delay(1000));
	print("task.IsCompleted= " + task.IsCompleted);

	await (uniTask = UniTask.Delay(1000));
	print("uniTask.IsCompleted= " + uniTask.IsCompleted);
}
}

In the output console: "task.IsCompleted= True"
"uniTask.IsCompeleted= False"

**Comment by neuecc** [comment]
Currently it is by design for reuse UniTask.
Task.Delay is started when Task is created.
UniTask.Delay is started when await is called.

**Comment by HyVong007** [comment]
Oh i didnot know that. But, what is a workaround solution for this problem ? i think the task should be completed after awaiting done, but it is not ! Please help me, or can you change the behaviour of UnitTask ?

**Comment by phongsoyenmoc** [comment]
> Oh i didnot know that. But, what is a workaround solution for this problem ? i think the task should be completed after awaiting done, but it is not ! Please help me, or can you change the behaviour of UniTask ?

If you don't want to reuse the same way Unitask.Delay is doing, try writing an Enumerator and converting it into unitask and waiting for it.

```cs
    private Task task = Task.CompletedTask;
    private UniTask uniTask = UniTask.CompletedTask;

    private async void Start()
    {
        await (task = Task.Delay(1000));
        print("task.IsCompleted= " + task.IsCompleted);

        await (uniTask = Observable.FromCoroutine(() => EWaitDelay(1000)).ToUniTask());
        print("uniTask.IsCompleted= " + uniTask.IsCompleted);
    }


    public IEnumerator EWaitDelay(int milliseconds)
    {
        yield return Observable.Timer(TimeSpan.FromSeconds(1)).ToYieldInstruction();
        Debug.Log("Done!");
    }
```

**Comment by HyVong007** [comment]
Thank you very much ! (Bạn là người Việt Nam phải không ?)
I think i will write a custom "async UniTask method" and put that method to Start().
Cảm ơn bạn đã chịu khó trả lời tôi. Thank you for your responese !
