### ISSUE TITLE
Can't find how to use unitask with dotween

### ISSUE THREAD

**Issue by ebolefeysot** [Cysharp/UniTask#475]
Hi
First, thank you for developing this unitask library.
I'm using dotween and saw I can use await with dotween methods and 'AsUniTask()'.
I added UNITASK_DOTWEEN_SUPPORT symbol in unity (2021) as required, but it still complains about AsUniTask not defined.
I search for the extension source code, but can't find it anywhere.
Has it been removed ? If no, how to use it ?
Thanks for your help.

**Comment by Merglasch** [comment]
Did you also add a reference to the asmdef that wants to use the code? That's what tripped me up at first.

**Comment by yellowisher** [comment]
Its not `AsUniTask()` but `ToUniTask()`.
Instead, you can await tween directly like this: (don't forget to add `using Cysharp.Threading.Tasks;`)
```
var tween = transform.DOMove(position, duration);
await tween;
```

**Comment by hadashiA** [comment]
yellowisher's comment seems to be the answer :)
Let me know if you have another problem.

**Comment by ebolefeysot** [comment]
It's not working, ToUniTask is not found and I get an error when awaiting the tween.
Version I used is 2.3.1

![image](https://github.com/Cysharp/UniTask/assets/8258226/8780a5d4-ff9d-44c6-9cfc-513f189f6eb3)

**Comment by yellowisher** [comment]
You have to add `using Cysharp.Threading.Tasks;` on the top of your script.

**Comment by ebolefeysot** [comment]
Yes, I did it, and vs will suggest it anyway.

**Comment by yellowisher** [comment]
Then I doubt the scripting symbol. Try adding `#define UNITASK_DOTWEEN_SUPPORT` directly on the top of your script.

**Comment by ebolefeysot** [comment]
I added the define, no changes...
I search for UNITASK_DOTWEEN_SUPPORT in solution and found it in script.csproj, probably added by unity.
Is there a file to look for in solution where the AsUniTask extension is defined ?

**Comment by yellowisher** [comment]
Its[ DOTweenAsyncExtensions.cs](https://github.com/Cysharp/UniTask/blob/master/src/UniTask/Assets/Plugins/UniTask/Runtime/External/DOTween/DOTweenAsyncExtensions.cs).

**Comment by ebolefeysot** [comment]
The file is found in packageCache. Code is greyed out as if the symbol was not defined. I commented the #if and code appears as usual, but I still get the errors. Maybe the source code is not used from this location...
This could solve the AsUniTask error, when what about the other one ?

I updated to latest version 2.3.3, but I still get the errors.

**Comment by ebolefeysot** [comment]
I checked the asmdef and references are there. To be sure it is refreshed, I switch to using plain text for libraries in unity), and then back to using guid.
I closed all and restarted my pc, but I still can't use the extensions.

**Comment by ebolefeysot** [comment]
Finally it's working !
I don't know exactly why, but I can point some actions I did:
I added unitask.dotween reference in the project. I had just added the main unitask library during installation. But it doesn't solve the problem.
Then I manually edited the scripts.asmdef file (see my comment above about guid).
I restart my pc (a pending windows update has been installed).
And today it works !
Hope it can help someone else...

**Comment by mcread29** [comment]
I'm having a similar issue, specifically with [DOTweenAsyncExtensions.cs](https://github.com/Cysharp/UniTask/blob/master/src/UniTask/Assets/Plugins/UniTask/Runtime/External/DOTween/DOTweenAsyncExtensions.cs). I've followed all the steps to import, reimported the specific plugins folders, reimported all, and still get errors in the file related to not being able to find the namespace "DG". My other team members are not having this issue, and on my primary PC I haven't encountered this at all. Does anyone have any suggestions on why this might occur or how to fix it?

**Comment by ZhengYiHu** [comment]
You can add `UNITASK_DOTWEEN_SUPPORT` directly in the project settings symbols.
This fixed it for me.
<img width="631" alt="Screenshot 2024-03-22 at 14 40 24" src="https://github.com/Cysharp/UniTask/assets/33153763/95a8545f-69b4-4890-ab46-debec138a265">

**Comment by Mojtabaohz** [comment]
@ZhengYiHu Thanks, it is the solution for the issue.
