### ISSUE TITLE
Custom GetAwaiter() problem

### ISSUE THREAD

**Issue by FelixGameNot** [Cysharp/UniTask#477]
I have a popup viewer with methods described below. The main idea of this is to wait for the user's click using await. (I know that the simplest way is to use WaitUntil, but it uses the PlayerLoop cycle to check if the action is done, so I decided that it's not suitable for me.) So I created an awaitable struct. But something went wrong. Looks like on the second click, the code just skips the part with await.
How it looks in play mode:
Waiting for popup and text to show
Console output: "Count: 3 text: SomeText4"
Clicking,
Console output: "Count: 2 text: SomeText3"
Clicking,
Console output: "Count: 1 text: SomeText2"
Console output: "Count: 0 text: SomeText1"
Clicking,
Waiting for popup and text to hide

    public async UniTask OpenAndWaitForHide(List<TextLocalization> story)
	{
		_audioSystem.Play(phoneCallSound);
		await UniTask.Delay((int)(soundDelay * 1000));
		storyAnimator.ShowText("");
		await windowActivator.Activate();

		_messagesQueue = new Queue<TextLocalization>();

		foreach (TextLocalization textLocalization in story)
		{
			_messagesQueue.Enqueue(textLocalization);
		}

		while (_messagesQueue.Count > 0)
		{
			var text = _messagesQueue.Dequeue().Localization[_langIndex];
			Debug.Log($"Count: {_messagesQueue.Count} text: {text}");
			storyAnimator.ShowText(text);
			LayoutRebuilder.ForceRebuildLayoutImmediate(content);
			storyAnimator.StartShowingText(true);
			await new PopupClosedAwaitable(this); // the problem is happening here
		}

		await new PopupHidAwaitable(this);
	}

	public void OnClickClose()
	{
		if (_messagesQueue.Count > 0)
		{
			CloseClicked?.Invoke();
			return;
		}
		
		CloseClicked?.Invoke();
		_audioSystem.Play(hangUpSound);
		Close();
	}

``

	public struct PopupClosedAwaitable
	{

		private IPopupAwaiter _popupAwaiter;

		public PopupClosedAwaitable(IPopupAwaiter popupAwaiter)
		{
			_popupAwaiter = popupAwaiter;
		}
	
		public PopupCloseAwaiter GetAwaiter()
		{
			return new PopupCloseAwaiter(_popupAwaiter);
		}
	
		public struct PopupCloseAwaiter : INotifyCompletion
		{
			private IPopupAwaiter _popupAwaiter;
			private Action _continuation;

			public PopupCloseAwaiter(IPopupAwaiter popupAwaiter)
			{
				_popupAwaiter = popupAwaiter;
				_continuation = null;
			}

			public bool IsCompleted => false;

			public void GetResult() { }
	
			public void OnCompleted(Action continuation)
			{
				_continuation = continuation;
				_popupAwaiter.CloseClicked += OnClosed;
			}

			private void OnClosed()
			{
				_popupAwaiter.CloseClicked -= OnClosed;
				_continuation.Invoke();
			}
		}
	}

I tried to check what happened in debug mode, and on the last click, I encountered an exception. I have seen this exception before in other parts of the game, but I never understood what triggers it. It seems to occur randomly from time to time. (I had never seen this exception before I started using my custom classes with GetAwaiter())

`NullReferenceException: Object reference not set to an instance of an object
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask1[TStateMachine].Run () (at Assets/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:189)
Popups.PopupClosedAwaitable+PopupCloseAwaiter.OnClosed () (at Assets/Scripts/Runtime/Game/Popups/PopupClosedAwaitable.cs:46)
(wrapper unbox) Popups.PopupClosedAwaitable+PopupCloseAwaiter.OnClosed()
PhoneCallPopup.OnClickClose () (at Assets/Scripts/YNewFeatureBeforeReview/PhoneCallPopup.cs:93)
UnityEngine.Events.InvokableCall.Invoke () (at <4746c126b0b54f3b834845974d1a9190>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <4746c126b0b54f3b834845974d1a9190>:0)
UnityEngine.UI.Button.Press () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction\1[T1] functor) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:501)`

**Comment by timcassell** [comment]
If you change the `struct PopupCloseAwaiter` to `class PopupCloseAwaiter` does it work?

**Comment by FelixGameNot** [comment]
> If you change the `struct PopupCloseAwaiter` to `class PopupCloseAwaiter` does it work?

Wow, that helps. I'm new to writing custom awaiters, and I saw that in any case, programmers use structs for this. Why does it work with classes? I thought that it must be a value type like TaskAwaiter.

**Comment by timcassell** [comment]
Structs are used for performance reasons to avoid an extra allocation. The problem you have is the delegate points to a different instance of the struct.

Recommended reading: https://stackoverflow.com/questions/5086472/c-sharp-delegate-to-struct-method
https://stackoverflow.com/questions/23609110/why-are-awaiters-async-await-structs-and-not-classes-can-classes-be-used

**Comment by FelixGameNot** [comment]
> Structs are used for performance reasons to avoid an extra allocation. The problem you have is the delegate points to a different instance of the struct.
> 
> Recommended reading: https://stackoverflow.com/questions/5086472/c-sharp-delegate-to-struct-method https://stackoverflow.com/questions/23609110/why-are-awaiters-async-await-structs-and-not-classes-can-classes-be-used

Thank you for the reply with useful links.
