### ISSUE TITLE
UniTask.Delay(1000);  Time interval is not 1000ms?

### ISSUE THREAD

**Issue by Chenxi-Peng** [Cysharp/UniTask#478]
void Start()
    {
        TestAsync().Forget();
    }
   
    async UniTask TestAsync()
    {
        DebugLog.LogTime("Delay ");
        await UniTask.Delay(1000);
        // await Task.Delay(1000);
        DebugLog.LogTime(" end");
    }

![image](https://github.com/Cysharp/UniTask/assets/73510165/d97db030-244e-4667-b2c1-b4e75eea783c)

Why is the time interval between the two times displayed in the log not 1000ms but 1300+ms?
Multiple tests have shown that it is always over 1300ms. 
However, after switching to the new code, the accuracy improved.

    async UniTask TestAsync()
    {
        DebugLog.LogTime("Delay ");
        // await UniTask.Delay(1000);
        await Task.Delay(1000);
        DebugLog.LogTime(" end");
    }

![image](https://github.com/Cysharp/UniTask/assets/73510165/9f85a9e9-a02f-4781-806d-aab0858d0b98)

Unity Version: 2021.3.13f1
UniTask Version: 2.3.1

**Comment by 12Acorns** [comment]
After doing a quick test with this script:
   ```
 public static async UniTaskVoid startTest()
    {
        List<UniTask> _tasks = new();
        for (int i = 0; i < 100; i++)
        {
            _tasks.Add(testAsync());
        }
        await UniTask.WhenAll(_tasks);
    }
    private static async UniTask testAsync()
    {
        System.Diagnostics.Stopwatch _stopWatch = new();
        _stopWatch.Start();
        await UniTask.Delay(1000);
        _stopWatch.Stop();
        Debug.Log($"Total elapsed time is {_stopWatch.ElapsedMilliseconds}");
        Debug.Log($"Error from 1000 milliseconds is roughly {_stopWatch.ElapsedMilliseconds - 1000} \n" +
            $"where a - (negitive) is less than 1000 and + (positive) is more than a thousand.");
        _stopWatch.Reset();
    }
```
I get similar results to you with all being roughly 300-nearly 400 milliseconds longer than 1000 milliseconds.

**Comment by hadashiA** [comment]
Hi, This is not a UniTask problem.

The problem is caused by Unity's Time.deltaTime.

Unity is actually taking a few hundred milliseconds to transition from frame 1 to frame 2. Despite this, Time.deltaTime only reports 0.01999sec.

Below is a log of the internal time elapsed transition.

```

[Frame 1] DelayPromise.Create        deltaTime=0.01999999 elapsed=0                                     elapsed(Stopwatch)=0
[Frame 2] DelayPromise.MoveNext deltaTime=0.01999999 elapsed=0.0199999921023846 elapsed(Stopwatch)=0.619
[Frame 3] DelayPromise.MoveNext deltaTime=0.06400681 elapsed=0.0840067975223064 elapsed(Stopwatch)=0.684
[Frame 4] DelayPromise.MoveNext deltaTime=0.0106233    elapsed=0.0946300970390439 elapsed(Stopwatch)=0.694
...
...
[Frame 160] DelayPromise.MoveNext deltaTime=0.02163821 elapsed=1.01724758418277 elapsed(Stopwatch)=1.617
```

Also, if the same test is started after frame 3, the results are more accurate.

```
[Frame 160] DelayPromise.Create       deltaTime=0.02163821   elapsed=0                                     elapsed(StopWatch)=0
[Frame 161] DelayPromise.MoveNext deltaTime=0.01365158   elapsed=0.0136515805497766 elapsed(StopWatch)=0.007
[Frame 162] DelayPromise.MoveNext deltaTime=0.00754893 elapsed=0.0212005106732249 elapsed(StopWatch)=0.014
...
...
[Frame 335] DelayPromise.MoveNext deltaTime=0.0182047 elapsed=1.01220421725884 elapsed(StopWatch)=1.005
```

Please refer to the Unity forum for more information on the topic of Time.deltaTime accuracy.

And, UniTask.Delay has an option to use realtime.
