### ISSUE TITLE
Issue starting UniTask

### ISSUE THREAD

**Issue by Nyankoo** [Cysharp/UniTask#48]
I'm most definetly missing something, but I want to start an async method like this:

`new UniTask(() => doSomethingAsync());`

But the code in doSomethingAsync is never called.

**Comment by phongsoyenmoc** [comment]
new UniTask(...); only create UniTask Object not run it.

if you need start method async you must call with await

```cs
public bool check = false;

    private async void Start()
    {
        UniTask uniTask = new UniTask(DoSomethingAync); //create task like object
        await uniTask; 
        
        
        //or
        await UniTask.Run(DoSomethingAync);
    }

    private async UniTask DoSomethingAync()
    {
        Debug.Log("Start");
        await UniTask.WaitUntil(() => check);
        Debug.Log("Done!");
    }
```

**Comment by Nyankoo** [comment]
@phongsoyenmoc Just a quick follow-up about your answer:

What happens when I only write "UniTask.Run(DoSomethingAync);", so not including the "await"? Does that make any difference when the method is **not** async?

I'm having a few difficulties figuring out how to start my UniTasks:

- StartCoroutine(UniTask.ToCoroutine(DoSomethingAync));
- UniTask.Run(DoSomethingAync);
- UniTask.Run(DoSomethingAync).Forget();

**Comment by phongsoyenmoc** [comment]
use UniTask.Run to call the method, not as part of the implementation of the method
use UniTask.Run to call cpu bound methods.
both  `void DoSomething()` and `UniTask DoSomethingAsync` are cpu bound methods

you can see source code
```cs
        public static async UniTask<T> Run<T>(Func<T> func, bool configureAwait = true)
        {
            await UniTask.SwitchToThreadPool();
            if (configureAwait)
            {
                try
                {
                    return func();
                }
                finally
                {
                    await UniTask.Yield();
                }
            }
            else
            {
                return func();
            }
        }
``

**Comment by phongsoyenmoc** [comment]
Well, there are ways to get started with Unitask.
Choose which method is easy to use for you and depending on the context

With Forget () you can suppress the compiler's await warning

**Comment by Nyankoo** [comment]
So StartCoroutine(UniTask.ToCoroutine(DoSomethingAync)); is the same as UniTask.Run, or should I prefer "UniTask.Run" when possible?

**Comment by phongsoyenmoc** [comment]
yup it same :smile:

**Comment by Nyankoo** [comment]
@phongsoyenmoc I'm running into an issue when using `UniTask.Run(DoSomethingAync).Forget();` vs `StartCoroutine(UniTask.ToCoroutine(DoSomethingAync));` together with `using(UnityWebRequest www = UnityWebRequest.Post(myURL, postData))`.

When using `StartCoroutine(UniTask.ToCoroutine(DoSomethingAync));`, everything works, but when I use `UniTask.Run(DoSomethingAync).Forget();`, I'm getting the following exception:
`UnityException: Create can only be called from the main thread.`

Any idea why this is happening? You mentioned that both ways are technically the same, so I'm wondering why they behave differently.

**Comment by phongsoyenmoc** [comment]
@Nyankoo because UniTask not run in mainthread where the unity api needs to be able to run.
In this case you are using the UnityWebRequest API of unity so running it with UniTask will throw an exception.

**Comment by phongsoyenmoc** [comment]
or you can try this in document 
```cs
// get async webrequest
    async UniTask<string> GetTextAsync(UnityWebRequest req)
    {
        var op = await req.SendWebRequest();
        return op.downloadHandler.text;
    }

    var task1 = GetTextAsync(UnityWebRequest.Get("http://google.com"));
    var task2 = GetTextAsync(UnityWebRequest.Get("http://bing.com"));
    var task3 = GetTextAsync(UnityWebRequest.Get("http://yahoo.com"));

    // concurrent async-wait and get result easily by tuple syntax
    var (google, bing, yahoo) = await UniTask.WhenAll(task1, task2, task3);
```
inside UniTask.Run has call await UniTask.SwitchToThreadPool(); so If you must use the api unity, avoid using UniTask.Run

**Comment by Nyankoo** [comment]
@phongsoyenmoc So when using `StartCoroutine(UniTask.ToCoroutine(DoSomethingAync));`, the task is always run on the main thread?

**Comment by phongsoyenmoc** [comment]
@Nyankoo yup, DoSomethingAync is converted to IEnumerator and runs on coroutine so it is run on mainthread

**Comment by Nyankoo** [comment]
@phongsoyenmoc Got it!
So when using `UnityWebRequest`, is it preferred to use the coroutine-way or how you posted it above, encapsulating only the `SendWebRequest` in the task?

**Comment by phongsoyenmoc** [comment]
Basically it's the difference between coroutine and async, I don't recommend it but async is being used as best practices.

**Comment by Nyankoo** [comment]
@phongsoyenmoc So you would use Unity's standard coroutine and don't use UniTask in general?
