### ISSUE TITLE
Editor tasks can't run when EditorApplication.isPaused

### ISSUE THREAD

**Issue by thebne** [Cysharp/UniTask#490]
```cs
        private static void ForceEditorPlayerLoopUpdate()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode || EditorApplication.isCompiling || EditorApplication.isUpdating)
            {
                // Not in Edit mode, don't interfere
                return;
            }
            //...
```

This block prevents EditorApplication.update tick to progress editor tasks.
However, removing this check or altering it to `(EditorApplication.isPlayingOrWillChangePlaymode && !EditorApplication.isPaused)` causes "regular" (game) tasks to progress too.

I guess it would the solution would require to run the editor tasks on a different runner loop..?

**Comment by thebne** [comment]
Another weird fact about editor tasks:

Consider the following code
```cs
var metadataResponse = await s3Client.GetObjectMetadataAsync(metadataRequest, token);
```

This is a `Task`, and this code works well.
However when the editor is paused, this causes the task to hang forever (maybe because it's running on the main thread and Waiting to pass the result back to the main thread? I'm not 100% sure what's going on there).

This solved it, but we can't fully explain why:
``cs
                                    GetObjectMetadataResponse metadataResponse;
                                    await using (UniTask.ReturnToMainThread())
                                    {
                                        await UniTask.SwitchToThreadPool();
                                        metadataResponse =
                                            await s3Client.GetObjectMetadataAsync(metadataRequest, token);
                                    }
```

**Comment by neuecc** [comment]
discussed in related PR #491 and closed.
