### ISSUE TITLE
ArgumentNullException: Value cannot be null. when awaiting UnityWebRequest

### ISSUE THREAD

**Issue by defStudios** [Cysharp/UniTask#501]
I'm loading textures with this code

```
public static async UniTask<Texture2D> DownloadImage(string url, CancellationToken? cancellationToken)
{
    try
    {
        var request = UnityWebRequestTexture
            .GetTexture(url)
            .SendWebRequest();
            
        if (cancellationToken.HasValue)
            request.WithCancellation(cancellationToken.Value);
    
        using var result = await request;
    
        return ((DownloadHandlerTexture)result.downloadHandler).texture;
    }
    catch (Exception e)
    {
        if (e is not UnityWebRequestException)
            throw;
    
        return null;
    }
}
```

Textures are being loaded correctly, but there are errors in the console

```
ArgumentNullException: Value cannot be null.
Parameter name: _unity_self
Cysharp.Threading.Tasks.Internal.UnityWebRequestResultExtensions.IsError (UnityEngine.Networking.UnityWebRequest unityWebRequest) (at ./Library/PackageCache/com.cysharp.unitask@c170af5642/Runtime/Internal/UnityWebRequestExtensions.cs:17)
Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () (at ./Library/PackageCache/com.cysharp.unitask@c170af5642/Runtime/UnityAsyncExtensions.cs:907)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () (at ./Library/PackageCache/com.cysharp.unitask@c170af5642/Runtime/Internal/PlayerLoopRunner.cs:175)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.Internal.<>c:<.ctor>b__9_0(Exception) (at ./Library/PackageCache/com.cysharp.unitask@c170af5642/Runtime/Internal/PlayerLoopRunner.cs:25)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore() (at ./Library/PackageCache/com.cysharp.unitask@c170af5642/Runtime/Internal/PlayerLoopRunner.cs:189)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update() (at ./Library/PackageCache/com.cysharp.unitask@c170af5642/Runtime/Internal/PlayerLoopRunner.cs:145)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run() (at ./Library/PackageCache/com.cysharp.unitask@c170af5642/Runtime/Internal/PlayerLoopRunner.cs:104)
```

I'm using the latest version of UniTask.

**Comment by defStudios** [comment]
Looks like if I remove "using" keyword the error goes away. 
Am I not supposed to use this keyword? Or I should call Dispose() manually?

**Comment by Stever1388** [comment]
I tried replicating the issue and I couldn't. But I think your issue might be the scope of your using statement. After leaving the block, the object is disposed. Your block is empty, so your `return ((DownloadHandlerTexture)result.downloadHandler).texture;` technically occurs after the request was disposed. I think you are only getting lucky that it's not causing an issue. [Microsoft's `using` reference mentions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using):

> In the preceding example, after control leaves the using statement, a disposable instance remains in scope while it's already disposed. If you use that instance further, you might encounter an exception, for example, [ObjectDisposedException](https://learn.microsoft.com/en-us/dotnet/api/system.objectdisposedexception). That's why we recommend declaring a disposable variable within the using statement or with the using declaration.

I think you might be better off doing something like this instead:
```
try
{
    using (UnityWebRequest request = UnityWebRequestTexture.GetTexture(url))
    {
        if (cancellationToken.HasValue)
            await (request.SendWebRequest().WithCancellation(cancellationToken.Value));
        else await request.SendWebRequest();
        return DownloadHandlerTexture.GetContent(request);
    }
}
```

This has the `request` completely within the `using` scope, so it won't get disposed early. Also, `DownloadHandlerTexture` has a `GetContent` convenience function to get the texture!

**Comment by defStudios** [comment]
Thanks for the detailed answer! (Especially for the catch part)

After some testing I can be sure that the reason of error is this part

```
if (cancellationToken.HasValue)
    request.WithCancellation(cancellationToken.Value);
```

So I did what you advised and error disappeared.

**Comment by Stever1388** [comment]
> P.S. Turns out I can use "using" statement without scope and it will work perfectly.

You are correct, I missed the part in the reference that I linked that mentions how that works:

> You can also use a using declaration that doesn't require braces: `using StreamReader reader = File.OpenText(filePath);` When declared in a using declaration, a local variable is disposed at the end of the scope in which it's declared. In the preceding example, disposal happens at the end of a method.

So the way you had it previously should have worked (in theory). I think applying the token after sending the request was what was probably messing it up.

One last thing, to clean up the token part, you can change it to this, which follows C# standard on having a token at the end:

```
public static async UniTask<Texture2D> DownloadImage(string url, CancellationToken cancellationToken = default)
{
    try
    {
        using var request = UnityWebRequestTexture.GetTexture(url);
        
        await request.SendWebRequest().WithCancellation(cancellationToken);
            
        return DownloadHandlerTexture.GetContent(request);
    }
    catch (UnityWebRequestException e)
    {
        return null;
    }
}
```

You can see this is how it's done for things like [`System.IO.File.ReadAllBytesAsync`](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.readallbytesasync?view=net-7.0). I've tested it this morning and seems to work fine (with UnityWebRequest).
