### ISSUE TITLE
Delayed reporting of an unhandled exception during a UniTask

### ISSUE THREAD

**Issue by joelmalone** [Cysharp/UniTask#51]
Bug:

When in Play Mode, when an async method throws an exception, and the exception is unhandled, the exception doesn't appear in the console window until after play mode exits.

Expected behaviour:

The exception would appear in the console immediately when thrown.

Repro:

* Create an empty scene.
* Add a single `GameObject` and attach the following component.
* Enter Play Mode.
* Look at the console and confirm that you see a message which indicates an exception is about to be thrown.
* Confirm that the exception does not appear in the console.
* Exit Play Mode.
* Confirm that the exception is now reported to the console.

What should happen:

* The exception should be reported to the console immediately after the initial message, i.e. while still in Play Mode.

```c#
using System;
using UnityEngine;
using UniRx.Async;

public class Repro : MonoBehaviour
{

    protected async UniTask Start()
    {
        await UniTask.Yield();

        Debug.Log("An exception will be thrown immediately, but you won't see it until you exit play mode.");

        throw new ApplicationException("This exception won't surface until exiting play mode.");
    }
}
```

**Comment by juliomg91** [comment]
I just came across the same issue. When using Unitask, exceptions are ignored most of the time. They only will be thrown when exiting playing mode if you have this in the UniTaskScheduler: 

**public static UnityEngine.LogType UnobservedExceptionWriteLogType = UnityEngine.LogType.Exception;**

If not, I won't even get a warning. Any solution for this?

**Comment by NoxMortem** [comment]
This is really of an annoying behaviour and matches an exception in a un-awaiteted Task. However, I'd really prefer to get an Exception when it happens, it would make it really easier during playmode to find potential errors.

**Comment by neuecc** [comment]
Unprocessed UniTasks (and tasks) will be sent to UniTaskScheduler.UnobservedTaskException at GC.
This is because it's hard to tell if the UniTask is something that will be await in the future (raise exceptions) or if it will disappear immediately.
By using UniTaskVoid, it will be marked as not await, so it will be reported immediately.
Alternatively, you can use Forget() for the same purpose.

**Comment by NoxMortem** [comment]
@neuecc that still does not explain why an awaited UniTask does not **immediatly** unwrap the exceptions - which is the default behaviour for Task? It is clear why a UniTask that is **not** awaited does not unwrap the exception (it could be awaited _later_)
