### ISSUE TITLE
GC.Alloc documentation 'solution' is wrong

### ISSUE THREAD

**Issue by AmitWhalo** [Cysharp/UniTask#525]
Hello,

I think that the current documentation regarding allocations on the profiler is misleading (unless I'm missing something).

For further context, what made me look up this issue was the fact that I see a lot of GC.Alloc called from within the UniTaskLoopRunnerUpdate:

![image](https://github.com/Cysharp/UniTask/assets/121756716/b32558fc-c2d4-403c-831b-2296deba7c2d)

Looking for previous issues on the subject suggests that the documentation is [not](https://github.com/Cysharp/UniTask/issues/380) well [understood](https://github.com/Cysharp/UniTask/issues/448).

The replies, [at least for the 2nd issue](https://github.com/Cysharp/UniTask/issues/448), have turned back the responsibility on the OP. Can you elaborate on that? Do these allocation stem from a currently running task, or are they from the AsyncStateMachine, as you state in your documentation?
 
The current README page states the following:

---
## Allocation on Profiler
In UnityEditor the profiler shows allocation of compiler generated AsyncStateMachine but it only occurs in debug(development) build. C# Compiler generates AsyncStateMachine as class on Debug build and as struct on Release build.

Unity supports Code Optimization option starting in 2020.1 (right, footer).

__You can change C# compiler optimization to release to remove AsyncStateMachine allocation in development builds. This optimization option can also be set via Compilation.CompilationPipeline-codeOptimization, and Compilation.CodeOptimization.__
---

I've highlighted in bold what I think is the root of the issue - the allocations will STILL exist on Development *builds* (which I assume most Unity developers use for their profiling), even if the Compilation Code Optimizations are turned on in the editor (Mode: Release, as stated in the documentation). 
These settings only effect the Editor runtime, not builds. If you create a development build for remote profiling from an editor that has Optimizations turned on, it would still not use these optimizations.

Am I missing something? Can you produce a build that can remote-profile while not seeing the GC.Alloc? It would be delightful if it was so.

If that's indeed the situation - it should be declared so plainly on the README page. Something like "If you are profiling your game, you would see these allocations, and there is no way to profile your game without seeing them".

**Comment by neuecc** [comment]
I believe it's an issue with what's registered in Update.

**Comment by jarrodspurrier** [comment]
I'm encountering the same issue. I have a number of allocation free methods that I converted over to using UniTask, and now my builds are showing allocations. Is there any world where I can create a standalone build with Deep Profiling support and not see the allocations from UniTask? And if not, how are you even validating that your code is allocation free?

**Comment by timcassell** [comment]
@jarrodspurrier If Unity builds with DEBUG when Deep Profiling is enabled, there's nothing anyone can do about that. The C# compiler decides whether to produce a class or struct based on that.

> how are you even validating that your code is allocation free?

I verified it myself using BenchmarkDotNet. See https://github.com/timcassell/CSharpAsynchronousBenchmarks
