### ISSUE TITLE
Using await UniTask.NextFrame() can result in the code after the await being executed at an incorrect timing.

### ISSUE THREAD

**Issue by stnaw** [Cysharp/UniTask#527]
Assuming the current loop consists of three events: frameStart, frameUpdate, and frameEnd.

When I use await UniTask.NextFrame() between the frameStart and frameUpdate events, the code after this await will continue executing after the current frame's frameUpdate event.

When I use await UniTask.NextFrame() between the frameUpdate and frameEnd events, the code after this await will only continue executing after the next frame's frameUpdate event. (Based on the literal meaning of the API, this call is correct as we want to execute the code after await in the next frame.)

Although both calls use await UniTask.NextFrame(), they are called at different times. After examining UniTask's source code, it appears to be true. I hope this issue can be fixed. :)

**Comment by neuecc** [comment]
You can choose either Yield or NextFrame as needed.
