### ISSUE TITLE
AsyncMethodBuilderAttribute conflicts with imported type

### ISSUE THREAD

**Issue by Hemaolle** [Cysharp/UniTask#53]
Still getting the warning described in https://github.com/Cysharp/UniTask/issues/13. Using Unity 2018.4.17f1 and .NET 4.x compatibility level.

```
The type 'AsyncMethodBuilderAttribute' in
'XXX\Assets\ThirdParty\UniRx.Async\CompilerServices\AsyncMethodBuilderAttribute.cs'
conflicts with the imported type 'AsyncMethodBuilderAttribute' in 'System.Threading.Tasks.Extensions, Version=4.1.0.0,
Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Using the type defined in
'XXX\Assets\ThirdParty\UniRx.Async\CompilerServices\AsyncMethodBuilderAttribute.cs'.
```

**Comment by neuecc** [comment]
UniTask's itself is internal but if others are public, can not treat it.
For workaround, remove UniTask's AsyncMethodBuilderAttribute.

**Comment by Hemaolle** [comment]
Thanks for the workaround. I wonder if the UniTask could just use the AsyncMethodBuilderAttribute from `System.Threading.Tasks.Extensions`?

**Comment by neuecc** [comment]
That's right, the AsyncMethodBuilderAttribute is fine as long as the hint to the compiler defines the one with the same name.

By the way, this seems to be only Warning to the place where you are using it, so I tried to suppress the Warning.
Now you may not have to deal with anything.
https://github.com/Cysharp/UniTask/commit/74738ab13e1197b9136c4843fcf89ac5b538ab38
