### ISSUE TITLE
How can I await unitask in property accessor

### ISSUE THREAD

**Issue by zrp2016** [Cysharp/UniTask#539]
```c#
public class ATest
{
private static ATest _instance;

public static ATest Instance
{
    get
    {
        if (_instance == null)
        {
            _instance = new ATest();
            await _instance.InitAsync(); //the writing is wrong,how to deal with it?
        }
        return _instance;
    }
}
public void Do()
{

}
async UniTask InitAsync()
{
    await UniTask.Yield();
   
}
}
``` 
see code above,How can I await "InitAsync()" in property accessor?

**Comment by timcassell** [comment]
https://stackoverflow.com/questions/6602244/how-to-call-an-async-method-from-a-getter-or-setter

**Comment by zrp2016** [comment]
> https://stackoverflow.com/questions/6602244/how-to-call-an-async-method-from-a-getter-or-setter

thanks bro

**Comment by zrp2016** [comment]
```c#
 /// <summary>
        /// Returns the default material for the graphic.
        /// </summary>
        public virtual Material defaultMaterial
        {
            get { return defaultGraphicMaterial; }
        }
``` 
such as this virtual method from Graphic.cs of com.unity.ugui, how can I override it to make it as an awaitable property,as show following:
```c#
public override UniTask<Material> defaultMaterial =>await LoadMaterial() ?? base.defaultMaterial; // this writing is wrong
``` 
any suggestion,thanks in advance!And I don't want to change the source code in  Graphic.cs

**Comment by hadashiA** [comment]
@zrp2016 Maybe your question is not this repo issue .
- You cannot use await outside of an async context.
- If not async, the property/method must return value as  follows declared signature. UniTask must be returned in this case, e.g) `UniTask.FromResult(defaultMaterial)`.

BTW, I don't think making a property async is something that should be encouraged. You can use the async method.
