### ISSUE TITLE
Maybe I found a bug about UnityWebRequest

### ISSUE THREAD

**Issue by yomunsam** [Cysharp/UniTask#54]
https://github.com/Cysharp/UniTask/blob/50ba93f9517886818ec70da50a9c90271983726a/Assets/UniRx.Async/UnityAsyncExtensions.cs#L734

Hello, When I load some files from StreamingAssets by `UnityWebRequest` , I found that if the value of `this.statue` at the beginning is not `AwaiterStatus.Succeeded`, it will never become `AwaiterStatus.Succeeded` again,

But not very sure
I do n’t reproduce this problem every time

**Comment by yomunsam** [comment]
Sorry, The description above seems a bit wrong.
But i have new discoveries:

![image](https://user-images.githubusercontent.com/24813704/76090147-01804b00-5ff6-11ea-96a5-ab13f4bc59c7.png)

If `this.status` has been `AwaiterStatus.Succeeded` from the beginning, the `OnCompleted` `continuation` never seems to be called.

**Comment by yomunsam** [comment]
Hello i am here again.
The previous description was not very accurate, but I just discovered something.

i modified your code like this
![image](https://user-images.githubusercontent.com/24813704/76141864-07803580-60a3-11ea-973b-f5858f1cffe2.png)

and this code is indeed executed
![image](https://user-images.githubusercontent.com/24813704/76141892-48784a00-60a3-11ea-86c6-44a40e837e82.png)

If `isDone` in Unity's `UnityWebRequestAsyncOperation` is already `true`, the function added after 
 `completed` will not be executed. This means that the entire `await` is stuck

**Comment by yomunsam** [comment]
despair
![image](https://user-images.githubusercontent.com/24813704/76189577-06bbe080-6216-11ea-9d46-631ae846a46d.png)

![image](https://user-images.githubusercontent.com/24813704/76189591-0facb200-6216-11ea-9c62-216ea5ef2008.png)

![image](https://user-images.githubusercontent.com/24813704/76189629-25ba7280-6216-11ea-98f5-6f1d78fc016f.png)

**Comment by neuecc** [comment]
see the PR #55

**Comment by yomunsam** [comment]
Sorry it's been so long since I've seen this.
I tried your new design and didn't find this problem.
Thanks a lot.

**Comment by yomunsam** [comment]
> see the PR #55

Sorry it's been so long since I've seen this.
I tried your new design and didn't find this problem.
Thanks a lot.
