### ISSUE TITLE
UniTask runs one frame even after exit PlayMode.

### ISSUE THREAD

**Issue by OkdolLab** [Cysharp/UniTask#543]
public class TestA : MonoBehaviour
	{
		async UniTask OnEnable() {
			_cts = new CancellationTokenSource();
			try {
				print("try [frameCount:" + Time.frameCount + "]" + "[isPlaying:" + Application.isPlaying + "]");
				await UniTask.Delay(10000, cancellationToken: _cts.Token);
			}
			catch (Exception e) {
				print("catch [frameCount:" + Time.frameCount + "]" + "[isPlaying:" + Application.isPlaying + "]" + "\n" + e);
			}
			finally {
				print("finally [frameCount:" + Time.frameCount + "]" + "[isPlaying:" + Application.isPlaying + "]");
				GameObject gameObject = new GameObject();
			}
		}
		void OnDisable() {
			print("OnDisable, Cancel [frameCount:" + Time.frameCount + "]" + "[isPlaying:" + Application.isPlaying + "]");
			_cts.Cancel();
		}

		CancellationTokenSource _cts;
	}

When you quit immediately after playing with this code, a game object is created in the scene.

![image](https://github.com/Cysharp/UniTask/assets/41319038/f2f558e6-764e-4f5a-b815-bc0048f10fe9)

In my short opinion, Play Mode should not affect Edit Mode. but..

Is this behavior as intended?

**Comment by neuecc** [comment]
The additional slight rotation at the end mimics the UnitySynchronizationContext.
https://github.com/Unity-Technologies/UnityCsReference/blob/master/Runtime/Export/Scripting/UnitySynchronizationContext.cs#L117
Whether the current UniTask behavior is really appropriate is debatable.
