### ISSUE TITLE
EnumerableAsyncExtensions hides System.Linq extensions

### ISSUE THREAD

**Issue by xzwache** [Cysharp/UniTask#545]
Hello! We are faced with issue, that 

**EnumerableAsyncExtensions** from **namespace Cysharp.Threading.Tasks** hides the **System.Linq** extensions

Case:
You are trying to get all the strings from the of **List\<string\>** with **Select()** method.
What you are excepting to get: IEnumerable\<string\>
What you are actually get: "**Cannot convert expression type 'string' to return type 'Cysharp.Threading.Tasks.UniTask**"

This happens because you have a using of **Cysharp.Threading.Tasks** namespace, that contains this extensions. Until you manually add the System.Linq usage into the file it will show you a error or **potentially** can cause an unexpected behaviour

Our suggestion is to not use Cysharp.Threading.Tasks namespace for extensions, but add the proper naming like Cysharp.Threading.Tasks.IEnumerable.Extensions (for example) to make usage of such extensions obvious for developers

Thank you!

<img width="1152" alt="Screenshot 2024-02-14 at 09 57 56" src="https://github.com/Cysharp/UniTask/assets/31211748/871e4f66-6c15-4bbc-be31-135d4a9036a8">

**Comment by neuecc** [comment]
Thanks, I think this is not a good method name and should be changed to `SelectAwait`.

**Comment by xzwache** [comment]
Hello! As SelectAsync maybe? What do you think?

**Comment by neuecc** [comment]
For ***Async, we expect Task to be the return value.
The rule we use in Async LINQ is to use ***Await if we receive an async function as an argument (we also adopted the same thing in [R3](https://github.com/Cysharp/R3))
