### ISSUE TITLE
Missing UniTask.Wait implementation

### ISSUE THREAD

**Issue by GuidoBelluomo** [Cysharp/UniTask#546]
This is the way I've implemented it in a project, not sure if this is actually the right way.

```
        private static UniTask<T> Wait<T>(this UniTask<T> t)
        {
            static void WaitCoroutine(IEnumerator func) {
                while (func.MoveNext ()) {
                    if (func.Current is IEnumerator current) {
                        WaitCoroutine(current);
                    }
                }
            }
            
            WaitCoroutine(t.ToCoroutine());
            return t;
        }
```

**Comment by GuidoBelluomo** [comment]
Well then.

**Comment by maxgmer** [comment]
@GuidoBelluomo thanks for the implementation, as UniTask hasn't implemented it.
I don't know why it's marked as "completed".

**Comment by neuecc** [comment]
I don't know what you doing.
If the target UniTask is something that synchronizes with PlayerLoop, it will be a deadlock,
And wouldn't while(MoveNext()) consume a lot of CPU to begin with?
It doesn't look like it's even spinlocked.

If you want to wait synchronously, `AsTask()`, then Wait `Task<T>`.
However, such a synchronous wait will still deadlock in the PlayerLoop base.

**Comment by maxgmer** [comment]
@neuecc Didn't know about the "AsTask()", thanks!

The use-case I need Wait() for is to buy some time before game server hosting shuts down my server.
With async, game server hosting library is able to shut down my process when deallocation starts without giving me enough time to do clean-up.
