### ISSUE TITLE
Tasks don't seem to have an easy to get reference to their exception

### ISSUE THREAD

**Issue by GuidoBelluomo** [Cysharp/UniTask#547]
I need to get a faulted task's exception, normally this would be done with Task.Exception, so I'm expecting a UniTask.Exception property to be there as well. I haven't figured out a proper way to get this yet, been looking at the source code and I saw that MemoizeSource throws the exception when trying to get a faulted task's result. But I don't think this would work all the time:

```
            if (task.Status.IsFaulted())
            {
                try
                {
                    task.GetAwaiter().GetResult();
                }
                catch (Exception e)
                {
                    // Store
                }
            }
```

**Comment by GuidoBelluomo** [comment]
I'm trying to get a reference to the exception thrown by a task after everything is already done, if it is faulted. System.Threading.Tasks.Task seems to store a reference to the thrown exception inside the property, and I'm looking for an equivalent way to do it with UniTask.

This is what I'm talking about: https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.exception?view=net-8.0

**Comment by timcassell** [comment]
Here you go.

```cs
Exception? ex = null;
try
{
    await FuncAsync();
}
catch (Exception e)
{
    ex = e;
}
```

**Comment by GuidoBelluomo** [comment]
I don't think I'm making myself clear enough though. I don't need to call the function again. The function has already been called. I now have the reference to the task that has already ran. I need to get the exception that was thrown, and I need it at a later point in time.

I'm not writing new code I'm just porting a library to use UniTask. I'm not calling the shots here.

**Comment by timcassell** [comment]
You cannot do that with UniTask. You have to store the exception yourself if you need it. Once a UniTask has been awaited, it is not valid to use it again, so exposing synchronous properties doesn't make sense like what Task has (also Task is bloated with legacy stuff that really shouldn't be used in modern async programming).

**Comment by timcassell** [comment]
P.S. if this is something you're struggling with, you might want to check out my [ProtoPromise](https://github.com/timcassell/ProtoPromise) library. You can wait synchronously (like you asked in another issue) and store a `Promise.ResultContainer` (when using `WaitNoThrow`) for this purpose (instead of storing the task itself).

**Comment by GuidoBelluomo** [comment]
Okay thanks.
