### ISSUE TITLE
[Idea] .NET Core Player Loop

### ISSUE THREAD

**Issue by cshunsinger** [Cysharp/UniTask#551]
Currently the .NET core version of UniTask is stripped of anything that utilizes a player loop.

My suggestion is this: Could there be an optional "player loop"-like mechanism added to the UniTask for .NET Core? At it's core it would just be a single thread that runs around in a loop doing something similar to what the game loop in Unity does in UniTask, but without all of the other Unity stuff.

**Comment by neuecc** [comment]
My latest library R3 https://github.com/Cysharp/R3 uses FrameProvider abstraction.
The next major update, UniTask, will make a major change to the same specifications as R3.
