### ISSUE TITLE
Performance / Garbage Generation with this approach?

### ISSUE THREAD

**Issue by kenofori** [Cysharp/UniTask#558]
Hi there,

Im new to UniTask, If i want to call a method after x seconds delay, will following approach be fine and without generating garbage?
If its not good, please advise which approach to take.

Please advise

```csharp
//whenever i need to call a method with delay, WaitAndCallMethodAsync(1, someMethod);


 public static async UniTaskVoid WaitAndCallMethodAsync(int seconds, Action methodToCall)
        {
            await UniTask.Delay(seconds * 1000);

            methodToCall.Invoke();
        }
```

**Comment by neuecc** [comment]
That should work just fine.

**Comment by Guirie92** [comment]
Hi @kenofori, have you tested it on a build? On the Editor, it doesn't generate garbage, but in build, it does allocate on my end:
Unity 2022.3.15f1, UniTask version 2.5.4

**Comment by kenofori** [comment]
@neuecc please check another comment on this issue

> Hi @kenofori, have you tested it on a build? On the Editor, it doesn't generate garbage, but in build, it does allocate on my end: Unity 2022.3.15f1, UniTask version 2.5.4
