### ISSUE TITLE
When are UniTasks called during their update loops? Do they follow script execution order at all?

### ISSUE THREAD

**Issue by chris-janidlo** [Cysharp/UniTask#559]
For example, if a script at execution order position N queues up a UniTask, is that UniTask also updated at roughly execution order position N? Or are all UniTasks updated in a batch with essentially the same execution order position? (Depending of course on the order they were queued, as per https://github.com/Cysharp/UniTask/issues/453.) And if so, where in the script execution order are they updated?

**Comment by neuecc** [comment]
UniTask itself does not have a predefined position.
However, if you specify a PlayerLoopTiming(for example Delay), it will run at that specific point in the PlayerLoop.

**Comment by chris-janidlo** [comment]
Does that mean with PlayerLoopTiming set to FixedUpdate or Update, it can execute at any arbitrary position?
