### ISSUE TITLE
PrivacyManifest

### ISSUE THREAD

**Issue by soqman** [Cysharp/UniTask#567]
Could you kindly conduct a thorough check of the plugin to verify its compliance with the latest Apple requirements?

https://docs.unity3d.com/Manual/apple-privacy-manifest-policy.html
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by neuecc** [comment]
I think it's ok, but if you find any issues, please let me know.
