### ISSUE TITLE
How to implement ConfigureAwait(false) without Task?

### ISSUE THREAD

**Issue by Brice-xCIT** [Cysharp/UniTask#57]
Hello, I'm trying to emulate the behavior of `Task.ConfigureAwait(false)` with UniTask and so far have failed to do so. The expected behavior is that continuations of the configured task are run in another thread, until the method containing it ends. 

```
public async UniTask LongTask() {
  await new SwitchToThreadPoolAwaitable();

  // on background thread now.
  Debug.Log("On background thread");
}

public async UnitTask Consumer() {
  // here on the main thread.

  // this task will spawn a backgroud thread internally.
  await LongTask();

  // We're still on the background thread LongTask spawned.
  // I would rather be back on the main thread here, like ConfigureAwait() does...
}
```

I've tried using `SwitchToThreadPoolAwaitable` but the task does not switch back to the main thread after it completes, and therefore an outer method consuming the task continues running on the background thread.

I've tried using `SwitchToTaskPoolAwaitable` and this works fine since it does spawn a `Task`.

How could I go and implement this?

**Comment by igor84** [comment]
You can do it like this:

```
public async UnitTask LongTask() {
    await UniTask.SwitchToThreadPool();
    try {
        DoWorkOnBackgroundThread();
    } finally {
        await UniTask.SwitchToMainThread();
    }
}
```

**Comment by Brice-xCIT** [comment]
Thank you for your message! You are right that your solution does solve the issue of running a task in its own thread and coming back to the main thread afterwards.

However, apologies, I realize now that I improperly described my original issue. I'm looking for something equivalent to [ConfiguredTaskAwaitable](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.configuredtaskawaitable?view=netframework-4.8) that allows to schedule continuations (which are internal to a task) on another context:

```
public async UniTask LongTask()
{
	// Schedules the continuation to a background thread.
	await new UniTask().ConfigureAwait(false);

	// on background thread now.
	Debug.Log("On background thread");
}

public async UniTask Consumer()
{
	// here on the main thread.

	// this task will spawn a backgroud thread internally.
	await LongTask();

	// We are back on the main thread because by default the continuation of LongTask
	// is scheduled on the captured context (e.g. like await LongTask().ConfigureAwait(true)).
}
```

**Comment by neuecc** [comment]
ConfigureAwait means use or non use SynchronizationContext.
But UniTask does not use SynchronizationContext completely(performance reason and normally Unity does not require it), you should control thread manually.

igor84 answer is right.
Or, if you want to control it, use Task instead only that area.
