### ISSUE TITLE
Consuming in Unity a library that targets UniTask.NetCore

### ISSUE THREAD

**Issue by Mangatome** [Cysharp/UniTask#572]
I have a project on Unity 2020.3, in which I have installed UniTask using the package manager + git source.
I also have a library that targets netstandard2.0 and UniTask.NetCore. In the library, I expose a bunch of public async methods returning UniTask. 
I want to use the library in my Unity project. When I import the DLL, I get the error message:

```error CS0012: The type 'UniTask<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'UniTask, Version=2.5.4.0, Culture=neutral, PublicKeyToken=7a576c6e8fde454a'.```

My understanding is that the Unity-side assembly generated from the package does not have the same signature as the referenced assembly in the library-side.

So the question is: how can I consume this library in my Unity project?

**Comment by neuecc** [comment]
Currently, the DLLs distributed on NuGet have no compatibility.
In the future, there are plans to integrate them.

**Comment by Mangatome** [comment]
Thanks, it would be great to have.
I'm curious about what is missing for compatibility, though. To me it seems like the only issue is that the NetCore assembly is strong/signed and has a valid version e.g. 2.5.4.0, whereas the assembly Unity generates is unsigned and has version 0.0.0.0.
If the NetCore assembly wasn't signed and the Unity assembly had the same version, shouldn't this work in theory?

**Comment by neuecc** [comment]
NET Core ones have none of the same elements that one would expect, such as the absence of PlayerLoop.
Currently, think of them as different, just with the same namespace and name.

**Comment by LiskNK** [comment]
@Mangatome did you ever find a workaround for this?

**Comment by LiskNK** [comment]
That all makes sense. Thanks for laying out the strategy idea; I could see that working, especially if UniTask is stable enough that I don't really need to update it ever.

I think I'm going to take your route though and just rely on vanilla Tasks in my library code for the same reasons as you, and then just use AsUniTask() whenever calling library code from a Unity context. Not the prettiest, but feels safe.

**Comment by zoltowskiwojciech** [comment]
@neuecc anything has changed? Get similar problem.

**Comment by zoltowskiwojciech** [comment]
I'm using OpenAPI generator to autogenerate code for models and apis. It's using .NET Framework 4.7. It was modified to use UniTasks because it's supposed to be used by Unity clients.

**Comment by LiskNK** [comment]
I am developing a server-authoritative game that can also run offline. The server is a C# console app, the client is in Unity. I want to be able to share code between my server and client, and sometimes that involves async code. Since the server does not reference Unity (it's a .NET Core app), it would be very helpful if I could use UniTask in both.
