### ISSUE TITLE
OnInvokeAsync for Action?

### ISSUE THREAD

**Issue by seoyeon01** [Cysharp/UniTask#575]
I couldn't find it in the document,
It seems that using OnInvokeAsync allows UnityEvent to wait.

for example
  
```csharp
public UnityEvent  TestEvent;
public UnityAction TestAction1;
public Action      TestAction2;

private async UniTask TEST()
{
    await TestEvent.OnInvokeAsync(this.GetCancellationTokenOnDestroy());
}
```

But UnityAction, Action doesn't seem to be able to use something like OnInvokeAsync
Isn't UnityEvent, UnityAction, and Action all public delegate after all?

Why can't await Action.OnInvokeAsync?

**Comment by timcassell** [comment]
Only `Action` and `UnityAction` are delegates. `UnityEvent` is a special event type which is really just a regular class that adds delegates to internal lists. `UnityEvents` have `AddListener` and `RemoveListener` which makes it possible to await. Regular delegates have a special multi-cast implementation where when you `+=` subscribe and `-=` unsubscribe, it actually overwrites the original value, so you can't (un)subscribe generically.
