### ISSUE TITLE
UniTaskCompletionSource and AutoResetUniTaskCompletionSource example code

### ISSUE THREAD

**Issue by kenofori** [Cysharp/UniTask#581]
Hi there,
Could you please explain if following approach automatically returns the newly created instance to pool? If not could you please provide code example.
Thanks

```
public UniTask<int> WrapByUniTaskCompletionSource()
{
            var test = AutoResetUniTaskCompletionSource<int>.Create();
            test.TrySetResult(33);
            return await test.Task;
}
```

**Comment by kenofori** [comment]
Hi @neuecc I'm assuming you closed this because above code works right?
if thats the case can i use it as alternate of  CancellationTokenSource?

so in my noob brain, ill create completion source outside, and then cancel it to get debounce effect?
Please advise

**Comment by neuecc** [comment]
AutoReset... should not be used for complex things.
Unless you understand the entire contents, it is better to use a normal CompletionSource.
To begin with, it is dangerous to use it for anything other than simple scenarios.
