### ISSUE TITLE
 error CS0117: 'ArrayPool<Merge<T>.MergeSourceState>' does not contain a definition for 'Shared'

### ISSUE THREAD

**Issue by SiMaLaoShi** [Cysharp/UniTask#591]
Assets\Plugins\UniTask\Runtime\Linq\Merge.cs(82,54): error CS0117: 'ArrayPool<Merge<T>.MergeSourceState>' does not contain a definition for 'Shared'

Assets\Plugins\UniTask\Runtime\Linq\Merge.cs(83,69): error CS0117: 'ArrayPool<IUniTaskAsyncEnumerator<T>>' does not contain a definition for 'Shared'

Assets\Plugins\UniTask\Runtime\Linq\Merge.cs(152,45): error CS0117: 'ArrayPool<Merge<T>.MergeSourceState>' does not contain a definition for 'Shared'

Assets\Plugins\UniTask\Runtime\Linq\Merge.cs(153,55): error CS0117: 'ArrayPool<IUniTaskAsyncEnumerator<T>>' does not contain a definition for 'Shared'

Assets\Plugins\UniTask\Runtime\Linq\ToArray.cs(22,43): error CS0117: 'ArrayPool<TSource>' does not contain a definition for 'Shared'

Assets\Plugins\UniTask\Runtime\Linq\ToLookup.cs(125,43): error CS0117: 'ArrayPool<TSource>' does not contain a definition for 'Shared'

Assets\Plugins\UniTask\Runtime\Linq\ToLookup.cs(160,43): error CS0117: 'ArrayPool<TSource>' does not contain a definition for 'Shared'

Assets\Plugins\UniTask\Runtime\Linq\ToLookup.cs(199,43): error CS0117: 'ArrayPool<TSource>' does not contain a definition for 'Shared'

Assets\Plugins\UniTask\Runtime\Linq\ToLookup.cs(235,43): error CS0117: 'ArrayPool<TSource>' does not contain a definition for 'Shared'

Assets\Plugins\UniTask\Runtime\Linq\ToLookup.cs(273,43): error CS0117: 'ArrayPool<TSource>' does not contain a definition for 'Shared'

Assets\Plugins\UniTask\Runtime\Linq\ToLookup.cs(309,43): error CS0117: 'ArrayPool<TSource>' does not contain a definition for 'Shared'
Unity2022

**Comment by do3jack** [comment]
I also encountered this problem, how do you solve it?
