### ISSUE TITLE
Repository maintenance

### ISSUE THREAD

**Issue by Razenpok** [Cysharp/UniTask#60]
Hey @neuecc 

Looks like PRs are piling up and some really good contributions are hanging there for quite some time. I guess you have some hard time working on other projects and there's not much time left for you to work on this repo. I'm using this package extensively in my projects, so I can help with maintaining it if you are up for it.

**Comment by neuecc** [comment]
I had tried several times, but stopped.
I know it's not good, so I'm hoping to start responding soon.

**Comment by Razenpok** [comment]
Well, I have an experience in developing/maintaining projects to not screw up this one (you can look at my profile), so it shouldn't be that bad.

**Comment by Nyankoo** [comment]
It would be nice when someone would actually take care of this repo, as issues and unanswered questions still pile up, too.

**Comment by neuecc** [comment]
Yes, it's a good thing that we're working together.
But I'm sorry, I couldn't understand your skill by looking at your profile.

**Comment by Razenpok** [comment]
Fair enough.
I'm still up for this, so feel free to reach out to me if you need a helping hand.

**Comment by neuecc** [comment]
I'm about to finish v2, but I'm making some major internal changes.
I don't think anyone is familiar with V2's design yet, so
To some extent, we'll think about it again after some time.
