### ISSUE TITLE
SuppressCancellationThrow Is Not work in Dotween Plugins

### ISSUE THREAD

**Issue by chasinghope** [Cysharp/UniTask#618]
UniTask 2.5.5
DOTweenPro v1.0.381

Detail See Image:

![Issue](https://github.com/user-attachments/assets/003d5f94-84cf-4a1b-a757-067ae8df1118)

I think "Test1"  should be True

**Comment by dvsilch** [comment]
Maybe you should use `ToUniTask()` instead of `WithCancellation()`, and pass a `TweenCancelBehaviour` as the screenshot of source code below

![image](https://github.com/user-attachments/assets/dfaeb0a4-08d1-4245-8175-2e39a4071a3d)

**Comment by kochounoyume** [comment]
See also this thread.

It is a specification that OperationCanceledException is not thrown when `WithCancellation()` is used.

#526

**Comment by chasinghope** [comment]
Thank you for solving my problem.
