### ISSUE TITLE
Compilation errors in Unity 2020.1 or older

### ISSUE THREAD

**Issue by nowsprinting** [Cysharp/UniTask#624]
Compilation errors in Unity 2020.1 or older (below C# 8.0):
```
Library/PackageCache/com.cysharp.unitask@2.5.9/Runtime/UniTask.WhenEach.cs(42,34): error CS1002: ; expected
Library/PackageCache/com.cysharp.unitask@2.5.9/Runtime/UniTask.WhenEach.cs(42,35): error CS1525: Invalid expression term ';'
Library/PackageCache/com.cysharp.unitask@2.5.9/Runtime/UniTask.WhenEach.cs(148,17): error CS0106: The modifier 'static' is not valid for this item
```

This project setting is Unity 2022.3.39f1, but the Unity version required for the package is 2018.4 (in package.json).

Please choose to fix the compilation errors or update the Unity version required for the package.

**Comment by neuecc** [comment]
Thanks, I'm completely forgotten it.
fixed.
