### ISSUE TITLE
GetResult() crash after task completion

### ISSUE THREAD

**Issue by CoderGamester** [Cysharp/UniTask#637]
`InvalidOperationException: Token version is not matched, can not await twice or get Status after await.
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:342)`

This error is thrown with the following code

```
UniTask<TextAsset> task = Resources.LoadAsync<TextAsset>("foo").ToUniTask();
await UniTask.WhenAll(task, [.... many other bit amount of tasks here, or list of tasks]);
Debug.Log(task.GetAwait().GetResult());
```

Is this intentional?
I was able to solve it with the following, and weird fix for me to Convert to Tasks and UniTasks back and forth

```
Task<TextAsset> task = Resources.LoadAsync<TextAsset>("foo").ToUniTask().AsTask();
await UniTask.WhenAll(task.AsUniTask(), [.... many other bit amount of tasks here, or list of tasks]);
Debug.Log(task.Result);
```

Would love to have some more insights or better use of the Library for a dev that is costumed to C# Tasks

**Comment by neuecc** [comment]
`var results = await UniTask.WhenAll();`

**Comment by CoderGamester** [comment]
Thank you
That works for this example, but becomes an issue if I deferred the asses of the result in a synchronous call, it only works if converting to Task.

Example code 

```
public UniTask<Sprite> LoadAsset(bool loadSynchronously)
{
    AssetReferenceSprite spriteReference = GetRandomSpriteAssetReference();
    spriteReference .LoadAssetAsync()
    
    if(loadSynchronously
        spriteReference .OperationHandle.WaitForCompletion();
    else
        await assetReference.OperationHandle.ToUniTask();

    return sprite.Asset as Sprite;
}

public void ShowSprite()
{
    GetComponent<Image>().Sprite = LoadAsset(true).AsTask().Result;
}
```

If I do `LoadAsset(true).GetAwaiter().GetResult()`, the package get's the same error mentioning above.
The main issue is deferred access of the UniTask calls, specially in cases where Pre-Loading Addressables or other assets becomes important. Leading to rely on Task conversion to mate it work.

Is there another solution for this cases?

**Comment by neuecc** [comment]
Using GetAwaiter().GetResult() in UniTask is not recommended.
Unless you fully understand it, it's unlikely to work properly in most cases.
And UniTask cannot perform synchronous operations.
Always use await, or structure your code to enable awaiting.
This is the quickest path to proper architecture.
While await is mandatory, it's acceptable for the await result to return synchronously.
In other words, when written this way, although you're using await, it effectively becomes a synchronous operation.

```csharp
public async void ShowSprite()
{
    GetComponent<Image>().Sprite = await LoadAsset(true);
}
```
