### ISSUE TITLE
[ItemNotNull] doesn't work with UniTask in Unity

### ISSUE THREAD

**Issue by Kotsuha** [Cysharp/UniTask#642]
Hello, thank you for this wonderful Unity async package.

I recently started to use JetBrains.Annotations attributes when I write Unity code in JetBrains Rider. There are some attributes to mark if a return value of a method can/cannot be null. Some of them have issue with UniTask. For example:

![Screenshot_mod](https://github.com/user-attachments/assets/6cdf40e3-8ace-4ccf-bc68-1ba557af5b21)

In line 76, the attribute is gray, which is not as expected.

Since I know nothing about how things work under the hood, I don't know where to report the issue. I've already made a post in Rider forum. No response currently. I decide to also make a post here.

**Comment by neuecc** [comment]
Thank you, but since this is a JetBrains issue requiring their own analysis, there's nothing we can do on our end.

**Comment by Kotsuha** [comment]
Thank you for the reply. Let me close this issue.
