### ISSUE TITLE
Is UniTask.DelayFrame(1) and UniTask.NextFrame() the same?

### ISSUE THREAD

**Issue by Kotsuha** [Cysharp/UniTask#644]
This is a trivia question but it's been puzzling me for a while. Are `UniTask.DelayFrame(1)` and `UniTask.NextFrame()` essentially the same?

**Comment by neuecc** [comment]
NextFrame will 'always' send to the next frame, but with DelayFrame, depending on the execution timing, it may be in the same frame (at a different PlayerLoopTiming)

**Comment by Kotsuha** [comment]
Thanks for clarifying
