### ISSUE TITLE
how can i await Assetbundle load assets?

### ISSUE THREAD

**Issue by woshihuo12** [Cysharp/UniTask#67]
AssetBundleRequest assetRequest = await assetBundle.LoadAllAssetsAsync();
so how can i use above method?

**Comment by neuecc** [comment]
`LoadAllAssetsAsync` and `LoadAssetAsync`, both returns `AssetBundleRequest`.
UniTask's awaiter extension methods can not distinguish which are expected.
Therefore, the return value of await is now `.asset`.

There is no choice but to write as follows.

```csharp
var assetRequest = assetBundle.LoadAllAssetsAsync();
await assetRequest;
// use assetRequest...
```

**Comment by woshihuo12** [comment]
thanks.
