### ISSUE TITLE
Installation Process ...

### ISSUE THREAD

**Issue by stonstad** [Cysharp/UniTask#68]
Running the unity package extracts code.  But the Assembly-CSharp project generated by Unity is unable to access UniTask classes.  I'm wondering if this is an amsdef setting that might need to change?

**Comment by neuecc** [comment]
Hmn, I can't reproduce it.
UniTask is defined by asmdef, could you reference it?

**Comment by stonstad** [comment]
Hi neuecc -- restarting Unity and reloading fixed it.  No idea why this happened the first time.  Please consider this a candidate for closure.
