### ISSUE TITLE
Broken Yield and Delay (in 1.3.0+)

### ISSUE THREAD

**Issue by kamyker** [Cysharp/UniTask#70]
I've updated to 1.3.1 using git/packages installation and whole project is broken. Something like:
```
private async void Awake()
{
    await Test(); //or Test().Forget();
}

async UniTask Test()
{
	Debug.Log( "1" );
	await UniTask.Delay(1);
	Debug.Log( "2" );
	await UniTask.Yield();
	Debug.Log( "3" );
}
```
Prints only "1"

Tried it in empty project and it's fine there. Any ideas?

**Comment by kamyker** [comment]
Tried different versions, it breaks exactly when going from 1.2.0 to 1.3.0.

**Comment by neuecc** [comment]
I tried it with the Empty Project, but it's fine.
I can't reproduce it, so I don't understand.

Maybe PlayerLoop is gone, so
Try calling `PlayerLoopHelper.Initialize` at a reasonable place.

**Comment by kamyker** [comment]
Yes, I've also "tried it in empty project and it's fine there." Something in my project collides with newer UniTask version.

**Comment by neuecc** [comment]
PlayerLoop is initialized with `[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]`, but the order of this is undefined.
And since Entities are overridden by the DefaultLoop, Entities will be erased UniTask's loop.
This is a bug in the Entitites Package (I hope to use CurrentLoop)
In any case, initializing the UniTask after initializing the Entities will solve the problem.

**Comment by kamyker** [comment]
That seems to be the case, thanks. Warning to readme should be added.

**Comment by TigerHix** [comment]
Same issue and the above solution did not solve my problem. Specifically I created an `Initialization` script with lowest script executing order (so it should run first) with below code:

```
    private async void Awake()
    {
        var playerLoop = UnityEngine.LowLevel.PlayerLoop.GetCurrentPlayerLoop();
        PlayerLoopHelper.Initialize(ref playerLoop);
        print("UniTask initializing");
        await UniTask.DelayFrame(0);
        print("UniTask initialized");
    }
```

Only the first `print` statement works.

**Comment by kamyker** [comment]
What if you try to print them in start?

**Comment by TigerHix** [comment]
Yes - I just wanted to comment that putting the code in `Start()` worked!

**Comment by kamyker** [comment]
Ye, I think Unity needs like a one frame to update its playerloop.
