### ISSUE TITLE
unitask takes up a lot of cpu on editor.

### ISSUE THREAD

**Issue by cn914287516** [Cysharp/UniTask#78]
unitask version:1.3.1
unity version:2019.3.11,2019.3.14

When I add unitask to my project, my pc cpu is taked 20% immediately。(i7 8750h)
And I open profiler to see and compare:
this is pic with added unitask 
![1CRPX9HX{P5ZEK2E~H)@UK1](https://user-images.githubusercontent.com/8104770/82736223-9aec0d00-9d5a-11ea-89ba-3fde788f25bb.png)

this is empty project
![{B8O7778OSE)VH0J_9(53M2](https://user-images.githubusercontent.com/8104770/82736250-d555aa00-9d5a-11ea-8753-74d09c82dc97.png)

**Comment by cn914287516** [comment]
I actually didn't notice this problem before, I only discovered it when I upgraded from the low version to 2019.3.14.

**Comment by neuecc** [comment]
Thank you for useful info.
Currently call `EditorApplication.QueuePlayerLoopUpdate` on every `EditorApplication.update`, and it causes performance issue.

I should fix it after 2.0 release.
Quick workaround, comment out `EditorApplication.QueuePlayerLoopUpdate()` in `PlayerLoopHelper.cs`.

**Comment by cn914287516** [comment]
Okay, now it's back to normal. 
Thank for reply and quick modify!
