### ISSUE TITLE
Cannot await twice exception when print(task.Status)

### ISSUE THREAD

**Issue by HyVong007** [Cysharp/UniTask#79]
UniTask Ver 2.0.10-rc7
Unity3D 2019.3.14f1 (Edit > Project Setting > Player > Other > Mono & .NET 4x; )

When I run this code in Editor mode in PC Mac and Linux Standalone mode:

```
private async void Start()
{
	var t = A();
	print(t.Status);
	await t;

	print(t.Status);  // Exception : cannot await twice ...
}


async UniTask A()
{
	await UniTask.Delay(1000);
}
```

Then I get the exception in Unity console .
I dont understand why I cannot check task.Status ???

**Comment by HyVong007** [comment]
here is my temporary fix:
![image](https://user-images.githubusercontent.com/20169967/82757412-79e2f500-9e0a-11ea-91bf-361666987b3c.png)

**Comment by neuecc** [comment]
It is not possible to get Status after await.
Status is get from inner tasksource, it is released after await, so same as await twice.
I think this is a bad error message, so I will add it to the error message.
Thank you.

**Comment by HyVong007** [comment]
> It is not possible to get Status after await.
> Status is get from inner tasksource, it is released after await, so same as await twice.
> I think this is a bad error message, so I will add it to the error message.
> Thank you.


Yes, thank you too ! I think task.Status should be available WHENEVER WE WANT !
And when the task is end, we can await the task peacefully (then the task is completed, so why cannot await ??? )
Now i must check if task is completed or not to be able to await task. It is a little crazy !

**Comment by HyVong007** [comment]
> It is not possible to get Status after await.
> Status is get from inner tasksource, it is released after await, so same as await twice.
> I think this is a bad error message, so I will add it to the error message.
> Thank you.

The UniTask should be able to be awaited WHENEVER WE WANT ! 
Why dont you make it the same like System.Threading.Task ?


```
static void Main()
	{
		Task.WaitAll(Entry());
		Console.WriteLine("End");
	}


	static async Task Entry()
	{
		var t = A();
		await t;
		await t;
		await t;
		await t;
	}


	static async Task A()
	{
		await Task.Delay(1000);
	}
```

**Comment by neuecc** [comment]
This rule is same as .NET Core 3's ValueTask and IValueTaskSource.
Your thinking of Task rules is outdated.
You need to radically rethink this.

**Comment by HyVong007** [comment]
> This rule is same as .NET Core 3's ValueTask and IValueTaskSource.
> Your thinking of Task rules is outdated.
> You need to radically rethink this.

Thank you, i will search more about C# async. I usually get "cannot await twice..." exception when i use task.Status or accidentally await task; I am very hard to find bugs. I suggest you write more documentation about Unitask. Thank you !

**Comment by codeabuse** [comment]
> It is not possible to get Status after await. Status is get from inner tasksource, it is released after await, so same as await twice. I think this is a bad error message, so I will add it to the error message. Thank you.

Still getting the same unclear error message in the same situation. Why can't I know the task status after it is awaited and how I supposed to track the task to cancel it if need to restart?
