### ISSUE TITLE
Does it run in Unity 2018.4.23f1?

### ISSUE THREAD

**Issue by laurentopia** [Cysharp/UniTask#80]
The doc says 2018.3 so maybe there is a setting to run this in LTS?
Beckend settings:
![image](https://user-images.githubusercontent.com/26075468/82882949-a2e0b400-9ef6-11ea-82b8-3ff2d669438d.png)

**Comment by neuecc** [comment]
Rather, it didn't work?

**Comment by laurentopia** [comment]
nope

**Comment by randomPoison** [comment]
I'm using UniTask in a project running on Unity 2018.4.11f1 and I largely haven't had any issues. What specific problems are you seeing?

**Comment by neuecc** [comment]
note: UniTask v2's lower support version will be `2018.4.13`.
