### ISSUE TITLE
UniTaskCompletionSource Should Support CancellationToken

### ISSUE THREAD

**Issue by Esam-Bustaty** [Cysharp/UniTask#81]
In the following example if the cancellation token was cancelled by calling `CancelWating()` the execution continues, and "Sample Task Is Done" will be logged.

Uncommenting `ct.ThrowIfCancellationRequested();` solves the problem of executing the rest of the method after cancellation, but it will still wait for the task we're awaiting to be done and only then it throws, this means that the task will be waiting indefinitely if the event source was destroyed (like if `Finish()` was never called in this example), this causes a memory leak.

Uncommenting `_completion.TrySetCanceled();` on the other hand cancels the task immediately, but it's not always possible (in most cases the cancellation token source is external) and it doesn't look pretty (I had to make the completion source a member to make this example work.

    UniTaskCompletionSource _completion;
    CancellationTokenSource _ctSource;

    async void Start()
    {
        _ctSource = new CancellationTokenSource();

        Invoke(nameof(Finish), 10f);

        await SampleTask(_ctSource.Token);
    }

    async UniTask SampleTask(CancellationToken ct)
    {
        _completion = new UniTaskCompletionSource();

        await _completion.Task;
        // ct.ThrowIfCancellationRequested();
        Debug.Log("Sample Task Is Done");
    }

    void Finish()
    {
        _completion.TrySetResult();
    }

    // bind this to a button
    public void CancelWaiting()
    {
        // _completion.TrySetCanceled();
        _ctSource.Cancel();
    }

**Comment by neuecc** [comment]
Hmn, I'm not sure what you want.
If you want to cancel a CompletionSource with a cancellation, please register it.
`ct.Register(() => _completion.TrySetCanceled());`

**Comment by Esam-Bustaty** [comment]
yeah.. that's what I was missing -_-

I spent too much time trying to find a constructor that takes in a cancellation token or a way to do `ConfigureAwait(cancellationToken: ct)` where I should've spent my time learning the basics.

thanks for the answer :)
