### ISSUE TITLE
Awaitable Events are reusable too but there is no mention in the docs

### ISSUE THREAD

**Issue by EthDra** [Cysharp/UniTask#82]
I've just spent a long while wondering why my OnCollisionEnterAsync task was never set to IsCompleted although the await continues, and then I saw in your source code that it was reusing the promises and thus never completing them.
You should add this remark to the docs, because this reusing is a strong deviation from the regular async/await pattern where after awaiting a task is always completed.
Even better, please make this reuse behaviour optional, with a "bool reuse" parameter set to false by default. This would be more compliant with regular async/await and will causes less surprises to newcomers like me.

Thanks,
  Ruben

**Comment by neuecc** [comment]
In v2(We're working on the documentation now, and we'll be releasing it in a few days)
OnCollisionEnterAsync(or another message trigger set `callonce:true`)
http://github.com/Cysharp/UniTask/blob/bfcd18aa/src/UniTask/Assets/Plugins/UniTask/Runtime/Triggers/MonoBehaviourMessagesTriggers.cs#L764-L767
and trigger itself implements `IUniTaskAsyncEnumerable<T>`(same as `IAsyncEnumerable<T>`),
it is same rule with regular async/await pattern.
Is this implementation equal to your expectations?

**Comment by EthDra** [comment]
So if I get it right, the new OnCollisionEnterAsync (and similar ones) will have callonce set to true and thus, will return a completed task after being awaited. If this is correct, yes, that would be perfect, thank you very much.
A similar change would happen with the other reusables, such as Yield or Delay? It's not as big issue as with other, as these ones are less likely to be checked, but again, being similar to regular async/await is important, IMHO.

**Comment by neuecc** [comment]
Thanks for checking.

* All UniTask/UniTask<T> can not await twice(will throw exception), Reusable Promise is discontinuance
* All UniTask Factory method(such as UniTask.Delay) run immediately(same as standard Task, previously it does not run before call await)

It follows the ValueTask/IValueTaskSource rules in .NET Core 3, but the overall behavior is the same as Task.
You're right, the behavior of UniTask v1 was different from Task and caused a lot of confusion.
This will all be fixed.

**Comment by EthDra** [comment]
That's perfect, thanks. I'll wait eagerly for the version 2 then.
