### ISSUE TITLE
Dll size need to reduce.

### ISSUE THREAD

**Issue by halleyxu** [Cysharp/UniTask#83]
Unitask 2 dll size upto 1.2m...

**Comment by neuecc** [comment]
It's the fault of LINQ support, so removing it will reduce it.
If you don't need it, please delete the directory.
Assembly separation is also being considered, but it's still undecided right now.

**Comment by neuecc** [comment]
Okay, now separated `UniTask.dll` and `UniTask.Linq.dll`

![image](https://user-images.githubusercontent.com/46207/83528892-9c6cc080-a524-11ea-8215-0ad8c8ccc1e4.png)
