### ISSUE TITLE
.NET Standard 2.0 support

### ISSUE THREAD

**Issue by Trojaner** [Cysharp/UniTask#84]
Would be great if you could add .NET Standard 2.0 support to the .NET Core NuGet package :)

**Comment by neuecc** [comment]
for zero allocation convert to ValueTask,
using interface default implementation in C# 8.0.
It is not supported by .NET Standard 2.0.

**Comment by Trojaner** [comment]
You could use the #if preprocessor directive to have different behavior on previous .NET versions

**Comment by neuecc** [comment]
already using.
https://github.com/Cysharp/UniTask/blob/master/src/UniTask/Assets/Plugins/UniTask/Runtime/IUniTaskSource.cs#L55-L91

.NET Standard 2.1 is zero cost to convert and 2.0 is not.
I don't like to see that kind of behavior making a difference.

**Comment by neuecc** [comment]
I've added netstandard 2.0 support, in next release will include it.

**Comment by neuecc** [comment]
I've released 2.0.14, it supports.

**Comment by Trojaner** [comment]
Thank you :)
