### ISSUE TITLE
v2 Task Lacking Result

### ISSUE THREAD

**Issue by GainDeveloper** [Cysharp/UniTask#94]
Hey!
Since switching to v2 from v1 the following isn't possible due to Result not being available.
```
List<UniTask<GameObject>> creatingGameObjectTasks = new List<UniTask<GameObject>>();

foreach (SavedGameObject savedGameObject in currentGameSaveCopy.savedPooledObjects)
{
	creatingSavedObjectTasks.Add(MethodReturningGameObjectTask(savedGameObject));
}

await UniTask.WhenAll(creatingGameObjectTasks);

foreach (UniTask<SaveableGameObject> x in creatingSavedObjectTasks.OrderByDescending(x => x.Result.Priority))
{
	x.Result.ApplySaveData();
}
```

If I understand correctly the appropriate way to do this now is to get the result directly from the WhenAll await.

`SaveableGameObject[] createdGameObjects = await UniTask.WhenAll(creatingGameObjectTasks);`

This is fine but it does seem unnecessary to allocate a new array when working with the objects in place worked fine?
I'm sure there's good reason for this I just wanted to understand what the reasoning was.

**Comment by neuecc** [comment]
UniTask itself is automatically returned to pool after await completed.
So can not get Result value twice(after awaited).

```csharp
var createdGameObjects = await UniTask.WhenAll(currentGameSaveCopy.savedPooledObjects.Select(x => MethodReturningGameObjectTask(x)));
```

**Comment by GainDeveloper** [comment]
Thanks for explaining.
