### ISSUE TITLE
Unitask v2でwindows buildしたアプリを終了しようとすると応答不能になる

### ISSUE THREAD

**Issue by edo0159** [Cysharp/UniTask#95]
Unitask Ver.2.0.18
Unity 2019.4.0f1
windows10

windows用にビルドしたアプリを終了しようとすると応答不能になります。
UniTaskを一度でもawaitすると応答不能になるようです。
Unitask Ver 1.3.1では上記の問題は発生しませんでした。

再現手順
1.空のプロジェクトを作成(Unity 2019.4.0f1)
2.Unitask Ver.2.0.18を導入
3.Start関数でDelayFrameを実行するようにする
	private async void Start() {
		await UniTask.DelayFrame(0);
	}
4.windows用にビルドする
5.アプリを起動して終了しようとすると応答不能

確認のほど、よろしくお願いいたします。

**Comment by neuecc** [comment]
ありがとうございます！
昨日ちょうどTwitterでも同様の話を受けていて調査しようと思っていたところなので、
報告助かります。

**Comment by guitarrapc** [comment]
I've confirm following reproduce result.

Script Backend | `async void` | `async UnitTaskVoid`
---- | ---- | ----
Mono | 💣 | 💣  |
IL2CPP | 🆗 | 🆗 |

```csharp
    async UniTaskVoid Start()
    {
        await UniTask.DelayFrame(0);
    }
```

```csharp
    async void Start()
    {
        await UniTask.DelayFrame(0);
    }
```

### Environment

* UniTask 2.0.18
* Unity 2019.3.9f1
* Backend: IL2CPP
* OS: Windows

**Comment by neuecc** [comment]
原因判明したので、修正します。
（デストラクタ内で`GC.ReRegisterForFinalize` したのが無限に発行されていたのが良くなかったので、そのへんの処理をやめます）

**Comment by edo0159** [comment]
@guitarrapc  Script BackendはMonoです。

**Comment by neuecc** [comment]
ありがとうございます、`2.0.19`で修正しました。
