### ISSUE TITLE
UniTask.Delay restricted to main thread?

### ISSUE THREAD

**Issue by f-maeda-V** [Cysharp/UniTask#96]
Hello, I'm trying to use UniTask.Delay on ThreadPool. ( used UniTask.Run )

an error occurred, on UniTask Ver.2.0.18, Unity 2019.4.0f1.
```

UnityException: get_frameCount can only be called from the main thread.
```

Time.frameCount is restricted to main thread.

Is this the intended behavior?

**Comment by neuecc** [comment]
thanks, fixed at `2.0.19`.
