### ISSUE TITLE
await UnityWebRequestAsyncOperation issue

### ISSUE THREAD

**Issue by Silentor** [Cysharp/UniTask#98]
Hello, and thank you for your work!

Please take a look at sample code at screenshot:
https://monosnap.com/file/YrszkJHzdJqJ0ntEUSTsnTRql0d9Al

I want to await at UnityWebRequestAsyncOperation, but compiler wants an AsyncOperationHandle. Yes, we use an Addressables in our project. If I comment out AddressableAsyncExtensions class, my code compiles as expected. But I want to keep adressables await support.
Maybe it is a some issue with UniTask compiler service?

**Comment by neuecc** [comment]
Thanks for reporting.
I can't reproduce it so please provide full reproducable code.

**Comment by laicasaane** [comment]
To reproduce this issue follow these steps:
1. Create an empty project
2. Add UniTask package
3. Add a script `Assets\Game\MyScript.cs`
4. Create `Assets\Game\Game.asmdef` and reference to UniTask
3. Write a simple download method in MyScript.cs
```
private async UniTask Download(UnityWebRequest req, string filePath)
{
    await req.SendWebRequest();
    File.WriteAllText(filePath, req.downloadHandler.text ?? string.Empty);
}
```

4. Add Addressables package. The error will appear immediately.
```
error CS0012: The type 'AsyncOperationHandle' is defined in an assembly that is not referenced. You must add a reference to assembly 'Unity.ResourceManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

So, to use UniTask with Addressables, the Game.asmdef must have a reference to Unity.ResourceManager.

This is fine for the Game project. But my other packages which don't have any dependency on Addressables will be broken if I use them in the Game project (which depends on Addressables).

**Comment by grashaar** [comment]
When I add this package to the main project, that error will occur.
[https://github.com/grashaar/Unity.GoogleSpreadsheet](https://github.com/grashaar/Unity.GoogleSpreadsheet)

**Comment by neuecc** [comment]
Thanks, there seems to be a problem with Unity's Soft Reference.
I will consider to separate amsdef.

**Comment by neuecc** [comment]
I've uploaded `2.0.20`, it may fix this.
https://github.com/Cysharp/UniTask/releases/tag/2.0.20
